### ISSUE TITLE
First Edition link funktioniert noch nicht richtig

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#101]

**Comment by alingnau** [comment]
Funktioniert aber die Anzeige der Publikationen funktioniert nicht richtig

**Comment by konczaknagel** [comment]
Eine Auswahl der 1. Edition ist zwar möglich, aber diese Auswahl wird nicht gespeichert, d.h. die Zeile ist bei erneutem Ansehen leer. Außerdem lässt sich nach dem Speichern auch keine Änderung mehr vornehmen.

**Comment by alingnau** [comment]
Auswahl wird gespeichert und beim öffnen auch wieder richtig gesetzt.
