### ISSUE TITLE
ToolTip für Location Filter

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#11]
wenn man über die Region und District Namen fährt sollte sich ein ToolTip öffnen

**Comment by alingnau** [comment]
Ines fragen was das bedeutet

**Comment by alingnau** [comment]
Hier weiß ich nicht, was das bedeuten soll. Stand mal so in einer Email.

**Comment by konczaknagel** [comment]
Es ging wohl darum, dass zwar Distrikte angezeigt wurden, es aber icht klar war, zu welchem buddhistischen Ort sie gehören. Das ist jetzt aber nicht mehr der Fall, da bei jedem Distrikt und auch bei jeder Region der dazugehörige Ort angezeigt wird.
