### ISSUE TITLE
Fehlende Icon-Beschriftungen (verschiedene)

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#113]
- im Filter-Bereich oben rechts: Feld nach links minimieren
- im Hauptfenser: Feld verkleinern und vergrößern
- im Hauptfenser: Feld minimieren oder maximieren
- im View-Bereich: Feld nach rechts minimieren
- im Painted Representation-Bereich / Images: Hilfe
- im Painted Representation-Bereich / Iconography ...: Liste ausklappen und Liste zusammenklappen

**Comment by alingnau** [comment]
Tool Tips wurden überall ergänzt. Beim Aus- und Einklappen ist das leider nicht möglich.
