### ISSUE TITLE
Benutzerebenen hinzufügen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#116]
1. Benutzer, der gar nicht eingeloggt ist.
	2. Benutzer mit eingeschränktem Gastzugang
	3. Benutzer mit uneingeschränktem Gastzugang
	4. Projektmitglieder
	5. Administrator, der neue Benutzer anlegen kann

**Comment by alingnau** [comment]
technical available but not yet implemented in UI

**Comment by alingnau** [comment]
Suche anpassen

**Comment by alingnau** [comment]
implemented, going live with next update
