### ISSUE TITLE
Ortsliste hinzufügen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#117]
So die Orte ebenfalls unter ihren alternativen Namen vom Benutzer gefunden werden können

**Comment by konczaknagel** [comment]
Sites with Buddhist murals in Kuča (with alternative place names)


A’ai
Aai 阿艾, アアイ

Duldur-Akur
Duldur Akhur, Duldur-Āqur, Duldur-ākhur, Duldul-okur, Douldour-Aqour, Duldul-Akur 夏哈吐尔 / 夏哈吐爾、乌什吐尔 / 烏什吐爾, Dwurudwuru-Akuru ドゥルドゥル・アクール, Duruduru-Okoru ヅルヅル・オコル

Kizil
Kezi’er 克孜尔 / 克孜爾, Hesele 赫色勒，Kızıl, Kyzil, Qïzïl, Qizil, Qyzyl, Kijiruキジル、Kijīru キジール

Kizilgaha
Kizil-Gargha, Kizil Kargha, Kizilkargha, Kizil-kāghe, Qizil Qargha, Qïzïlqarγa, Kızıl-karga, Kezi'ergaha 克孜尔尕哈 / 克孜爾尕哈， Kezikalahan 克子喀拉罕，Kijirugaha キジルガハ

Kumtura
Kumutula 库木吐拉 / 庫木吐拉, 库木吐喇, 庫木土拉， Kum-tura, Qumtura, Kumutora クムトラ

Mazabaha
Achik-Ilek, Ačigh Iläk, Ačiγ Iläk, Atschygh Ilaek, Azapaba, Mazarbaγ, Mazhabaha / Mazhaboha 玛扎伯哈 / 瑪扎伯哈, Mazhabohe 瑪扎伯赫, Mazabha マザバハ 

Simsim
Kiriš, Kīrish, Senmusaimu 森木塞姆, Simusimu  シムシム

Subashi
Subaši, Subashi 苏巴什 / 蘇巴什, Sabasi スバシ, Subeši, Hasatam, Hasatamu ハサタム, Längär,  Subasi Rengaru スバシ・レンガル

Taitai‘er
Taitai‘er 台台尔 / 臺臺爾, Taitaier, Taitairu タイタイル 

Tograk-eken
Toghrak-akin, Tograkeken, Tuhulake'aiken 吐乎拉克艾肯, Tuohulake'aiken 托乎拉克艾肯, Tuoyulakeaiken, Tokuraku-Aikan  トクラクアイカン

Wenbashi
Unbashi温巴什 / 溫巴什, Wenbasi  ウェンバシ

**Comment by alingnau** [comment]
done
