### ISSUE TITLE
Painted Representation Bibliography Autorensortierungs-Fehler

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#119]
nachdem man einmal unter „Bibliography“ die Autoren rückwärts alphabetisch geordnet hat, lässt sich das nicht mehr zurück stellen

**Comment by alingnau** [comment]
Ich kann den Fehler nicht nachvollziehen, bei mir lässt sich alles problemlos auswählen

**Comment by alingnau** [comment]
Editoren fehlen in der Ansicht und leere Felder werden vor A einsortiert. Es wird eine neue Version der Bibliographie Selection geben.
