### ISSUE TITLE
Bibliography-Suche (Filter)

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#120]
- Zur Suche: Es wäre schön, wenn man nicht nur nach Autor / Institution suchen könnte, sondern auch nach Editor, da einige Bücher nur einen Editor haben. Lässt sich das ändern?
- „Search Title sollte so überarbeitet werden, dass auch in Untertiteln (subtitle) gesucht wird.
- Unter Titel-Suche sollte auch der „Collection Title“ auffindbar sein.

**Comment by alingnau** [comment]
Neues search Model implementiert. Namenssuche erfolgt in Autor/Editor/Institut
