### ISSUE TITLE
Painted Representation Saving function need to be checked / modified

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#125]
Wenn ich bspw. eine Beschreibung einer Malerei unter Description in Painted Representation ändere, wird die Änderung gespeichert, selbst wenn ich auf "nicht speichern" klicke. Könnte das geändert werden?

**Comment by alingnau** [comment]
Die Änderungen wurden zwar nicht gespeichert, waren aber bis zu einem reload trotzdem weiterhin sichtbar. Der Fehler ist mit dem nächsten Update behoben.
