### ISSUE TITLE
Image Pool: Delete Images that are named as "LÖSCHEN"

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#128]

**Comment by alingnau** [comment]
done

**Comment by OKienzler** [comment]
Die Bilder mit "LÖSCHEN" sind noch vorhanden bzw. Neue hinzugekommen.

**Comment by erikradisch** [comment]
Ich schließe das mal, da ja jetzt selbstständig gelöscht werden kann
