### ISSUE TITLE
Alias Mail Address for guests who want to contact the project members or the technical support

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#130]
Andreas informiert sich bei Uwe Kretschmer, ob das Projekt eine einheitliche alias-E-Mail-Adresse erhalten kann, an die sich Besucher der Webseite wenden können

**Comment by ukretschmer** [comment]
Wir können gern eine solche Weiterleitungs-E-Mail einrichten, wie bspw. kucha@saw-leipzig.de. Hierfür wäre noch zu klären, wer dann der oder die Empfänger sein sollen. Schickt mir bitte einfach **per E-Mail** die entsprechende Adressatenliste, dann richte ich es.

**Comment by alingnau** [comment]
Wir haben in Rücksprache mit Monika Zin geklärt, dass zunächst Ines Konczak-Nagel als Ansprechpartnerin eingetragen werde soll. Ob dann später noch eine 2. Person dazu kommt wird noch geklärt.

**Comment by alingnau** [comment]
eingerichtet von Uwe Kretschmer
