### ISSUE TITLE
tiff-Image in Painted Representation is shown black

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#131]
Ein tiff-Bild in Painted Representations (Kiz 4, Kaminhöhle A) wird schwarz angezeigt. Wenn man das Bild öffnen möchte, zum näheren Betrachten, dann kann es nicht in einem eigenen Browser-Fenster geöffnet werden (wie z.B. jpgs), sondern nur gespeichert werden. Das gespeicherte Bild sieht dann normal aus.

**Comment by alingnau** [comment]
passiert offenbar immer noch bei sehr großen Bildern

**Comment by alingnau** [comment]
Der Fehler scheint im TIF zu sein. Hochladen auf Testserver um zu sehen, ob es dort auch Probleme gibt! 
Kizil110_SWLe_IB8376_B1086_GROSS

**Comment by alingnau** [comment]
Trat beim Testen nicht wieder auf, vermutlich ein Problem mit dem Chaching bzw. Thumbnail.

**Comment by konczaknagel** [comment]
Auf dem Testserver ist dieses Bild auch noch schwarz. Es handelt sich um:
Kizil004_SALe_InnerWall_Gen_Ph004_IB9203a_VD707.tif

**Comment by aisi1989** [comment]
Ja, das stimmt. Es ist ein bearbeitetes TIFF-Bild, das sehr groß ist (241 MB). Beim nochmaligen Hochladen wiederholte sich der Fehler: die Vorschau ist schwarz.

<img width="1440" alt="kis-test" src="https://user-images.githubusercontent.com/45682519/49995646-0d18c980-ff8d-11e8-91aa-ab99d28fbf3e.png">

**Comment by alingnau** [comment]
Es handelt sich um eine beschädigtes TIF. Das Bild hat eine Auflösung von 449 x 397 pixel, bei öffnen und erneutem Abspeichern reduziert sich die Größe von 269 MB auf 1,3 MB. Vermutlich wurde bei Bearbeiten das Vorschaubild als Original gespeichert. Demnächst wird man Bilder löschen können, dann kann man anschließend versuchen, die Original wieder herzustellen bzw. zu Beschaffen. Von meiner Seite kann ich da nichts machen.
