### ISSUE TITLE
Image view / display is makes browser slow

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#133]
Wenn man sich alle Bilder auf einmal anzeigen lassen möchte, wird der Browser unheimlich verlangsamt.

**Comment by alingnau** [comment]
Wird in zukünftiger Version abgestellt. Alle Bilder auf einmal wird dann nicht mehr möglich sein.

**Comment by alingnau** [comment]
workaround implemented: empty search filters will only return the first 100 images found
