### ISSUE TITLE
Decken Typen Typologie

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#14]
Die verschiedenen Arten der Decken können nicht ausgewählt werden (sind einfach nicht da im Selector)

**Comment by alingnau** [comment]
Ines erstellt Liste mit zu ergänzenden Decken- und Durchgangsbereiche (ceiling & reveal)

**Comment by konczaknagel** [comment]
Die Liste mit den Durchgangsbereichen findet sich bereits unter #35

**Comment by alingnau** [comment]
erledigt mit nächsten Update
