### ISSUE TITLE
District and Location Filter Sortierung nach Ort einrichten

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#145]
In der Suche nach Distrikt bzw. Region sollte zuerst der Ort "Site" wie Kizil, Kumtura etc. angegeben werden und dann Distrikt bzw. Region. Jetzt sind die jeweiligen Angaben alphabetisch sortiert und der Site erscheint zweitranging. Dadurch wird jedoch die Suche erschwert.

**Comment by alingnau** [comment]
solved with next update
