### ISSUE TITLE
Annotated Bibliography: Editoreneinträge bearbeiten möglich?

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#170]
Ist es noch möglich, die Editorenliste so umzuändern, dass sich Editoren wie Autoren noch im Nachhinein bearbeiten lassen?

**Comment by alingnau** [comment]
Editoren und Autoren sind identisch und werden lediglich über individuelle Listen ausgewählt. Es genügt, oben bei Autore eine Änderung zu machen.

**Comment by alingnau** [comment]
falsches image. Funktion war vorhanden (PLUS Button links), ab Version 0.9.1 Zahnrad Button (=edit)
