### ISSUE TITLE
Anpassung Ornamentation Editor

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#192]
- [x] "Pictorial elements" (in "new Cave Relation") entfernen.

- [x] Auswahlmöglichkeiten für „Function“ auf 6 begrenzen, nämlich:
- framing band
- dividing band
- patterned frieze
- filling motif (area-wide motif)
- filling motif (isolated motif) 
- background motif

- [x] Bei der Eingabe von Daten über eine Höhle (in "add Cave") sollte man die betreffende Höhle direkt auswählbar machen und nicht den Distrikt. Der Distrikt muss sich stattdessen automatisch nach der Höhle aussuchen.

- [x] Anzeige der Höhlen wie in Painted Representaion

- [x] "2. General" komplett löschen

- [x] "Select inner secondary patterns" löschen

- [x] Begriff "Frame" als Auswahlmöglichkeit in "Position" für alle Wände hinzufügen.

- [x] Nach der Suche, die Ornamente nach der Kode anzeigen lassen (nicht nach dem ID).

- [x] Dopplungen löschen, die man in "Position" findet (z. B. zweimal "unknown").

- [x] "description" (in "1. General") in "type description" umbenennen.

- [x] "1. General" in "basics" umbenennen.

- [x] "3. General" in "components" umbenennen

- [x]  in "select ornament components" (in 3. General) ermöglichen es, eine Komponente zu löschen, nachdem sie ausgewählt und in der rechten Spalte eingefügt wurde.

- [x] Es fehlt den Begriff "other" in "Position" (nur wenn man ein "ceiling" auswählt).

- [x] Verknüpfung für ein Erklärungsschema (für "Position")

- [x] Ornamente mit Code "delete" löschen.

- [x] "Similarities with elements of other cultural areas" löschen

**Comment by LucaDeF** [comment]
- [ ] Suchfunktion für "Sites" hinzufügen

**Comment by LucaDeF** [comment]
- [ ] Verknüpfung für ein Erklärungsschema (für "Position")

**Comment by LucaDeF** [comment]
- [ ] Begriff "Frame" als Auswahlmöglichkeit in "Position" für alle Wände hinzufügen.
- [ ] Begriffe "main   band", "inner band", "outer band", "secondary band", "other" und "unknown" als Auswahlmöglichkeit in "Function" für "Frame" hinzufügen.
- [ ] Dopplungen löschen, die man in "Position" findet (nur wenn man ein "ceiling" auswählt).
- [ ] Es fehlt den Begriff "other" in "Position" (nur wenn man ein "ceiling" auswählt).

vgl. die Tabelle

[Ornamentation Terminology (Walls-Position-Function).pdf](https://github.com/saw-leipzig/kucha/files/2819554/Ornamentation.Terminology.Walls-Position-Function.pdf)

**Comment by LucaDeF** [comment]
- [ ] "description" (in "1. General") in "type description" umbenennen.
- [ ] Bei der Eingabe von Daten über eine Höhle (in "add Cave") sollte man die betreffende Höhle direkt auswählbar machen und nicht den Distrikt. Der Distrikt muss sich stattdessen automatisch nach der Höhle aussuchen.

**Comment by LucaDeF** [comment]
- [ ] in "select ornament components" (in 3. General) ermöglichen es, eine Komponente zu löschen, nachdem sie ausgewählt und in der rechten Spalte eingefügt wurde.

**Comment by erikradisch** [comment]
sehe ich es richtig, dass sich hier auch alles erledigt hat?

**Comment by LucaDeF** [comment]
Lieber Erik,

ich habe nur kurz die Ornamentation editor mich angeschaut, es sieht
tatsächlich alles richtig zu sein. Nun gibt es noch einen Fenster den
eigentlich auch entfernen sein sollte und zwar den "Pictorial elements" in
"new Cave Relation" (screenshot im Anhang). Wir hatten schon einmal darüber
gesprochen, aber ich habe es wohl vergessen in Github hinzufügen (ich habe
es erst jetzt bemerkt). Das ist dann meinen Fehler, ich entschuldige mich
dafür, aber seitdem wir die Baumstruktur in "Basics" haben, brauchen wir
diesen Fenster auch nicht mehr!! Ich hoffe, es kostet nicht zu viel Muhe
und viel Zeit das jetzt zu entfernen!! Ich füge die Sache auch in Github!!
Ausserdem werde ich während des Wochenendes den DB richtig anschauen, um zu
kontrollieren, ob es Tatsäschlich alles richtig funktioniert!!

vielen Dank Erik und bis Dienstag!!
Luca

Il giorno ven 21 feb 2020 alle ore 15:58 erikradisch <
notifications@github.com> ha scritto:

**Comment by LucaDeF** [comment]
Ich hab den entsprechende Punkt wieder in  Anpassung Ornamentation Editor
(#192) hinzugefügt!!


Il giorno ven 21 feb 2020 alle ore 16:27 Luca De Fabritiis <
defabritiis.luca@gmail.com> ha scritto:

**Comment by LucaDeF** [comment]
folgenden vier alten Punkten bleiben offen:
 
- Auswahlmöglichkeiten für „Function“ auf 6 begrenzen: framing band; dividing band; patterned frieze; filling motif (area-wide motif); filling motif (isolated motif); background motif

- Nach der Suche, die Ornamente nach der Kode anzeigen lassen (nicht nach dem ID).

-  in "select ornament components" (eher 3. General) ermöglichen es, eine Komponente zu löschen, nachdem sie ausgewählt und in der rechten Spalte eingefügt wurde.

- Ornamente mit Code "delete" löschen.

**Comment by erikradisch** [comment]
Kann das geschlossen werden?

**Comment by LucaDeF** [comment]
Teoretisch bleibe es noch:

- Auswahlmöglichkeiten für „Function“ auf 6 begrenzen: framing band; dividing band; patterned frieze; filling motif (area-wide motif); filling motif (isolated motif); background motif
- Nach der Suche, die Ornamente nach der Kode anzeigen lassen (nicht nach dem ID).

aber, mit der neuen Organisation, die beide mussen wahrscheinlich wieder besprechen werden. Es ist dann in Ordnung erst mal schließen. Wann wir eine Lösung haben, öffnen wir die Punkte wieder!!
