### ISSUE TITLE
Painted Representation Filter

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#200]
- Painted Representation -> Iconography search -> im Filter ist nur ein Teil des Namens sichtbar „Iconography“ anstatt „Iconography search“ 

- Eindeutige Abgrenzungen im Filter Bereich (z.B. zwischen den Reitern)

**Comment by konczaknagel** [comment]
-  Painted Representation -> Iconography search -> Es wäre schön, wenn sobald ein Suchbegriff eingegeben wurde, sich das Feld, in dem der Begriff angezeigt wird, automatisch aufklappt, damit der Begriff sichtbar ist

- Painted Representation -> Iconography search -> lassen einzelne Suchbegriffe sich aus der Liste der angezeigten Suchbegriffe unkomplizierter löschen, als sie erst wieder einzugeben und dann das Häckchen bei dem einzelnen Begriff zu entfernen

**Comment by erikradisch** [comment]
Ich meine, ich habe es jetzt so gemacht, dass man jetzt die Kinder über die Eltern löschen kann. Sprich: Wenn Du beispielsweise Iconography abwählst, werden auch gleich alle Unterpunkte der Iconography mit abgewählt.
Kann das damit geschlossen werden?

**Comment by konczaknagel** [comment]
Die Suche ist immer noch etwas kompliziert. Wenn man einen Begriff eingibt, kann man sich problemlos alle Suchergebnisse anzeigen lassen. Wenn man zusätzlich einen anderen Begriff eingibt, wird im Baum nicht angezeigt, dass schon ein Begriff eingegeben ist, sondern nur links in dem Menü, das man erst ausklappen muss. Dass die bereits ausgewählten Begriffe ohne Häckchen erscheinen, macht es noch komplizierter, sie wieder abzuwählen.

**Comment by erikradisch** [comment]
wäre es hilfreich, wenn ich eine Checkbox einfüge: Do not filter checked Items?
Dann könnte man theoretisch drei mal z eingeben und sieht alle ausgewählten Felder.

**Comment by konczaknagel** [comment]
![grafik](https://user-images.githubusercontent.com/45167567/78226018-659a1000-74cb-11ea-8fac-4ec2fdc895d9.png)

Wie kann ich den Suchbegriff wieder abwählen, wenn er als nicht gewählt angezeigt ist, wie in diesem Beispiel Dipamkara?

**Comment by erikradisch** [comment]
Das sollte natürlich gehen. schau mal bitte. In Kucha-Test habe ich den Bug hoffentlich behoben.

**Comment by konczaknagel** [comment]
Bei mir ist immer noch das gleiche. Trotz löschen des Caches usw.

**Comment by erikradisch** [comment]
In Kucha-Test? Bei der Iconography-Search? Da geht das bei mir jetzt...

**Comment by OKienzler** [comment]
Liebe Ines, lieber Erik,

ich habe es auch gerad ein Kucha Test (nach Cache löschen und so)
ausprobiert, bei mir ist alles so wie Ines schreibt. man kann die
ausgewählte Items nicht sehen und auch nicht abwählen.

LG Olga

Am Do., 2. Apr. 2020 um 11:33 Uhr schrieb erikradisch <
notifications@github.com>:

**Comment by erikradisch** [comment]
Ihr meint doch das so wie hier in dem Video, oder?

https://cloud.saw-leipzig.de/s/HKtLRNGmyMkyxHL

**Comment by OKienzler** [comment]
Ja so habe ich es gemeint :) ich probiere es noch mal aus 

Von meinem iPhone gesendet

**Comment by OKienzler** [comment]
Nee, geht bei mir nicht. Auch den Baum über die Funktion oben rechts kann
ich nich aufklappen:

[image: grafik.png]


Am Do., 2. Apr. 2020 um 12:05 Uhr schrieb erikradisch <
notifications@github.com>:

**Comment by konczaknagel** [comment]
Bei mir geht jetzt leider gar nichts mehr. :-(
![grafik](https://user-images.githubusercontent.com/45167567/78241799-47d7a580-74e1-11ea-9c78-a2e9417bedf2.png)

**Comment by erikradisch** [comment]
kann sein, dass ich das gerade war. bitte nochmal versuchen.

**Comment by erikradisch** [comment]
Im Grunde ist der letzte Screenshot übrigens eine Lösung für den Bug: Null Items ausgewählt -> null Items übertragen. Funktioniert also. ;-)

**Comment by erikradisch** [comment]
achso. Und Cache leeren.

**Comment by erikradisch** [comment]
kann das geschlossen werden?

**Comment by konczaknagel** [comment]
Bei mir ist immer noch ein leeres "iconography Selector" :-( Trotz Cache löschen.

**Comment by OKienzler** [comment]
bei mir ist es jetzt auch so (cache gelöscht und eben probiert):

[image: grafik.png]


Am Do., 2. Apr. 2020 um 13:27 Uhr schrieb konczaknagel <
notifications@github.com>:

**Comment by erikradisch** [comment]
und jetzt?

**Comment by erikradisch** [comment]
das ist doch zum verrückt werden. bei mir klappt das ohne Probleme:
![Bildschirmfoto von 2020-04-02 18-17-52](https://user-images.githubusercontent.com/34335811/78272853-55efeb00-750e-11ea-84fe-572b90b1031f.png)

**Comment by konczaknagel** [comment]
Es verhält sich interessanterweise anders, wenn ich die Suche nicht durch type forward, sondern wie in Deinem Video durch Aufklappen des Verzeichnisbaumes starte. Dann bleibt der Suchbegriff angeklickt, ABER er wird nicht im Menü links angezeigt, obwohl matching elements = 1 steht UND die Suche funktioniert nicht, d.h. im Beispiel unten wird nicht nach Dipamkara gefiltert. 

![grafik](https://user-images.githubusercontent.com/45167567/78272937-6f913280-750e-11ea-82fc-bb0a8b243ae6.png)

**Comment by erikradisch** [comment]
Also nochmal zum mitmeiseln:
Du öffnest zuerst den Iconography-Filter
Dann wählt Du etwas aus und schließt es
Danach öffnest Du ein zweites mal de Iconography-Filter und willst das abwählen, da ist es aber schon nicht mehr ausgewählt?

**Comment by erikradisch** [comment]
INES!!! Kuchatest!!!

**Comment by konczaknagel** [comment]
TSCHULDIGUNG!

**Comment by erikradisch** [comment]
:-)) geht's da?

**Comment by konczaknagel** [comment]
Yep, jetzt funktioniert die Suche einwandfrei. :-)

**Comment by OKienzler** [comment]
Bei geht es jetzt auch :) 

Von meinem iPhone gesendet
