### ISSUE TITLE
Ornamentation Editor (Fehler)

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#202]
- [x] Es ist jetzt nicht möglich, einen neue Ornamentkarteikarte zu erstellen (in Kuchatest). 

- [x] Das Fehlerfenster "Ornament already assigned" öffnet sich jedes mal, wenn man die Eingabe einer Ornament editiern will.

- [x] es ist nicht möglich, eine zusätzliche Wand (und deren Positionen) zu einer bereits existierenden Höhle hinzuzufügen (oder sie wird nicht angezeigt).
 
- [x] nur die erste hinzugefügte Wand wird in der Liste der Wände (in "Cave") angezeigt.

- [x] die Liste der Höhlen (in 1. General) enthält höchstens 23 Höhlen. Ab dem 24ten werden sie nicht mehr in der Liste angezeigt.

- [x] es ist nicht möglich, die "components" [in "select ornament components" (in "3. General")] nach die rechte Spalte zu verschieben und damit es auszuwählen.

 - [x]  es ist nicht möglich, die "related ornaments" [in "relations" (in "add cave")] nach die rechte Spalte zu verschieben und damit es auszuwählen.

- [x] man kann einen "Motif" umbenennen, aber der zeigt sich in dem Drop-down menu weiter mit dem alten Begriff. 

- [x]  die Umbenennung einer "Motif" wird nicht gespeichert. Ermöglichen es, die Motive zu umbenennen oder die Möglichkeit hinzuzufügen, alte Begriffe zu löschen.

- [x] es ist nicht möglich die Positionen und die Funktionen hinzufügen, wenn die Höhletyp als "other" gespeichert ist.

- [x]  wenn man mehrere Bilder hochgeladen hat, kann man nicht feststellen, welches als Icon angezeigt wird (ich vermute, das Icon wird automatisch aus den hochgeladenen Dateien in alphabetischer Reihenfolge ausgewählt).

- [x] es ist nicht möglich die Positionen, die Funktionen und deren Notizfeld speichern, ohne die Wand auszuwählen (z.B. im Falle eines Fragments, von dem die Wand, zu der es gehört, unbekannt ist).

- [x] es ist nicht möglich die Position der Ornamente in der Höhle 83 zu editieren

- [x]  es ist nicht möglich die Positionen und die Funktionen für den "Ceiling" von Höhle 189 eingeben.

- [x] Es gibt zwei ornamente mit dem Code Kiz25.6a: der zweiter davon löschen (es ist nicht möglich die name des Code in "delete" ändern).

- [x] Löschen den Punkt "Emulations from Textile
Materials", der unter "Mountain Landscape" erscheint .

**Comment by LucaDeF** [comment]
- [ ] es ist nicht möglich, alle "components" [in "select ornament components" (in "3. General")] nach die rechte Spalte zu verschieben und damit es auszuwählen. 
- [ ] es ist nicht möglich, die "related ornaments" [in "relations" (in "add cave")] nach die rechte Spalte zu verschieben und damit es auszuwählen.

**Comment by LucaDeF** [comment]
- [ ] die Umbenennung einer "Motif" wird nicht gespeichert. Ermöglichen es, die Motive zu umbenennen oder die Möglichkeit hinzuzufügen, alte Begriffe zu löschen.

**Comment by LucaDeF** [comment]
- [ ] Wenn man mehrere Bilder hochgeladen hat, kann man nicht feststellen, welches als Icon angezeigt wird (ich vermute, das Icon wird automatisch aus den hochgeladenen Dateien in alphabetischer Reihenfolge ausgewählt).

**Comment by LucaDeF** [comment]
- [ ] nur die erste hinzugefügte Wand wird in der Liste der Wände (in "Cave") angezeigt.

**Comment by LucaDeF** [comment]
+ Es ist nicht möglich die Positionen und die Funktionen hinzufügen, wenn die Höhletyp als "other" gespeichert ist.

**Comment by LucaDeF** [comment]
Die Liste der Höhlen (in 1. General) enthält höchstens 23 Höhlen. Ab dem 24ten werden sie nicht mehr in der Liste angezeigt.

**Comment by LucaDeF** [comment]
es ist nicht möglich die Positionen und die Funktionen für den "Ceiling" von Höhle 189 eingeben.

**Comment by LucaDeF** [comment]
es ist nicht möglich die Positionen, die Funktionen und deren Notizfeld speichern, ohne die Wand auszuwählen (z.B. im Falle eines Fragments, von dem die Wand, zu der es gehört, unbekannt ist).

**Comment by erikradisch** [comment]
bitte mal überprüfen, ob in Kuchatest alles zur Zufriedenheit funktioniert. Wenn nicht, bitte wieder öffnen.

**Comment by LucaDeF** [comment]
folgenden alten Punkten bleiben öffen:

-  es ist nicht möglich, die "components" [in "select ornament components" (in "3. General")] nach die rechte Spalte zu verschieben und damit es auszuwählen.

- Es gibt zwei ornamente mit dem Code Kiz25.6a: der zweiter davon löschen (es ist nicht möglich die name des Code in "delete" ändern).

- Löschen den Punkt "Emulations from Textile
Materials", der unter "Mountain Landscape" erscheint .

**Comment by LucaDeF** [comment]
ein neuen Punkt wurde geöffnet:

-  Es ist jetzt nicht möglich, einen neue Ornamentkarteikarte zu erstellen (in Kuchatest).

**Comment by LucaDeF** [comment]
folgenden alten Punkten bleiben offen:

- es ist nicht möglich, die "components" [in "select ornament components" (in "3. General")] nach die rechte Spalte zu verschieben und damit es auszuwählen.

- Es gibt zwei ornamente mit dem Code Kiz25.6a: der zweiter davon löschen (es ist nicht möglich die name des Code in "delete" ändern).

- Löschen den Punkt "Emulations from Textile Materials", der unter "Mountain Landscape" erscheint .

**Comment by LucaDeF** [comment]
ein neuen Punkt wurde geöffnet:

- Es ist jetzt nicht möglich, einen neue Ornamentkarteikarte zu erstellen (in Kuchatest).

**Comment by erikradisch** [comment]
Die Components sollte ich einmal komplett Löschen, oder?

**Comment by LucaDeF** [comment]
richtig!!

**Comment by erikradisch** [comment]
Die Jungfreulichkeit der Componenten is wiederhergestellt. ;-)

**Comment by LucaDeF** [comment]
sehr gut!!
