### ISSUE TITLE
Bibliography: Speichern bestimmter Einträge nicht möglich

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#215]
Article:
Title: 新疆库木 吐 喇 窟群区第 5 0 窟主室正壁龛 内 题记 (Inscriptions in the Niche on the Main Wall of the Main Chamber of Cave No. 50 of the Kumtura Grottoes in Xinjiang)

Journal: The Western Regions Studies, vol. 3 (2015), pp. 16–35

DOI: 10.16363/j.cnki.xyyj.2015.03.003

Autoren:
Xinjiang Kucha Academy 新疆 龟 兹研 究 院
Center for Research on Ancient Chinese History, Peking University 北 京 大 学 中 国 古代 史研究 中 心 
Institute for Historical and Philological Studies in China's Western Regions, School of Chinese Classics, Renmin University of China 中 国 人 民 大 学 国 学 院 西 域历 史 语 言研究 所

**Comment by erikradisch** [comment]
Das Sind ja jetzt nur Institutionen als Autoren. Hast Du die bei Editoren reingenommen oder komplett rausgelassen?

**Comment by erikradisch** [comment]
Ich glaube, das können wir schießen, oder?
