### ISSUE TITLE
Bibliography: Wenn die englische Übersetzung des Original-Titels als "official" gekennzeichnet wird, erscheint der englische Titel zwei Mal: einmal in runden und einmal in eckigen Klammern

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#216]
gewünscht ist bei der offiziellen Übersetzung lediglich die Angabe des englischen Titels in runden Klammern

**Comment by erikradisch** [comment]
Sollte behoben sein, bitte in Kuchatest überprüfen.

**Comment by konczaknagel** [comment]
Vielen Dank, das ist jetzt tatsächlich behoben.
Wir haben jedoch vor kurzem eine Neuerung eingeführt und zwar, dass der offizielle englische Titel nicht in runden Klammern angegeben wird, sondern durch einen / vom asiatischen Titel getrennt wird. Z.B. 
Shinshutsu Loulan Hekiga ni kansuru ni san no Kosatsu 新出楼蘭壁画に関する二、三の考察 / A Study in the Recently Found Mural from Loulan in China
nicht 
Shinshutsu Loulan Hekiga ni kansuru ni san no Kosatsu 新出楼蘭壁画に関する二、三の考察 (A Study in the Recently Found Mural from Loulan in China)

Ist das änderbar?

**Comment by erikradisch** [comment]
sollte jetzt korrekt in kuchatest abgeändert sein.
