### ISSUE TITLE
Icons in der oberen Reihe verschwinden manchmal (mouse over funktioniert zwar noch, Symbol ist aber nicht zu sehen)

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#217]

**Comment by erikradisch** [comment]
Kannst Du spezifizieren, wann das in etwa passiert? Ich kann den Fall nicht reproduzieren.

**Comment by erikradisch** [comment]
Mein Eindruck ist, dass das nur kurz nach dem Laden passiert. Kannst Du das bestätigen? Wenn ja, brauchen die Bilder schlicht, ein wenig, bis sie geladen sind.

**Comment by erikradisch** [comment]
tritt das Problem in der neuen Version noch auf?
