### ISSUE TITLE
Skalierung funktioniert nicht (auf großem Bildschirm alles in Ordnung, auf kleinem alles verschoben)

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#218]

**Comment by erikradisch** [comment]
Was genau ist verschoben? Ich habe es mir gerade mal in 800x600 angeschaut, da ging die Standardoberfläche noch. Die Editoren gingen jedoch gar nicht. Da war die Hälfte nicht zu sehen. Ich habe mal eine skalierbare Lösung für den Dateneditor beim Imagepool in Kuchatest implementiert. (Imagepool --> Bild auswählen).
Bitte mal nachschauen, ob das das Problem damit behoben ist. Ansonsten am Besten Screenshots machen.

**Comment by erikradisch** [comment]
Ist so OK, es wäre nur wünschenswert, es zukünftig dynamischer zu gestallten, da Änderungen erst bei einem Neuaufruf der Editoren wirksam wären.
