### ISSUE TITLE
Tastaturbefehle

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#220]
Tastaturbefehle z.B. bei ImagePool Upload wären wünscheswert.

ab hier direkt mit Enter-Taste zum Speichern:

![1](https://user-images.githubusercontent.com/47562310/63010167-2bb9c200-be86-11e9-9cec-60d26a237b33.JPG)

![2](https://user-images.githubusercontent.com/47562310/63010169-2bb9c200-be86-11e9-886b-a60f5af187ff.JPG)

![3](https://user-images.githubusercontent.com/47562310/63010171-2bb9c200-be86-11e9-95b5-1470a8e15de3.JPG)

**Comment by erikradisch** [comment]
Ich könnte zwar grundsätzlich die Entertaste nehmen, finde es aber sinnvoller, eine Shortcut-Kombi zu benutzen. Ich habe das mal beim Imagepool bei Kuchatest implementiert.
Speichern kann man jetzt direkt mit Shift+Enter. 
Bitte überprüfen, ob das so grundätzlich ok ist, dann implementiere ich es überall.

**Comment by erikradisch** [comment]
Ist so angenommen. Wird geschlossen.
