### ISSUE TITLE
Wenn unter Painted Representation Eintrag als privat markiert wurde, sollte er nicht für die Öffentlichkeit (in View rechts) sichtbar sein

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#222]

**Comment by erikradisch** [comment]
Also, im Quelltext stand dazu folgender Kommentar und der Test auf die Rechte wurde auskommentiert:
		/**
		 * We cannot filter the accessLevel because that would create problems e.g. when choosing a cave for a depiction.
		 * What we can do is restricting the visibility of certain fields e.g. comments but this has to be done 
		 * when the UI is build on the client side!
		 */
Ich habe deswegen den entsprechenden Teil umgeschrieben, sodass jetzt alle eingeloggten User alles sehen und allen Gästen nur die Einträge zur Verfügung, die auch wirklich Accesslevel Guest haben. Ich hoffe, diese Lösung ist so OK?
Bitte mal in Kuchatest überprüfen, ob ich alle Einträge erwischt habe. Ich habe entsprechenden Code an 3 verscheidenen Stellen gefunden...
