### ISSUE TITLE
Wenn unter Painted Representations eine Iconography- oder Painted Elements-Kategorie ausgewählt wird, sollte die Oberkategorie mit ausgewählt sein

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#223]

**Comment by erikradisch** [comment]
Bitte mal in Kuchatest überprüfen, ob das so ok ist. 
Ursprünglich wollte ich eigentlich eine Version realisieren, wo die oberen Klassen nicht ausgewählt werden, sondern nur durch ein scharzes Viereck angezeigt wird, dass hier eine Unterklasse ausgewählt ist. 
Problem ist, dass wir dann immer noch das gleiche Problem bei der Suche haben. Sprich: möchte man alle Tiere haben und wählt die Oberkategorie "Animals", bekäme man auch wirklich nur die Fälle, wo diese Kategorie und nicht eine Unterkategorien gewählt wurde.
Übrigens: sollte diese Lösung so bleiben, müssen alle bisherigen Painted Representations geöffnet und gespeichert werden. ansonsten würden sie bei einer Standardsuche nicht mehr auftaufen (es wäre ja dann nur der Tiger ausgewählt, nicht aber die Klasse Tier)
Hier wäre es wirklich ratsam mittelfristig auf eine richtige Ontologie umzusteiegen und eine semantische Suche zu implementieren. 
Das wäre allerdings Arbeit für mehrere Monate.

**Comment by konczaknagel** [comment]
Danke, klappt!
