### ISSUE TITLE
Bibliography: nur Monografien-Titel kursiv

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#224]
Es sollten ausschließlich Monografien-Titel kursiv sein. Titel von Aufsätzen in Zeitschriften,  Sammel- oder Konferenzbänden sollen nicht kursiv angezeigt werden. Siehe Beispiel:
![grafik](https://user-images.githubusercontent.com/45167567/67212714-0a90c700-f41d-11e9-9b15-b0068239b998.png)

**Comment by konczaknagel** [comment]
Zusatz: Chinesische, japanische und koreanische Zeichen sollten generell nicht kursiv sein. Ist das möglich?

**Comment by erikradisch** [comment]
Kannst Du mal in Kis-Test schauen, ob das so passt? 
Zum Chinesischen und Koreanischen: in der augenblicklich implementierten Lösung sehe ich dazu keine Möglichkeit. Ich habe mal in Stackoverflow einen Post veröffentlicht. Mal sehen, ob jemanden anders was einfällt.

**Comment by konczaknagel** [comment]
Leider sind die Monografien-Titel jetzt nicht mehr fett.
![grafik](https://user-images.githubusercontent.com/45167567/67379758-9b84b100-f589-11e9-8bf0-69ae829aa34f.png)

**Comment by konczaknagel** [comment]
Entschuldigung, das hat mit dem Bild nicht so richtig geklappt:
![grafik](https://user-images.githubusercontent.com/45167567/67379863-c969f580-f589-11e9-8574-5e61d4c12bb7.png)

**Comment by erikradisch** [comment]
schau noch mal in kuchatest, jetzt sollte es klappen.

**Comment by konczaknagel** [comment]
Super, Danke!
