### ISSUE TITLE
Painted Representations: Current locations bitte nach Orten sortieren / Type forward möglich?

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#226]
Momentan ist die Liste nach Insitutionen / Museen sortiert. Z.B. Ashmoleum Museum, Oxford, England. Es wäre schön, wenn es folgendermaßen aussähe: Oxford, Ashmoleum Museum, England.

Danke!

**Comment by erikradisch** [comment]
Soll das dann auch so umgestellt werden?

**Comment by erikradisch** [comment]
guckst du mal in Kuchatest, ob das so OK ist?

**Comment by konczaknagel** [comment]
Danke! Die Sortierung ist jetzt perfekt!
Wäre auch noch ein type forward für die Suche möglich?

**Comment by erikradisch** [comment]
schau nochmal, sollte jetzt auch gehen.

**Comment by konczaknagel** [comment]
Funktioniert einwandfrei. Herzlichen Dank!
