### ISSUE TITLE
Image Pool - Allgemeine Vorschau, Vermerk anlegen?

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#228]
Wenn man sich alle im Image Pool befindlichen Bilder anzeigen lassen möchte, erscheinen nur 100, da das Laden aller Bilder viel zu lange dauern würde. Gibt es eine Möglichkeit, die echte Anzahl der Bilder anzeigen zu lassen, damit verständlich wird, dass wir mehr Bilder als nur 100 haben?

**Comment by erikradisch** [comment]
Ich habe es jetzt auf 50 reduziert und einen "add more results"-Button am Ende eingefügt, der es einem ermöglicht, Stück für Stück alle 20.000 Bilder zu laden.
