### ISSUE TITLE
Painted Representation: hochgeladene Bilder sind manchmal nicht sichtbar

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#229]
![image](https://user-images.githubusercontent.com/47562310/67572606-d4ae5400-f736-11e9-8ad5-fc75bcca5964.png)

**Comment by erikradisch** [comment]
Es scheint der ImageServer gerade allgemein nicht zu gehen. Ich habe Uwe gebeten, da mal nachzuschauen.

**Comment by erikradisch** [comment]
Probier das mal nach 5 Minuten wieder zu laden. Ich fürchte, er braucht ewig, um die Bilder anzeigen zu lassen.

**Comment by erikradisch** [comment]
dieses Problem sollte in Kuchatest jetzt nicht mehr bestehen, oder?
