### ISSUE TITLE
Painted Representations: View Bereich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#232]
Mit dem Doppelklick auf das Bild im Viewer Bereich öffnet sich das Bild, wäre es möglich das Gleiche aus dem Image Bereich einzurichten? siehe Screen:

![image](https://user-images.githubusercontent.com/47562310/67575189-50f76600-f73c-11e9-9ff5-b9c036131cf0.png)

**Comment by erikradisch** [comment]
ist jetzt drin. schau mal in kuchatest.
