### ISSUE TITLE
Image Pool: markieren des Titels nicht möglich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#233]
![image](https://user-images.githubusercontent.com/47562310/67619921-bcefd200-f801-11e9-8107-1c1e433d8e98.png)

**Comment by erikradisch** [comment]
gelöst. In Kucha-Test schon realisiert.

**Comment by erikradisch** [comment]
ich hab gerade festgestellt, dass ich das im falschen Branch behoben habe. Musst Dich also noch ein wenig gedulden, bis der WallTree drin ist, sorry.
