### ISSUE TITLE
Painted Representation: immer wieder Probleme bei Image hinzufügen 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#234]
an dieser Stelle stockt es oft. Manchmal geht werden die Bilder problemlos angezeigt, aber oft geht es an dieser Stelle nicht weiter. 
Das Problem mit "cancel" ist schon in der GitHub Liste aufgeführt.

![image](https://user-images.githubusercontent.com/47562310/67622504-04368c80-f81b-11e9-8aad-b9c3ad016a59.png)

**Comment by erikradisch** [comment]
sollte jetzt gehen, oder?
