### ISSUE TITLE
Painted Representation: das Bild von der Höhle lässt sich nicht als ganzes anschauen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#235]
vielleicht kann es so hinterlegen, so dass es sich z.B.verkleinern lässt

![image](https://user-images.githubusercontent.com/47562310/67698813-53abc280-f9ab-11e9-9846-14f90e3cd182.png)

**Comment by erikradisch** [comment]
schau mal in Kucha-test, ob das so OK ist.

**Comment by erikradisch** [comment]
sollte in der neuen Version von kuchatest jetzt auch ordentlich gehen, deswegen geschlossen.
