### ISSUE TITLE
Painted Representation: Elemente werden nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#236]
Painted Representation: Elemente werden nicht angezeigt
![image](https://user-images.githubusercontent.com/47562310/68071078-b53aab00-fd76-11e9-90af-e4cdfbf86c58.png)

**Comment by erikradisch** [comment]
Hast Du an dem Tag ein paar Bilder hochgeladen? Ich habe nämlich die Vermutung, dass der Image-Server ab einer bestimmten Zahl an Uploads abschmiert.

**Comment by OKienzler** [comment]
Guten Morgen Erik,

Nee an dem Tag habe ich nichts hochgeladen, es war von vorne rein so, deshalb konnte ich mit unserer Database am Samstag gar nicht arbeiten.

Grüße 
Olga

Von meinem iPhone gesendet

**Comment by erikradisch** [comment]
Das dürfte auf Kuchatest jetzt nicht mehr vorkommen. Bitte mal dort überprüfen.
