### ISSUE TITLE
Painted Representation: LÖSCHEN

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#237]
Beiträge mit dem Namen "LÖSCHEN" sollen gelöscht werden. Diese sind entstanden als das Programm sich mehrmals aufgehänt hatte und beim erneuten Starten diese Beiträge nicht sichtbar waren, so dass ich einen neuen Beitrag angelegen musste. Später wurden alle Beträge sichtbar. Das Problem ist, dass wir bereits hochgeladene Beiträge in Painted Representation oder auch hochgeladene Bilder in ImagePool (siehe Issue vom 12.02.2019) beim Bedarf nicht mehr aus der Database entfernt werden können.
![image](https://user-images.githubusercontent.com/47562310/68119515-345cea00-ff03-11e9-9944-ba243cc90988.png)

**Comment by OKienzler** [comment]
diese Issue #128 (Delete Images that are named as "LÖSCHEN") angelgt im Nov. 2018 von Ines,

**Comment by erikradisch** [comment]
Ich habe die zu löschenden Einträge entfernt.

**Comment by erikradisch** [comment]
Ich habe sie doch mal wieder hinzugefügt. Einfach Löschen geht nicht. Es müssten auch die Verknüpfungen entfernt werden, sonst nutzt das System beim nächsten Bild die freie ID. Damit hätte das neue Bild die potentiellen Verknüpfungen das alten Bildes. Das müssen wir vermeiden...

**Comment by erikradisch** [comment]
gelöst, es gibt jetzt ein Löschbutton in den Image- und Depiction-Editor. Bitte bei den Images vorsichtig damit umgehen, da in der augenblicklichen Version die Images nicht gelöscht werden...

![grafik](https://user-images.githubusercontent.com/34335811/72440352-f6086480-37a8-11ea-8389-984c6265e1c7.png)
