### ISSUE TITLE
Painted Representaion: Eitrag doppelt bitte löschen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#238]
unter: current location 
"not available anymore" ist doppelt, bitte eins davon löschen, Dankeschön.
![image](https://user-images.githubusercontent.com/47562310/68596792-1b70ad80-049c-11ea-8ffb-55eb4bd0dfeb.png)

**Comment by konczaknagel** [comment]
Bitte bei der Gelegenheit "not available anymore" ändern in "not preserved"
Danke schön!

**Comment by erikradisch** [comment]
sollte erledigt sein.
