### ISSUE TITLE
LÖSCHEN in Painted Representations / Pictorial Elements

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#243]
Bitte in der Liste der Pictorial Elements einmal "Inflated Animal Skin" löschen. Es erscheint leider zweimal in der Liste und ist richtig unter miscellanea. Das andere muss weg.

![grafik](https://user-images.githubusercontent.com/45167567/72070971-0e7d0880-32eb-11ea-8273-58eb432d563e.png)

**Comment by konczaknagel** [comment]
Hier die richtige Grafik dazu:
![grafik](https://user-images.githubusercontent.com/45167567/72071157-76335380-32eb-11ea-9434-0f6671817477.png)

**Comment by erikradisch** [comment]
erledigt
