### ISSUE TITLE
Caves -- die einzelnen Höhlen lassen sich nicht mehr durch Anklicken öffnen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#245]

**Comment by konczaknagel** [comment]
in kuchatest ist das Öffnen der Höhlen durch Anklicken aber weiterhin möglich

**Comment by erikradisch** [comment]
in der Kachel für die Caves? Bei mir geht's...

**Comment by konczaknagel** [comment]
Entschuldigung! Hab jetzt alles noch einmal neu gestartet und jetzt geht's auch wieder bei mir. Danke!
