### ISSUE TITLE
Bibliography: Anzeige der englische Übersetzungen der Titel ändern

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#246]
es ging in der Bibliographie in der Datenbank um die englischen Übersetzungen der (in diesem Fall deutschen) Titel. Ein Beispiel ist im Anhang.

- englische Übersetzungen der Titel von Artikel in Publikationen (Incollection) werden überhaupt nicht angezeigt, sollten aber in eckigen Klammern hinter dem Titel stehen;
- englische Übersetzungen von Publikationstiteln sollen ebenfalls in eckigen Klammern erscheinen und NICHT kursiv sein

**Comment by erikradisch** [comment]
ging das Anhängen schief? Ich sehe hier gar keinen.

**Comment by konczaknagel** [comment]
![grafik](https://user-images.githubusercontent.com/45167567/77756936-81676700-7030-11ea-9ced-46f1fc0d7adb.png)

**Comment by konczaknagel** [comment]
Die englische Übersetzung wird jetzt angezeigt (rot unterstrichen), sie sollte nur in eckigen Klammern stehen.

**Comment by erikradisch** [comment]
hast Du mal ein Beispiel für den zweiten Punkt?

**Comment by erikradisch** [comment]
Astrid hat ein Beispiel gegeben und überprüft, deswegen schließe ich dieses Issue jetzt.
