### ISSUE TITLE
Painted Representations: zu "Acquired by expedition" bitte hinzufügen "One of the German expeditions (1902-1914)"

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#249]

**Comment by erikradisch** [comment]
Ist eingefügt, jetzt allerdings ganz unten. Ist das ein Problem?

**Comment by konczaknagel** [comment]
Kein Problem, dass es ganz unten ist.

Bitte noch bei Leader einschreiben: Grünwedel (1st and 3rd expedition) / Le Coq (2nd and 4th expedition)

**Comment by erikradisch** [comment]
ist ein Bischen lang so, oder? Schau mal bitte.

**Comment by konczaknagel** [comment]
Tut mir leid, Deine Eintragung wird bei mir in kuchatest nicht angezeigt. Ich sehe nur: "Leader: "
Du kannst expedition auch mit exp. abkürzen, wenn es zu lang ist. Sollte allen klar sein, was gemeint ist.

**Comment by erikradisch** [comment]
ich hab das direkt in Kucha geändert. Kannst Du da mal schauen?

**Comment by konczaknagel** [comment]
Prima! Der Eintrag ist jetzt sogar noch kürzer als der zur dritten Exp.
