### ISSUE TITLE
Anzahl gefilterter Bilder in Image pool

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#250]
Die Anzahl der gefilterten Bilder in Image pool ist nicht mehr sichtbar. Diese Funktion wird benötigt.

![grafik](https://user-images.githubusercontent.com/47562310/77160661-1b1a9b80-6aa8-11ea-8513-94ac080da0fa.png)

Dankeschön

**Comment by erikradisch** [comment]
schau mal in Kuchatet. Ist das so OK?

**Comment by OKienzler** [comment]
Sehr schön, jap so meinte ich auch, Dankeschön!

Das einzige ist z.B. in dem Fall s.u. werden die ersten 100 von insgesamt
30 gezeigt, ist vielleicht für manche verwirrend? Würde es gehen 30/30 in
so einem Fall anzeigen zu lassen? Wenn es zu viel Aufwand es so zu ändern,
dann lasse es so :) denn diese Ansicht bleibt eh nur für uns intern.

[image: Kucha_2.JPG]



Am Fr., 20. März 2020 um 22:34 Uhr schrieb erikradisch <
notifications@github.com>:

**Comment by erikradisch** [comment]
so?

**Comment by OKienzler** [comment]
sehr schön, sieht gut aus! Dankeschön!!!

Am Mi., 25. März 2020 um 11:27 Uhr schrieb erikradisch <
notifications@github.com>:
