### ISSUE TITLE
Tab-Taste beim Hochladen der Bilder in Image pool 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#251]
Arbeiten mit der Tab -Taste in der Image-pool-Bilder-Maske wird direkt nach dem Öffnen des Fensters nach dem Hochladen eines Bildes benötigt. Der Kursor soll bitte gleich im Feld des Dateinamens stehen, so dass mit der Tab-Taste direkt in das nächte Feld gegangen werden kann. So was es schon mal, es war sehr praktisch und hat die Arbeit erleichtert.

![grafik](https://user-images.githubusercontent.com/47562310/77161455-fde6cc80-6aa9-11ea-8956-f82762dcd0d5.png)

Dankeschön

**Comment by erikradisch** [comment]
schau mal in Kuchatest. Geht es jetzt?

**Comment by OKienzler** [comment]
super, genau so!!! Dankeschön Erik!

Jetzt wenn Du schon dabei bist noch eine Frage. Um den Vorgang zu schließen
drücke ich auf Shift Taste + Enter und dann kommt noch ein Fenster mit der
Speicherfrage. Könntest Du es so einstellen, dass "Yes" oder von mir aus
"No" gleich markiert ist und man nur noch ggf. auf die "Pfeiltaste" drücken
muss und dann auf "Enter" um den Vorgang abzuschließen. Mit der Tastatur zu
arbeiten ist einfacher und entlastender als mit der Maus.

[image: Kucha.JPG]


Am Di., 24. März 2020 um 22:05 Uhr schrieb erikradisch <
notifications@github.com>:

**Comment by erikradisch** [comment]
so?

**Comment by OKienzler** [comment]
Du bist super! Genauso, Dankeschön!


Am Mi., 25. März 2020 um 10:50 Uhr schrieb erikradisch <
notifications@github.com>:
