### ISSUE TITLE
Suche nach Cave No. in Cave

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#252]
Die Suche sollte auch oder nur nach Cave No. sein z.B. Kiz 110
im Moment geht es nur nach historischen Namen z.B. Treppenhöhle 
![grafik](https://user-images.githubusercontent.com/47562310/77553173-c1094400-6eb4-11ea-82f1-2aea0536ae14.png)

**Comment by erikradisch** [comment]
sollte jetzt gehen.
