### ISSUE TITLE
Image Pool Spreichern Pfeiltaste

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#253]
Von "Yes" auf "No" mit der Pfeiltaste geht nicht, sodern nur mit der Maus

![grafik](https://user-images.githubusercontent.com/47562310/77554608-961fef80-6eb6-11ea-8d4c-616ed68b246d.png)

**Comment by erikradisch** [comment]
Sollte jetzt gehen.
P.S. Wenn Du so weiter machst, ist der gesamte Uploadprozess automatisiert und wir brauchen keine Olga mehr. ;-P

**Comment by OKienzler** [comment]
Liebe Erik,

mit der Pfeiltasten von "Yes" auf "No" geht noch nicht. Weder in Kuchatest
noch in der Arbeitsversion.

[image: grafik.png]

Und lieben Dank für deine Erledigung anderer GitHub Einträge.

LG Olga

PS.: zum Glück habe ich noch andere Aufgaben außer Bilder hochladen :-P

Am Mi., 25. März 2020 um 21:15 Uhr schrieb erikradisch <
notifications@github.com>:

**Comment by OKienzler** [comment]
also jetzt geht es zwischen "Yes" und No" zu springen nur nicht mit den Pfeiltasten, sondern mit Tab...vielleicht ging es mit Tab auch schon zuvor?
