### ISSUE TITLE
Ornamentation Editor (Fehler)2

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#257]
KuchaDB:
- [x] Neue Ornamentik Karteikarten werden nicht gespeichert (technisch gesehen wird die Karteikarte gespeichert, aber die Felder bleiben alle lehr).

- [ ] die mit "delete" bezeichneten Eingabe der Baumstruktur in KuchaDB löschen (Decoration & Ornaments / Phytomorphic Motifs / Running Scroll / delete).

- [x] es ist möglich die Bilder nur für eine bereits existierende Ornamentik Karteikarte auszuwählen.

Kuchatest:
- [x] Neue Ornamentik Karteikarten werden mit Explorer nicht gespeichert.

- [x] es ist möglich die Bilder nur für eine bereits existierende Ornamentik Karteikarte auszuwählen.

- [x] einigen Bilder im "Image Pool" werden nicht in Kuchatest visualisiert.

- [x] es ist nicht möglich neuen Bilder im "Image Pool" hochladen (Kuchatest).

- [x] es ist nicht möglich die bereits hochgeladenen Bilder in "image Pool" zu editieren (Kuchatest).

**Comment by LucaDeF** [comment]
der speichern Fehler gilt auch für Kuchatest!!

**Comment by LucaDeF** [comment]
die Karteikarten werden immernoch nicht gespeichert. Ich habe es versucht die Cache zu löschen. Ausserdem habe ich es mit verschiedenen Browsers versucht und zwar mit Explorer, Chrome und Firefox (Explorer zeigt direkt einen Fehler Fenster, während, mit Chrome und Firefox, es scheint erst zu funktionieren: das Icon der neuen Karteikarte erscheint; aber wenn man die Seite aktualisiert, dann verschwindet das Icon). Es besteht die möglichkeit dass es eigentlich gespeichert wird, aber die Karteikarten einfach nicht zu visualisieren sind (wenn ich versuche in die Baumstruktur die als Test gespeicherten Ornamente auszuwählen, kriege ich die Nachricht, dass die Eingabe schon gewählt wurde).

**Comment by LucaDeF** [comment]
die Karteikarte werden nicht gespiechert wenn man mit Explorer arbeitet. In Gegenteil werden sie gespeichert, wenn man mit Chrome oder Firefox arbeitet.

**Comment by LucaDeF** [comment]
die Bilder werden nicht ausgewählt wenn man mit Firefox arbeitet (Explorer funktioniert überhaupt nicht). D.h. es ist möglich die Bilder für eine Ornamentik Karteikerte auszuwählen, nur wenn man mit Chrome arbeitet.

**Comment by LucaDeF** [comment]
einigen Bilder im "Image Pool" werden nicht in Kuchatest visualisiert. Ich vermute, die sind diejenigen, die ich ursprünglich direkt im KuchaDB hochgeladen hatte.
Es ist auch nicht möglich neuen Bilder im "Image Pool" überhaupt zu hochladen.

**Comment by LucaDeF** [comment]
Ich habe es neulich bemerkt, dass man Bildern auswählen kann, nur wenn die an eine bereits existierende Ornamentik Karteikarte zu verknüpfen sind.

**Comment by erikradisch** [comment]
könntest Du mir das eventuell mal im Videochat vorführen? kann mir da nichts drunter vorstellen.

**Comment by erikradisch** [comment]
Achso. Und zum delete: Das kannst Du doch jetzt selbst! :-)

**Comment by LucaDeF** [comment]
> könntest Du mir das eventuell mal im Videochat vorführen? kann mir da nichts drunter vorstellen.

Natürlich!! Sollen wir gleich Videochatten oder lieber Nachmittags?

**Comment by erikradisch** [comment]
Nachmittags. Bin Grad unterwegs.

Am 24. Juli 2020 10:31:56 MESZ schrieb LucaDeF <notifications@github.com>:
>> könntest Du mir das eventuell mal im Videochat vorführen? kann mir da
>nichts drunter vorstellen.>
>>
>Natürlich!! Sollen wir gleich Videochatten oder lieber Nachmittags?>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/saw-leipzig/kucha/issues/257#issuecomment-663409416

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by LucaDeF** [comment]
> Achso. Und zum delete: Das kannst Du doch jetzt selbst! :-)

Ich denke dafür brauche ich mal eine Vorführung im Videochat!! Ich kann eine Karteikarte löschen, aber eine Eintrag in der Baumstruktur zu löschen kann ich noch nicht!!

**Comment by LucaDeF** [comment]
> Nachmittags. Bin Grad unterwegs. Am 24. Juli 2020 10:31:56 MESZ schrieb LucaDeF <notifications@github.com>:
> […](#)
> > könntest Du mir das eventuell mal im Videochat vorführen? kann mir da nichts drunter vorstellen.> > Natürlich!! Sollen wir gleich Videochatten oder lieber Nachmittags?> > -- > You are receiving this because you commented.> Reply to this email directly or view it on GitHub:> [#257 (comment)](https://github.com/saw-leipzig/kucha/issues/257#issuecomment-663409416)
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

Sehr gut!! Ist es ok für Dich gegen 16:00 Uhr??

**Comment by erikradisch** [comment]
Bin gerade raus. kann das geschlossen werden?

**Comment by LucaDeF** [comment]
Soviel ich sehe, nur diesem Punkt bleibt noch offen:

- die mit "delete" bezeichneten Eingabe der Baumstruktur in KuchaDB löschen (Decoration & Ornaments / Phytomorphic Motifs / Running Scroll / delete).
