### ISSUE TITLE
Ornamentation Suchfunktion (Fehler)2

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#258]
- [x] "Add more Results" Button scheint nicht zu funktionieren.

- [x] Die Suche nach dem Kode gibt kein Ergebnis wieder.

**Comment by LucaDeF** [comment]
nachdem ich die Suchfunktion nutze, kriege ich eine gewisse Zahl von Treffer und, darünter, einen Button, der "Add more Results" heißt. Wenn ich auf dem klicke, passiert es aber gar nichts!!

**Comment by erikradisch** [comment]
ich bin mir noch nicht 100% sicher, ob die Filterung nach Kode in Kuchatest klappt oder nicht. Teste mal bitte

**Comment by LucaDeF** [comment]
Nein, in Kuchatest funktioniert nicht, sowie in KuchaDB auch nicht!! Soviel ich gesehen habe, das einziges Filter der tatsächlich funktioniert ist den mit der Baumstruktur von "Iconography".

**Comment by LucaDeF** [comment]
Ich habe es bemerkt, dass in Kuchatest, wenn man nach *Kiz* sucht, kriegt man auch ein paar Ergebnisse. Man sollte aber alle Ornamentik Karteikarte visualisieren, da alle haben "Kiz" in der Kode.

**Comment by erikradisch** [comment]
Benutzt du *?

Am 23. Juli 2020 16:28:05 MESZ schrieb LucaDeF <notifications@github.com>:
>Ich habe es bemerkt, dass in Kuchatest, wenn man nach *Kiz* sucht,
>kriegt man auch ein paar Ergebnisse. Man sollte aber alle Ornamentik
>Karteikarte visualisieren, da alle haben "Kiz" in der Kode.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/saw-leipzig/kucha/issues/258#issuecomment-663039025

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by LucaDeF** [comment]
Ja: der Kiz in kursive in der letzte Nachricht sollte eigentlich * Kiz * gewesen sein!!

**Comment by erikradisch** [comment]
jetzt sollte es gehen. Denk daran, dass caves und district in Kuchatest erst klappen können, wenn Du auch dort einen verknüpften Eintrag in Painted Representation erstellt hast.

**Comment by LucaDeF** [comment]
Die Suchfunktion nach dem Kode scheint jetzt in Kuchatest zu funktionieren. Genauso funktioniert das Button "add more results" in Kuchatest. Beide Funktionen klappen aber in KuchaDB noch nicht!

**Comment by erikradisch** [comment]
Na, weil wir es ja erst in kuchatest testen, um nichts in Kucha zu ruinieren. Deswegen auch kuchatest. :-) ich warte noch auf das ok Von Olga, dann geht es online.

Am 24. Juli 2020 10:23:12 MESZ schrieb LucaDeF <notifications@github.com>:
>Die Suchfunktion nach dem Kode scheint jetzt in Kuchatest zu
>funktionieren. Genauso funktioniert das Button "add more results" in
>Kuchatest. Beide Funktionen klappen aber in KuchaDB noch nicht!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/saw-leipzig/kucha/issues/258#issuecomment-663405999

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by LucaDeF** [comment]
So hatte ich auch nicht gemeint!! ...ich wusste nur nicht in welche Stufe die Prozedur sich befand!!

**Comment by erikradisch** [comment]
hast Du hier jetzt mal geschaut?

**Comment by LucaDeF** [comment]
Es funktioniert jetzt in KuchDB auch!!!
