### ISSUE TITLE
Suche in Caves funktioniert teilweise nicht

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#259]
- Suche nach historischen Namen (search historical names) nicht möglich (passiert nichts)
- Suche nach "sites" nicht möglich (Lupe bleibt rot)

**Comment by erikradisch** [comment]
Kann es sein, dass Du bei der Suche nach historischen Namen den Asterix vergessen hast? Bei mir geht das jedenfalls...

**Comment by konczaknagel** [comment]
Es lag daran, dass der historische Name nicht angegeben war. Danke!
