### ISSUE TITLE
Description of Painted Representations

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#26]
* [x]  bei „Iconography“ bitte Mehrfachauswahl möglich machen
* [x]  bitte entfernen „add inscription / dating / description / remarks“; es lässt sich viel besser sehen, dass ein Feld noch nicht ausgefüllt ist, wenn es leer ist; zudem ist es z.B. bei copy und past hinderlich, da es zusammen mit dem eingefügten Text stehen bleibt
* [x]  „discription“ wird zwar nach Eingabe gespeichert, beim Neustart des InfoSys ist es aber nicht mehr vorhanden
* [x]  „other suggested identifications“ wird nach Eingabe nicht gespeichert
* [x]  „mode of representation“ fehlt
* [x]  bitte noch link zur Publikation von „Painted Representation“ hinzufügen (= #24)
 * [x]  primary literature
 * [x]  secundary literature
* [x]  bei „Iconography Selector“ ist die Markierung zu schwach (kaum sichtbar)

**Comment by konczaknagel** [comment]
- hinter width und height bitte "(cm)" setzen

**Comment by alingnau** [comment]
siehe #24
