### ISSUE TITLE
current location in image pool lässt sich nicht speichern

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#260]
current location in image pool lässt sich raussuchen, wird aber nicht gespeichert.

![grafik](https://user-images.githubusercontent.com/47562310/86446201-eb6c6800-bd13-11ea-90d1-14121413c8db.png)

**Comment by erikradisch** [comment]
Mal eine dumme Nachfrage hierzu: Habe ich "Current Location" hier eingepflegt? Das gab es noch nicht immer, oder? Es existiert noch gar nicht in der Datenbank. Das kann ich mir nur mit dem Hin und Her erklären, dass wir mit der Current Location bei Painted Representation hatten. Da hatten wir ja mal eine zeitlang überlegt, die Current Location über die Bilder einzufügen, wovon wir dann ja aber wieder abgekommen sind, oder? Wenn dem so ist: Brauchen wir das hier an der Stelle?

**Comment by erikradisch** [comment]
sollte jetzt gehen, bitte in Kuchatest überprüfen.

**Comment by konczaknagel** [comment]
in Kucha-Test funktioniert es jetzt; können wir dies schließen?

**Comment by OKienzler** [comment]
Ich würde es erst dann schließen, wenn es auch in der Kucha-Arbeitsversion funktioniert (das habe ich Erik schon so geschrieben)

Von meinem iPhone gesendet
