### ISSUE TITLE
Problem mit der Bilder Auswahlmöglichkeit in Painted Representation Editor

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#262]
Während ich mit dem "Painted Representation Editor" arbeite, kann ich nicht mehr viele Bilder gleichzeitig auszuwählen um sie zu verknüpfen. Ich muss jedes Mal maximal drei oder vier Bilder auswählen, sie verknüpfen und dann wieder die Prozedur von "add image"/"search image" anfangen. Das verlangsamt deutlich die Arbeit der Verknüpfung der Bildern.

**Comment by erikradisch** [comment]
zumindest in Kuchatest habe ich gerade über 20 bilder auf einmal ausgewählt. Allerdings habe ich auch festgestellt, dass man dann eine Weile (bei mir etwa 5 sek) warten muss, bis der Speicherprozess von Painted Representation (nicht der der Verknüpfung der Bilder) abgeschlossen war. Kannst Du mal in Kuchatest schauen, ob es da klappt?

**Comment by LucaDeF** [comment]
In Kuchatest scheint es gut zu klappen: ich habe auch gerade über 20 Bildern gleichzeitig Problemlos ausgewählte.
Der Speicherprozess von Painted Representation dauert bei mir auch eine Weile, aber so Schlimm fand ich es nicht!!

**Comment by erikradisch** [comment]
Gut, dann warten wir mal, was Olga morgen zu den Änderungen in der neuen Kuchatest-Version sagt und schauen dann, ob sich die Probleme von selbst lösen, wenn ich die neue Version rüber schiebe.

**Comment by erikradisch** [comment]
hat sich das jetzt erledigt?

**Comment by LucaDeF** [comment]
Ich musste mehrmals es testen und am Ende habe ich folgendes verstanden: das Problem kommt nicht mehr vor, wenn man mit Firefox arbeitet, aber das Problem ist mit Chrome noch da!! Ich musste jedenfalls die Cache von beiden Browsers komplett löschen (ich teste Explorer nicht mehr)!! Ich habe jetzt keine Ahnung, ob eine so große Unterschied zwischen Browsers normal ist und ob man diesen Issue wirklich schließen kann!!

**Comment by erikradisch** [comment]
Da das hier ja nur für die Bearbeitung intern gedacht ist, würde ich sagen: arbeite halt mit Firefox. :-)
