### ISSUE TITLE
Infos der Bilddatei werden nicht gespeichert

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#263]
Infos der Bilddatei werden nicht gespeichert:

Nach dem Hochladen einer Bilddatei werden die Infos wie Cave no., Datum, etc. eingetragen. Zuerst mal weden diese Infos gespeichert (s. KuchaSW_Fehler_1). Nach der Schließung der Kucha SW und erneutem Einloggen sind die Informationen nicht mehr vorhanden, aber dies betrifft nicht alle hochgeladene Dateien sondernnur 3 mit dem Kreuz (s. KuchaSW_Fehler_2). Dieser Fehler trat auch letzte Woche vor.
<img width="743" alt="KuchaSW_Fehler_1" src="https://user-images.githubusercontent.com/47562310/87304850-c34fe680-c515-11ea-9f75-01e4314d865c.PNG">
<img width="885" alt="KuchaSW_Fehler_2" src="https://user-images.githubusercontent.com/47562310/87304859-c6e36d80-c515-11ea-9ef2-97d7c2289901.PNG">

**Comment by erikradisch** [comment]
So. Habe mal eine neue Version in Kuchatest hochgeladen. Das Problem dürfte gewesen sein, dass vor dem Speichern übrprüft wurde, ob alle wichtigen Daten vorhanden und/oder korrekt sind (wie z.B. Kurznamen). Wenn dem nicht so war, brach der Speicherprozess ohne nachricht ab...
Hab jetzt Benachrichtigungen eingefügt. Inklusive einer Nachricht, wenn der Speicherprozess erfolgreich war.
Bitte überprüfen, ob es so alles funktioniert.

**Comment by OKienzler** [comment]
Schön 👍 Dankeschön, werde es dann am Mittwoch ausprobieren

Von meinem iPhone gesendet

**Comment by OKienzler** [comment]
Infos wurden im eben hochgeladenem Bild nicht gespeichert:
![grafik](https://user-images.githubusercontent.com/47562310/91548619-ec8dd000-e925-11ea-8e00-fc847961eadb.png)

**Comment by erikradisch** [comment]
hast Du nur einmal mit Shift-Enter gespeichert oder mehrmals, als Du in jedem Eintrag raus bist?

**Comment by erikradisch** [comment]
Also, was ich gesehen habe ist, dass Du Shift+Enter drückst und dann das Speichern 5 mal ausgeführt wird. Das ganze hängt wohl mit dem Zusammen, dass Du über Enter speicherst. Falls Du dich erinnerst, war das ein Zeit lang ein Problem, an der ich einige Zeit lang rumgedoktort habe. Deswegen war da noch eine alte Lösung drin, die eigentlich nie ging. Jetzt scheint sie aber auch zu funktionieren, wodurch das Speichern mehrmals ausgelöst wird. Trotzdem erschließt sich mir jedoch nicht, warum bei Dir bei verschiedenen Speichervorgängen verschiedene Inhalte übermittelt worden. Eine Theorie ist, dass Du mehr als einmal gespeichert hast und die die Doppelten Speicher-Aufträge gegenseitig überholt hatten. Sicher bin ich mir da aber nicht. Ich lade heute Abend eine neue Version hoch. Schau am Montag mal, ob es eventuell nun geht.

**Comment by erikradisch** [comment]
denke daran, den Cache zu leeren, bei mir ging es erst dann wieder

**Comment by OKienzler** [comment]
im Moment habe ich nichts zum Hochladen, vielleicht nächste Woche und melde mich wenn es wieder Probleme gibt. Bei den am Montag (31.08.2020) hochgeladenen Bildern gab es keine Probleme.

**Comment by erikradisch** [comment]
Besteht das Problem noch?

**Comment by OKienzler** [comment]
im Moment läuft es gut
