### ISSUE TITLE
Ornamentation Editor (Anpassung)2

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#264]
Jetzt dass wir gesehen haben dass die Verbindung mit der Painted Representation gut läuft, zwei Felder sind nicht mehr gebraucht:

- [x] Feld "Motif" (drop down menu) löschen bzw. ausblenden

- [x] Feld "Add Cave" löschen bzw. ausblenden

**Comment by erikradisch** [comment]
segne es mal in Kuchatest ab und schließ dieses Issue dann bitte.

**Comment by LucaDeF** [comment]
ich segne es ab!!
