### ISSUE TITLE
Bilder für Ikonen Anpassung (Ornamentik)

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#265]
einigen Bildern die ich speziell für die Ikonen zugeschnitten habe passen sich nicht an die Ikone an! 
![2020 07 30](https://user-images.githubusercontent.com/45200800/88909077-f820a500-d25a-11ea-9ea3-d9310bd85f4c.jpg)

**Comment by erikradisch** [comment]
schau mal in Kuchatest

**Comment by LucaDeF** [comment]
soviel ich sehen kann, gibt es dasselbe Problem in Kuchatest auch!

**Comment by erikradisch** [comment]
hast Du mal ein beispiel in Kuchatest jetzt? Bei mir sah alles dufte aus.

**Comment by LucaDeF** [comment]
Gestern sah es mehr oder weniger wie in KuchaDB aus, aber heute sieht es viel besser aus. Keine Ahnung was ist passiert, ich habe keine Einstellung geändert. Die Bildern sind aber sowieso nicht wirklich zentriert und in manchen Fällen fällt der Text von der Ikone heraus.
![2020 07 31](https://user-images.githubusercontent.com/45200800/89026349-d8f04900-d328-11ea-8afe-dd8b571563dc.jpg)
.

**Comment by LucaDeF** [comment]
P.S. vielen Bildern visualisiert man nicht, einfach weil sie in Kuchatest nicht hochgeladen sind!!

**Comment by erikradisch** [comment]
ich kann auch die Höhe der Bilder noch mehr begrenzen, dann wird Kiz42.1 aber sehr klein. Die Entscheidung überlasse ich Dir. :-)

**Comment by LucaDeF** [comment]
Es ist wahrscheinlich besser die Bilder etwa kleiner zu haben, statt den Text außerhalb der Ikone zu lassen!!

**Comment by erikradisch** [comment]
Done. Teste es mal in Kuchatest.

**Comment by LucaDeF** [comment]
es sieht gut aus!!!
