### ISSUE TITLE
Bilder erst einmal nicht mehr sichtbar nach Auswahl des Masterbildes, nach erneutem Laden der DB wieder sichtbar

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#266]
Sobald Master-Bild-Auswahl aktiviert wurde, werden keine Bilder mehr angezeigt:
![grafik](https://user-images.githubusercontent.com/45167567/89772666-b5848580-db02-11ea-83ac-471e792d7c0d.png)

Auch gesetztes Master-Bild erst nach erneutem Laden der Datenbank korrekt angezeigt (vorher sah man noch das alte, automatisch ausgewählte Bild)

**Comment by erikradisch** [comment]
schau mal in Kuchatest, ob das jetzt ordentlich klappt.

**Comment by konczaknagel** [comment]
Selbst nach längerem Warten sieht es bei mir so aus:
![grafik](https://user-images.githubusercontent.com/45167567/90030032-da702880-dcbb-11ea-8637-1844bf7c7168.png)

**Comment by erikradisch** [comment]
Du hast in Kuchatest geschaut? Wenn ja, leere mal bitte deinen Cache. Bei mir dauert es zwar einen Augenblick, da er die Bilder neu laden muss (5 sek), aber es kommt.

**Comment by konczaknagel** [comment]
Hab's mit derselben Höhle ausprobiert und es ging wieder nicht. Mit einer anderen Höhle ist aber alles problemlos gelaufen.
