### ISSUE TITLE
Bild lässt sich nicht in image pool hochladen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#268]
Bitte prüfen, warum sich das Bild Kizil110_03_III8376c_B1087_GROSS in Kucha-Arbeitsversion und in Kucha-Test nicht hochladen lässt (ich habe bei Versuche gelöscht und warte auf deine Rückmeldung)
![grafik](https://user-images.githubusercontent.com/47562310/91299669-4b2a4100-e7a2-11ea-95dc-4c77a904082c.png)

**Comment by erikradisch** [comment]
In beiden Fällen handelt es sich bei mir (zumindest in der Cloud?) um kaputte Images. Diese können dann natürlich auch nicht angezeigt werden. Entsprechend schließe ich das hier wieder.

**Comment by erikradisch** [comment]
Dort, wo man es schließt, kann man es auch wieder öffnen (unter dem Kommentarfeld).
Also, ich habe mir die Bilder noch einmal angeschaut. Es sind in der Tat korrupte JPGs. Der Grund, warum sie korrupt sind liegt daran, dass es in Wahrheit TIFs sind. ;-) Einfach umbenennen und noch einmal versuchen.
Entsprechend bleibt das aber von mir aus zu.

**Comment by OKienzler** [comment]
das betrifft auch zum Beispiel dieses bild, Simsim_ZweiteHoehleKleineSchlucht_Ceiling_III9096a

![grafik](https://user-images.githubusercontent.com/47562310/91307336-1b813600-e7ae-11ea-86e5-f88c9816e38f.png)

**Comment by erikradisch** [comment]
Hat bei mir ohne Probleme geklappt. Arbeitest Du im Büro?

![Bildschirmfoto von 2020-08-26 15-16-22](https://user-images.githubusercontent.com/34335811/91308217-3f914700-e7af-11ea-8a45-d8163360e3e3.png)

**Comment by OKienzler** [comment]
Ja bin im Büro

**Comment by OKienzler** [comment]
Dann liegt es an schlechter Internetverbindung der Uni?

**Comment by erikradisch** [comment]
Bist Du über Kabel oder WLan drin?

**Comment by erikradisch** [comment]
Ich schätze, dass Du im WLan bist. Übrigens muss ein reingestecktes Kabel auch nichts heißen, wenn die Authentifizierung schief ging. Wichtig ist, welches Symbol unten angezeigt wird.

**Comment by erikradisch** [comment]
Wer weiß, eventuell war es auch was anderes. Ev. hat Uwe gerade den Canteloupe neugestartet, als Du es versucht hast.
