### ISSUE TITLE
Doppelte Einträge in iconography Selector

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#269]
Elephant war nicht zu finden, deshalb hat Fang "elephant" eingefügt, nun sind 3 x Elephant. Bitte löschen und prüfen wo das problem lag. Dankeschön (Fang hat keinen Zugangn zu GitHub deshalb tue ich das für sie)

![grafik](https://user-images.githubusercontent.com/47562310/91300479-a01a8700-e7a3-11ea-8a09-12188a69b668.png)

**Comment by erikradisch** [comment]
Einer der Elephanten scheint bereits älter zu sein. Ebenso die Dopplungen, zumindest habe ich dazu nichts mehr im Log. Ich habe es in Kucha und Kuchatest probiert, funktionierte ohne Probleme. Bitte unbedingt mir SOFORT mitteilen, wenn so etwas auftritt. Leider sind nämlich alle drei Elephanten verwendet worden, weshalb ich nun aufräumen muss...
Wegen fehlender Nachvollziehbarkeit der Fehlerursache schließe ich dieses Issue bis auf weiteres.
P.S. Fang braucht ganz dringend ihren eigenen Zugang.
