### ISSUE TITLE
Das Bild wird in image nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#270]
Das Bild (Kizil110_14_IB8376g_B1083_GROSS) wird in image pool in der Kucha-Arbeits-Version nicht angezeigt, eventuell das gleiche problem wie bei  Kizil110_03_III8376c_B1087_GROSS ????

![grafik](https://user-images.githubusercontent.com/47562310/91300698-ff789700-e7a3-11ea-889f-e50a6061caa0.png)

**Comment by erikradisch** [comment]
In beiden Fällen handelt es sich bei mir (zumindest in der Cloud?) um kaputte Images. Diese können dann natürlich auch nicht angezeigt werden. Entsprechend schließe ich das hier wieder.

**Comment by OKienzler** [comment]
auf NAS sind es keine kaputte Bilder und werden normal angezeigt. Der Upload in unsere Kuch Db erfolgt von NAS und nicht aus der Cloud
