### ISSUE TITLE
Meldung, wenn ein Bild in image pool bereits existiert

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#271]
Die Meldung ob ein Bild bereits in image pool hochgeladen wurde erscheint willkürlich, mal kommt die Meldung, mal nicht und man muss es aktiv prüfen. Es wird allerdings nicht ein zweiter mal hochgeldaden, sondern nach der ableuf der "Sanduhr" bleib dieses Fenster einfach so stehen:
![grafik](https://user-images.githubusercontent.com/47562310/91301340-081d9d00-e7a5-11ea-944e-5b2b648c6d43.png)

es kann nicht nachvollzogen werden wann die Meldung kommt und wann nicht.

**Comment by erikradisch** [comment]
Das in dem Beispiel ist ja gerade das korrupte JPG. Könnte das der Grund gewesen sein?

**Comment by OKienzler** [comment]
Es ist immer so, egal bei welchen Bildern. Selten kommt eine Meldung, dass es bereits hochgeladen ist und eben willkürlich. ich konnte keine Regel feststellen, wann die Meldung kommt und wann nicht

**Comment by erikradisch** [comment]
Bitte achte mal in Zukunft drauf. So ist das für mich nicht nachvollziehbar. Informiere mich, sobald es mal nicht geklappt hat.
Allgemein ist es aber so, dass nur der Dateinamen überprüft wird. Weicht der auch nur minimal ab, beschwert sich das System nicht mehr.

**Comment by OKienzler** [comment]
so jetzt kam heute zum ersten mal diese Meldung, sonst kommt es so gut wie nie. Was bei diesem Bild Kizil224_RA_InnerWall_III8861_B0197_KLEIN  (hier kam die Meldung) anders 
als bei dem Kizil212_Cella_SWLe_Reg01_III8400_Det03_B0118_01 (hier kam keine Meldung)

![grafik](https://user-images.githubusercontent.com/47562310/91583782-f62d2d00-e951-11ea-93c4-625e06cd82d7.png)

**Comment by OKienzler** [comment]
bei dem (gerade eben) kommt keine meldung
Kizil224_RA_InnerWall_III8861_B0197_KLEIN
![grafik](https://user-images.githubusercontent.com/47562310/91584286-b286f300-e952-11ea-86a0-2a89a493483b.png)

**Comment by erikradisch** [comment]
Hast Du "Kizil224_RA_InnerWall_III8861_B0197_KLEIN" insgesamt 3 mal versucht, hochzuladen? Also zwei mal übrpürft, ob die Meldung kam?

**Comment by erikradisch** [comment]
Das habe ich mir schon gedacht. In diesen Fällen bekommst Du eine andere Fehlermeldung. Mit anderen Worten. Neben dem Problem mit dem Doppelten Dateinamen hat auch der Upload nicht richtig geklappt. 
Ich lasse die Fehler jetzt auch ausgeben. Allerdings ist er leider sehr kryptisch. Was genau in diesen Fällen im Hintergrund schiefläuft ist sehr schwer nachzuvollziehen. Ob und wenn ja, warum das nur bei Duplikaten auftritt, kann ich nicht sagen. Ich bespreche am Dienstag das mal mit Uwe.

**Comment by OKienzler** [comment]
jetzt kam wieder so eine Meldung bei Kizil 17 (bei Kizil 13, direkt zuvor kam die Meldung mit "Bad Gateway"

![Uploading grafik.png…]()

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/94409567-9d31fe00-0176-11eb-926f-8e88fa24ec0e.png)

**Comment by erikradisch** [comment]
Das Bild "Kizil017_SALe_OuterWallLe_III8868_B0419_KLEIN" kam ohne Felhler durch?

**Comment by OKienzler** [comment]
Nein, bei 
- Kiz13 - Fehlermeldung "Bad Gateway"
- Kiz 17 - Fehlermeldung "duplicate Image Error"

Beide Bilder waren in Kucha SW, aber die Meldung war unterschidlich, darum geht es.

**Comment by erikradisch** [comment]
Das Bild lief aber sauber durch?
Kizil017x_Cella_FWRi_IB8875_B0375

**Comment by erikradisch** [comment]
Wie sind wir hier verblieben?

**Comment by OKienzler** [comment]
zur Zeit gibt es keine Probleme, ich schließe es und melde mich ggf. wieder

**Comment by OKienzler** [comment]
kaum geschrieben und doch kommt das Problem wieder:
diese sind drin:
Simsim35-36_Nord_B1244_pos.tif
Simsim35-36_Nord_B1244.jpg

und das Bild ist nicht in der Datenbank, aber es kommt eine Fehlermeldung
Simsim35-36_Nord_B1244.tif

![grafik](https://user-images.githubusercontent.com/47562310/188105574-f417d715-82bb-47cc-99fa-e9f2a5cbc594.png)

**Comment by erikradisch** [comment]
Naja. Das ist eben jetzt die Fehlermeldung, die durchgereicht wird, wenn bereits vorher ein Fehler auftritt. Das habe ich gemacht, um das nicht Anzeigen im ursprünglichen Issue zu kompensieren. Das muss also so. Besser bekomme ich es nicht hin, da absolut nicht klar ist, was den Fehler verursacht.

**Comment by OKienzler** [comment]
könnte es vielleicht daran liegen, dass der Dateiname gleich ist? Und dass das System xxx.jpg und xxx.tif als gleich ansieht? Obwohl ich solche Probleme schon lange nicht mehr hatte und vor ein paar Wochen ging es.

Es z.B. betrifft diese Dateien:
Simsim35-36_Nord_B1244.jpg
Simsim35-36_Nord_B1244.tif

und
Simsim35-38_Nord_B1247.jpg
Simsim35-38_Nord_B1247.tif

**Comment by erikradisch** [comment]
Die System-Strucktur ist darauf ausgelegt, dass der Datainahmen eindeutig ist. In solchen fällen würde ich eigentlich einen Zusatz erwarten. So ist es doch auch in dne meisten Fällen, oder?

**Comment by OKienzler** [comment]
Stimmt, ich habe vergessen im Dateinamen _KLEIN dazu zu sschreiben :) ups...ich schließe issue
