### ISSUE TITLE
Doppelte Einträge in Painted Representation 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#272]
bitte doppelte Einträge, obwohl von Fang nur einmal erfasst (Fang hat keinen Zugang zu GitHub, deshalb mache ich den Eintrag)
das betrifft z.B.
Kiz 14_ceiling
Kizil 14_Mahabodhisatva

![grafik](https://user-images.githubusercontent.com/47562310/91302742-3c925880-e7a7-11ea-93c4-ce6fe1dd6deb.png)

**Comment by erikradisch** [comment]
da fehlt das Verb. :-) Was soll ich denn hier machen? Löschen könnt ihr selbst...

**Comment by OKienzler** [comment]
Es geht darum zu prüfen warum es überhaupt aufkommt. Darber haben wir am Montag gesprochen und Du wolltest Dir das mal anschauen ;) GitHub Eintrag nur damit es nicht in Vergessenheit gerät

**Comment by erikradisch** [comment]
Bisher war im Log dazu nichts zu finden. Ich habe das Log jetzt deutlich erweitert, falls es noch einmal auftritt. Es scheint aber eher etwas grundsätzlich nicht kompatibel in Fangs Chrome zu sein (warum auch immer. Mit meinem Chrome, selbe Version, klappt es einwandfrei...). Da sie jetzt Firefox benutzt, kann sich das Problem eh erledigt haben. Ich lasse das Issue mal noch ein bis zwei Wochen auf. Sollte es dann keinen neuen Fall geben, würde ich ihn erst mal schließen, bis etwas entsprechendes auftritt.

**Comment by erikradisch** [comment]
Das scheint sich ja geklärt zu haben, deswegen schließe ich das mal. Fals es wieder auftritt, wieder öffnen.
