### ISSUE TITLE
current location, manuelle Änderung erlauben 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#273]
current location wurde in Übereinstimmung mit dem Dateinamen übernommen, sehr schön! Bei manchen Bildern ist "Eremitage" zwar in dem Dateinamen drin als Info, es handelt sich aber um die Zeichnung von Grünwedel, die sich in AKu (museum Berlin) befindet. Ich konnte es manuel nicht ändern. Manuelle Änderung sollte wäre an der Stelle wichtig, könntest Du es bitte so einstellen:

Das betrifft z.B. Kizil004_SARi_OuterWall_IB9045_Eremitage_VD856_02-03-1426385_Gruenwedel1920_I_p048_fig038_Vajrapani
![grafik](https://user-images.githubusercontent.com/47562310/91322458-0dd4ac00-e7c0-11ea-9fcb-4077d8eb652b.png)

**Comment by erikradisch** [comment]
Das geht aber. Ist nur leider ein ziemliches gefummel, weil man erst alles rauslöschen muss und am besten die Anfangsbuchstaben des neuen Eintrages kennt. Das tut mir wirklich leid, dass das so schwierig ist, das ist aber dieses... nunja .... ausbaufähige Framework, das wir verwenden.  Habe es bei demerwähnten Bild gerade händisch geändert. Ich schließe es deswegen. Wenn es Probleme gibt, müssen wir es am Freitag mal über Videokonferenz gemeinsam machen.
