### ISSUE TITLE
Es werden keine Bilder angezeigt, wenn ein Eintrag geöffnet wird

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#274]
bitte noch mal prüfen, es werden keine Bilder mehr angezeigt (auch bie Fang nicht):
![grafik](https://user-images.githubusercontent.com/47562310/91333608-159b4d00-e7ce-11ea-8666-ee0aba8f9204.png)

**Comment by erikradisch** [comment]
da ich ja die neue Version mit Vor- und Zurük-Buttons noch nicht in Kucha eingebunden hatte, vermute ich, dass Du in Kuchatest bist? Dort funktionieren in der Tat viele Bilder nicht, das ist aber auch nicht weiter schlimm.

**Comment by OKienzler** [comment]
Nee, es geht um Kucha-Arbeitsversion, da werden keine Bilder, wenn ich eine Kachel öffne, nicht angezeigt.

Was hat es mit Vor- und zurück- Buttons zu tun? Die Buttons sind in der Arbeitsversion bereits drin gewesen und haben auch funktioniert.

Von meinem iPhone gesendet

**Comment by erikradisch** [comment]
Na, Du meintest doch früher heute, dass die neue Version noch nicht eingespielt hatte. Ich hatte dan auch geschaut und bei mir wurde auch die alte angezeigt. Mit einem mal schien aber doch die neue angezeigt zu werden (ich hatte nichts geändert). Jedenfalls hatte ich bei der neuen Version vergessen, von lokalen cantaloupe auf den globalen umzustellen. Das war mein fehler, Entschuldigung. Ich habe ihn behoben.

**Comment by OKienzler** [comment]
Ja genau so war es bei mir auch. Zuerst die alte Version und dann plötzlich die neue. Ich dachte, dass du dann doch nicht bis zum Abend gewartet hast und zeitnah die neue eingespielt hast. 

Von meinem iPhone gesendet
