### ISSUE TITLE
Bild wird nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#276]
Dieses Bild habe ich heute hochgeladen und es wird mir nicht angezeigt, würdest Du bitte prüfen:
Kizil017x_x_IB8875_B0375

![grafik](https://user-images.githubusercontent.com/47562310/94430093-a4b3d000-0193-11eb-9b01-0967c1e97a4d.png)

**Comment by OKienzler** [comment]
hier ist auch ein Problem, das Bild wird nicht angezeigt:
Kizil110_RW_LunetteGen_Ph004_reconstr
![grafik](https://user-images.githubusercontent.com/47562310/94432394-ff9af680-0196-11eb-97c3-a90bfae0a561.png)

**Comment by konczaknagel** [comment]
Habe auch das Problem, dass manche Bilder nicht angezeigt werden, wie z.B. hier:
![grafik](https://user-images.githubusercontent.com/45167567/97435783-36446800-1921-11eb-8b5c-96c1d1ca488d.png)
![grafik](https://user-images.githubusercontent.com/45167567/97435816-42302a00-1921-11eb-847e-ac6a3d6aada3.png)

**Comment by erikradisch** [comment]
Das ist Kuchatest, oder?

Am 28. Oktober 2020 13:27:19 MEZ schrieb konczaknagel <notifications@github.com>:
>Habe auch das Problem, dass manche Bilder nicht angezeigt werden, wie
>z.B. hier:
>![grafik](https://user-images.githubusercontent.com/45167567/97435783-36446800-1921-11eb-8b5c-96c1d1ca488d.png)
>![grafik](https://user-images.githubusercontent.com/45167567/97435816-42302a00-1921-11eb-847e-ac6a3d6aada3.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/saw-leipzig/kucha/issues/276#issuecomment-717899589

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by OKienzler** [comment]
In meinem Fall ist der Fehler in Kucha-Arbeitsversion und Kumtura31_SALe_Ph001_20190729092501 wird bei mir in der Kucha-Arbeitsversion auch nicht angezeigt

**Comment by erikradisch** [comment]
ja, habe ich auch gerade gesehen. Zumindest beim ersten ist das Bild im Imageserver fehlerhaft.

**Comment by konczaknagel** [comment]
In meinem Fall war es ebenfalls die Arbeitsversion.

**Comment by erikradisch** [comment]
Also. Das erste (Kizil017x_x_IB8875_B0375) ist fehlerhaft. 
Das Zweite (hier ist auch ein Problem, das Bild wird nicht angezeigt:
Kizil110_RW_LunetteGen_Ph004_reconstr) wird angezeigt, aber mit einem völlig überzogenen contrast (wann man da rumstellt, wird es sichttbar). Eventuell sind auch hier die Metadaten kaputt. Ich würde das auch mal ersetzen. Allgemein scheint das aber ein extrem seltsammes Bild zu sein, da es als Tiff unter einen MB hat.
Das letzte Bild ist seltsam, da es da ist, funktioniert und auch ansteuerbar ist. Cantaloup bringt auch keinen Fehler. Warum hier ein Fehler kommt ist mir noch unklar. 
Ich würde es auch mal mit ersetzen, evenutell wird dabei ein neues chaching angestoßen und das Bild ist wieder da, mal sehen.
Kleines Problem: 
Ich finde die Bilder weder in der Cloud... Ich gebe die Namen im Unterordner images suchen, finde jedoch nichts. Könnte sie mir mal jemand schicken?

**Comment by erikradisch** [comment]
Bei mir geht es über die cloud nicht:
![grafik](https://user-images.githubusercontent.com/34335811/97472517-34db6580-194a-11eb-9d42-820fc15b45f8.png)

**Comment by OKienzler** [comment]
man mus in den entsprechnden Ordner reingehen, dann wird das Bild gefunden
![grafik](https://user-images.githubusercontent.com/47562310/97474204-25f5b280-194c-11eb-9bc6-79540b0b6720.png)

**Comment by konczaknagel** [comment]
Weitere Bilder werden auch nicht angezeigt. Z.B.
![grafik](https://user-images.githubusercontent.com/45167567/97848976-28f8f600-1cf2-11eb-8f59-31544854b19c.png)

**Comment by konczaknagel** [comment]
In "Painted Representation" werden die Masterbilder, die im Image-Pool nicht angezeigt werden, auch nicht angezeigt:
![grafik](https://user-images.githubusercontent.com/45167567/98537858-31b97100-228a-11eb-9569-6ba42db3d3fe.png)
![grafik](https://user-images.githubusercontent.com/45167567/98537874-39791580-228a-11eb-8dac-b798f832e872.png)
![grafik](https://user-images.githubusercontent.com/45167567/98537891-3e3dc980-228a-11eb-9aa9-0ad54623941b.png)

**Comment by OKienzler** [comment]
weitere, eben hochgeladenen Bilder werden nicht angezeigt:
Simsim41_SALe_InnerWall_PtRi_Ph001_3
Simsim41_SALe_InnerWall_PtRi_Ph001_4
Simsim41_SALe_InnerWall_PtRi_Ph001_5
Simsim41_SALe_InnerWall_PtRi_Ph001_6

**Comment by erikradisch** [comment]
mit ImageMagick dürften jetzt alle bilder wieder zu sehen sein.

**Comment by OKienzler** [comment]
Bei diesen Bildern gibt es immer noch Probleme:
Kizil017x_x_IB8875_B0375 >>>> dieses habe ich neu von NAS zum Austauschen gesendet, es wird immer noch nicht angezeigt
Kizil110_RW_LunetteGen_Ph004_reconstr >>> wird nichts mehr angezeigt, auch nicht sehr dunkel

Diese Bilder machen keine Probleme mehr und sind jetzt zu sehen:
Kumtura31_SALe_Ph001_20190729092501 
Simsim41_SALe_InnerWall_PtRi_Ph001_3
Simsim41_SALe_InnerWall_PtRi_Ph001_4
Simsim41_SALe_InnerWall_PtRi_Ph001_5
Simsim41_SALe_InnerWall_PtRi_Ph001_6

**Comment by erikradisch** [comment]
Besteht das Problem noch?

**Comment by konczaknagel** [comment]
Im Fall von *B0375* besteht das Problem noch. Würde davon ausgehen, dass es bei den anderen Bildern genauso ist.

**Comment by erikradisch** [comment]
Das Bild scheint aber in der Tat beschädigt zu sein. Wenn ich es runter lade und anschauen will, wird bei mir weniger als die Hälfte angezeigt. Ist das bei der Version auf dem NAS auch so?
Ansonsten haben wir ja aber den Workaround. Also Bild runterladen, überspeichern und wieder hochladen.

**Comment by konczaknagel** [comment]
Auf dem NAS ist das Bild unbeschädigt. Habe das Bild jetzt Workaround-mäßig heruntergeladen und überspeichert. Nur ist mir unklar, wie ich es hochladen soll.

**Comment by konczaknagel** [comment]
Prima, mein Bild-Problem ist damit gelöst. Das Bild wird jetzt angezeigt.
