### ISSUE TITLE
Bilder-Zoom zum Teil fehlerhaft

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#277]
Manche Bilder werden beim Vergrößern kachelig und die Bildsegmente sind durcheinander angeordnet:
![grafik](https://user-images.githubusercontent.com/45167567/94661772-cc2ba980-0307-11eb-97d0-e303400cd70b.png)
![grafik](https://user-images.githubusercontent.com/45167567/94661845-e1083d00-0307-11eb-88c9-552a95405bbc.png)

**Comment by OKienzler** [comment]
das gleiche Problem bei eben hochgeladenem Bild: Kumtura31_SARLe_Ph001_01

![grafik](https://user-images.githubusercontent.com/47562310/95775116-1165b900-0cc2-11eb-82e1-c5d76c143aac.png)

**Comment by erikradisch** [comment]
Bitte mal chache löschen und überprüfen, sollte jetzt gehen.

**Comment by OKienzler** [comment]
Das Bild: Kumtura31_SARLe_Ph001_01 geht bei mir, andere Fälle hatte ich bisher nicht

**Comment by konczaknagel** [comment]
Habe verschiedene Bilder durchprobiert und es scheint jetzt alles zu klappen.
Danke!
