### ISSUE TITLE
Iconography Baum_2 Issues: aus der kleinen Ansicht des Bildes und neuen Namen für eine Ikonography generieren

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#278]
![grafik](https://user-images.githubusercontent.com/47562310/94684616-964aed00-0328-11eb-80e8-eac4c0f7e455.png)

auch wenn ich es klein mache sehe ich den Baum nicht:

![grafik](https://user-images.githubusercontent.com/47562310/94685467-bf1fb200-0329-11eb-9f1a-582adf113030.png)

**Comment by OKienzler** [comment]
Der Baum ist nur dann zu sehen, wenn ich aus der großen Ansicht die Polygone setze.

**Comment by OKienzler** [comment]
ich dachte man kann direkt einen neuen Iconography-name von da aus vergeben, oder?

![grafik](https://user-images.githubusercontent.com/47562310/94688283-a6b19680-032d-11eb-91b9-98f6c8a35c21.png)

**Comment by erikradisch** [comment]
nein, ein neuer Eintrag ist wie gehabt zu vergeben. Ich meinte ja auch beim letzten Treffen, dass ich das ungern ändern will, da es wirklich kompliziert wäre.

**Comment by erikradisch** [comment]
Zum ursprünglichen Issue: Ja, das ist einfach zu klein. Deswegen wird in der nächsten Version der Trenner zwischen Bildern und Eingabemaske bewegbar sein, sodass du das Bild wesentlich vergrößern kannst. Das kann damit geschlossen werden, oder?

**Comment by erikradisch** [comment]
Du kannst aber übrigens auch einfach das Bild höher ziehen.

**Comment by erikradisch** [comment]
Wenn Du magst, komme ich am Freitag mal ans Institut oder Du hierher und wir schauen es uns gemeinsam an? Ist eventuell einfacher zum Besprechen von Problemen

**Comment by OKienzler** [comment]
Ich bin erst wieder am 12.10. hier. Also bin am Freitag nicht da.

**Comment by OKienzler** [comment]
Mir ist noch nicht klar, wie ich es miteinander verbinden soll? 

am Maontag sagtest Du, dass die bestehenden Ikonography-Einträge nicht mit neu-gesetzten Polygonen verbindet werden können. Aber wie würde es mit neuen Einträgen funktionieren? z.B. "Vehicle" habe ich neu gemacht, bei bem Bild erscheint natürlich jetzt Vehicle, aber nicht im dem Baum wenn man druüber fährt, oder funktioniert es noch nicht?

![grafik](https://user-images.githubusercontent.com/47562310/94690367-525be600-0330-11eb-8a53-4f07c5398e77.png)

**Comment by erikradisch** [comment]
Naja, die neue Version, die Ihr am Montag gesehen habt, braucht noch Zeit. Ich hoffe, sie heute hochladen zu können.

**Comment by erikradisch** [comment]
Mit anderen Worten, das ist noch die alte Verison, da geht es noch nicht.

**Comment by OKienzler** [comment]
ok dann warten wir auf die nächste Version :)

**Comment by erikradisch** [comment]
Soll ich Dir mal schnell die neue Version hochladen?
