### ISSUE TITLE
"moon" in Iconography Baum bei Annotation lässt sich nicht auswählen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#279]
![grafik](https://user-images.githubusercontent.com/47562310/94705749-b044f980-0341-11eb-9eef-179eaf296f42.png)

**Comment by erikradisch** [comment]
sollte jetzt gehen

**Comment by OKienzler** [comment]
Du bist zu schnell mit Schließen, ich habe 279 und 280 noch nicht getestet ob es geht

Von meinem iPhone gesendet
