### ISSUE TITLE
"hare" markiert, Hase wird nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#280]
![grafik](https://user-images.githubusercontent.com/47562310/94706270-49741000-0342-11eb-8bf0-859a27a0f98f.png)

**Comment by OKienzler** [comment]
jetzt nach der Aktualisierung der Seite klappt es, dass der "hare" grün angezwigt wird, aber "flower"-Zuordnung bleib zugeordnet obwohl vorher entfernt und gespeichert:
![Uploading grafik.png…]()

**Comment by OKienzler** [comment]
![Uploading grafik.png…]()

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/94707710-0adf5500-0344-11eb-8d75-e869293ea1b3.png)

**Comment by OKienzler** [comment]
habe gespeichert und Kachel geschlossen, nach erneutem Öffnen erschien weder "hare" noch "flower" als annotation. "hare" war noch im Baum als grün zu sehen, flower nicht.
Dann die Seite erneuert und "hare" und "flower" wieder da, aber flower muss weg.

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/94708244-abce1000-0344-11eb-97c8-1b026b36781f.png)

**Comment by OKienzler** [comment]
also Umbenennung funktioniert nicht, falsch gemachte Zuordnung funktioniert nur auf den ersten Blick, denn nach dem Speichern und Erneuern der Seite sind alle, auch die falsche zuordnungen wieder da, habe auch in Kiz 8 (Garuda) ausprbiert:

**Comment by OKienzler** [comment]
Bild 4:
![grafik](https://user-images.githubusercontent.com/47562310/94712127-534d4180-0349-11eb-8d2c-239261e1bf66.png)

**Comment by erikradisch** [comment]
sollte jetzt ordentlich gehen.
