### ISSUE TITLE
Hare und Moon sind wieder verschwunden

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#281]
![grafik](https://user-images.githubusercontent.com/47562310/95995660-16497a80-0e32-11eb-9058-f6b43f918fee.png)

seite erneuert, Hare und Moon sind wieder verschwunden:
![grafik](https://user-images.githubusercontent.com/47562310/95996111-98d23a00-0e32-11eb-98cd-2b5b271c405f.png)

**Comment by erikradisch** [comment]
Deine Annotation steht bei mir als gelöscht drin. Was genau hast Du denn gemacht? Lotus noch hinzugefügt und wieder gelöscht?

**Comment by OKienzler** [comment]
ich wollte nur Lotus löschen, als Test ob Löschen überhaupt funktioniert. Dann sind aber auch hare und moon verschwunden. Beim nächsten mal habe ich nur hare und moon gespeichert und beim erneuten laden der Seite, waren die nicht mehr da.

Jetzt scheint es wieder zu funktionieren

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/96014452-b1e4e600-0e46-11eb-8b1d-f645c1eb3054.png)

**Comment by OKienzler** [comment]
ich habe zum Testen "Elephant" zusätzlich zu moon und hare zugeordnet um zu testen. Gespeichert. Seite erneuert. Jetzt sind wieder alle Bezeichnungen verschwunden.

**Comment by erikradisch** [comment]
Probier jetzt mal, sollte jetzt gehen.

**Comment by erikradisch** [comment]
kann das geschlossen werden?

**Comment by OKienzler** [comment]
ich teste es noch einmal kurz und schließe es dann, wenn alles geht

**Comment by OKienzler** [comment]
Es wird gerade nichts angezeigt oder ist es wieder mal sehr, sehr langsam? 

![grafik](https://user-images.githubusercontent.com/47562310/97458565-1de14700-193b-11eb-977e-d4592ec988b4.png)

**Comment by OKienzler** [comment]
Funktioniert in der Kucha-Testversion immer noch.
