### ISSUE TITLE
Bearbeitungs-Historie

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#282]
Ji Ho hat zuletzt am 12.10. um 11:14 etwas geändert, aber es steht als last modified Olga um 11:15. Da hatten wir unsere Besprechung und ich habe nichts geändert gehabt.

![grafik](https://user-images.githubusercontent.com/47562310/95997118-be137800-0e33-11eb-96c3-ff579f6deda7.png)

**Comment by erikradisch** [comment]
Ich würde vorschlagen das da oben komplett rauszulöschen. Es funtkioniert nicht und erfüllt keinen Zweck mehr, jetzt wo wir die history haben.

**Comment by OKienzler** [comment]
in der Kucha-Testversion funktioniert
