### ISSUE TITLE
Image tools in Painted Representation

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#283]
Image tools in Painted Representation, einmal angeklickt -> verscwindet nicht, wenn nicht gebraucht wird. Die Kachel muss zuerst geschlossen werden, erst dann wird das Menü wieder zugeklappt:

![grafik](https://user-images.githubusercontent.com/47562310/96242008-43696a80-0fa3-11eb-9c8e-e02ba4c301c2.png)

**Comment by erikradisch** [comment]
Du musst zum schließen wieder drauf drücken...

**Comment by OKienzler** [comment]
gut, passt.
