### ISSUE TITLE
Annotation: Nachträgliches Editieren funktioniert nicht

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#284]
Annotation: Nachträgliches Editieren funktioniert nicht. 
Die Linien erscheinen nicht mehr gelb um die Annotation noch mal anzupassen:

![grafik](https://user-images.githubusercontent.com/47562310/96245026-28005e80-0fa7-11eb-8189-fec5bdbe615a.png)

**Comment by erikradisch** [comment]
Hattest Du da gerade eine Annotation angelegt?

**Comment by erikradisch** [comment]
bei mir geht es mit alten ohne Probleme

**Comment by erikradisch** [comment]
hmm. auch bei neuen Annotationen geht das. Ich kann diesen Fehler absolut nicht reproduzieren...

**Comment by OKienzler** [comment]
im Moment hat es wieder funktioniert, aber noch nicht so flüssig. Ich werde weitertesten und melde mich ggf. wieder
