### ISSUE TITLE
Element lässt sich nicht zum Bearteiben auswählen 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#285]
![grafik](https://user-images.githubusercontent.com/47562310/96258350-2e4d0580-0fbc-11eb-955e-41bc1c92d4b2.png)

**Comment by OKienzler** [comment]
wie #284 
nur "scarf" wieder bearbieten geht nicht

**Comment by erikradisch** [comment]
Da hast Du alle Annotationen angeschalten, oder? Ansonsten ganz viele gemacht? Wenn ersteres, einfach alle Annotationen bearbeiten abschalten. Wenn zweites, einfach scarf auswählen.
