### ISSUE TITLE
Iconography Baum in Kucha Test nicht sichtbar

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#286]
Iconography Baum in Kucha Test nicht sichtbar. Wäre gut wenn es geht, damit man üben kann.

![grafik](https://user-images.githubusercontent.com/47562310/96276554-76c3ed80-0fd3-11eb-9d94-5bc87114b73f.png)

**Comment by erikradisch** [comment]
der fehlt ja nur bei den ersten beiden Einträgen. Da ist er mal beim Rumtesten verloren gegangen. (Deswegen haben wir ja kuchatest, damit man mal was kaputt machen kann ;-))

**Comment by OKienzler** [comment]
wirst Du den wiedeherstellen?  ich meine damit z.B. Dominika und Robert A. zuerst mal da probieren können neue Kacheln anzulegen.

**Comment by erikradisch** [comment]
Dieser Baum ist nicht zu sehen, da keine Annotationen in den Bildern vorgenommen wurde und früher keine Iconographie gesetzt wurde. Sobald eine Annotation gemacht wurde, erscheint der Eintrag im Ikonographiebaum. Einfach so setzen ist jetzt natürlich nicht mehr möglich.
