### ISSUE TITLE
neue Kachel in KuchaTest, iconography Baum fehlt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#287]
wirst Du den wiedeherstellen? ich meine damit z.B. Dominika und Robert A. zuerst mal da probieren können neue Kacheln anzulegen.

**Comment by erikradisch** [comment]
was genau meinst Du damit?

**Comment by OKienzler** [comment]
versuche in **KuchaTest** eine neue Kachel in Paited Representation anzulegen.
- Bilder werden nicht angezeigt
- Iconography Baum fehlt

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/96688721-c878c900-1381-11eb-9ca2-d45d38597003.png)

**Comment by OKienzler** [comment]
![Uploading grafik.png…]()

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/96688855-ee05d280-1381-11eb-949f-e7a88a881ee5.png)

**Comment by OKienzler** [comment]
Schau auch #286 - hast Du zu schnell geschlossen

**Comment by erikradisch** [comment]
Sobald Du eine Annotation vornimmst, wird in dem Iconographiebaum der Eintrag erscheinen. Ohne Annotation einen Eintrag zu setzen geht ja jetzt eben nicht mehr. Der Baum ist quasi ins Bild gewandert. Man kann ihn sich übrigens auch noch anschauen, indem man auf Iconographie hinzufügen (plus) klickt. Dort wird der gesamte Baum angezeigt.
Bilder mache ich gleich wieder zugänglich. Ich vergesse regelmäßig den Pfad von meinem lokalen Cantaloupe zu ändern.
