### ISSUE TITLE
entry last modified in der Ansicht noch sichtbar

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#288]
![grafik](https://user-images.githubusercontent.com/47562310/96715250-96785e80-13a3-11eb-9b6e-2a905527e537.png)

**Comment by erikradisch** [comment]
In Kuchatest habe ich das jetzt gemacht. Stattdessen steht da oben jetzt die interne ID. Diese kann für Analysezwecke sehr nützlich sein.

**Comment by OKienzler** [comment]
Also "6" ist eine interne ID, richtig?

![grafik](https://user-images.githubusercontent.com/47562310/97475221-42deb580-194d-11eb-8fb9-e848df4f7a58.png)

**Comment by erikradisch** [comment]
genau. mit der ID finde ich einträge viel einfacher.

**Comment by OKienzler** [comment]
In Kucha-Test funktioniert
