### ISSUE TITLE
Kucha-Arbeitsversion: Master-Bild auswählen, Bilder füllen nicht den kompletten Bildbereich aus

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#289]
- Kucha-Arbeitsversion: Master-Bild auswählen - wie geht es jetzt? Markieren funktioniert nicht mehr.
- Bilder füllen nicht den kompletten Bildbereich aus
- ein Bild wurde nicht geladen
![grafik](https://user-images.githubusercontent.com/47562310/96740707-5f18aa80-13c1-11eb-80d7-955cc5b45858.png)

**Comment by OKienzler** [comment]
Beim zweiten Versuch wurden alle Bilder geladen, aber die 2 ersten Fragen sind noch aktuell:
- Kucha-Arbeitsversion: Master-Bild auswählen - wie geht es jetzt? Markieren funktioniert nicht mehr.
- Bilder füllen nicht den kompletten Bildbereich aus

**Comment by erikradisch** [comment]
mach mal die Bilderliste ein wenig größer oder kleiner, dann passt es wieder. 
Masterbild wird wie bisher gewählt, nur darfst Du nicht auf das Bild klicken, sondern innerhalb der Kachel, die das Bild umgibt.
Zum nicht geladenen Bild: Das kann daher kommen, dass wir den Chache von Cantaloupe löschen mussten. Es kann schon durchaus sein, dass der arme Server mal nicht gleich alles schafft. Das würde ich gerade darauf schieben.

**Comment by OKienzler** [comment]
jeztz plözlich hat alles funktioniert ohne, dass ich da was gemacht habe, ich befand mich noch in der Kachel. Es ist extrem !!! langsam, so schlimm langsam war es noch nie
