### ISSUE TITLE
Neues Iconography-Element nicht hinzufügbar (Kucha-Test und Kucha-Arbeitsversion)

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#290]
Kucha-Arbietsversion:
![grafik](https://user-images.githubusercontent.com/47562310/97437848-5a557880-1924-11eb-9ca8-fec8c5e27ec9.png)

button ist da aber beim Anklicken passiert nichts:
![grafik](https://user-images.githubusercontent.com/47562310/97437748-36923280-1924-11eb-8811-d43850ba715a.png)

**Comment by erikradisch** [comment]
Also, in der Kucha-Arbeitsversion geht es natürlich bisher nicht, die neue Version ist in der Testumgebung.
Ein neues Element lässt sich im Paintet-Representation-Editor hinzufügen, nicht bei der Suche.

**Comment by OKienzler** [comment]
Kucha-Test:

Button läst sich gar nicht auswählen und das Fenster wie im Bild 1 erscheint nicht:
![grafik](https://user-images.githubusercontent.com/47562310/97438131-adc7c680-1924-11eb-8210-b911ef060750.png)

Beim Anklicken in der Kachel passiert nichts:
![grafik](https://user-images.githubusercontent.com/47562310/97438319-ebc4ea80-1924-11eb-97af-fa031549105d.png)

**Comment by erikradisch** [comment]
Das funktioniert nun wieder wie früher, Du musst ein Element auswählen, damit dem PC klar ist, welches zu bearbeiten ist, bzw wo etwas einzuügen ist.

**Comment by OKienzler** [comment]
Also, in der Kucha-Arbeitsversion geht es natürlich bisher nicht, die neue Version ist in der Testumgebung. - > zuvor ging es! In der Testversion ging es nur über die Suche (bevor Du es letzten Mittwoch umgestellt hast). Und die Version hast Du ja in die Arbeitsversion übernommen. 

Ein neues Element lässt sich im Paintet-Representation-Editor hinzufügen, nicht bei der Suche. .-> NEIN, das geht nicht, siehe Bild 2. Zuvor ging es in beiden Ansichten.

Also es geht jetzt in keiner Version, in keiner Ansicht

**Comment by OKienzler** [comment]
Das funktioniert nun wieder wie früher, Du musst ein Element auswählen, damit dem PC klar ist, welches zu bearbeiten ist, bzw wo etwas einzuügen ist. - in Kucha-Test????

**Comment by erikradisch** [comment]
bei dem Problem, dass man die Ickonography-Suche nicht mehr öffnen kann, schau ich mal.

**Comment by OKienzler** [comment]
Kucha-Arbeitsversion:
Iconography-Suche öffnet sich, aber es gibt ken "+"
![grafik](https://user-images.githubusercontent.com/47562310/97439334-54f92d80-1926-11eb-850c-dda4b0af165f.png)

**Comment by OKienzler** [comment]
Kucha-Test: Iconography-Suche öffnet sich nicht

**Comment by OKienzler** [comment]
Kucha-Test und Kucha-Arbeitsversion: Iconography-Suche öffnet sich nicht in einer Kachel:
![grafik](https://user-images.githubusercontent.com/47562310/97439688-c46f1d00-1926-11eb-9d3b-a7e417c08eb1.png)

**Comment by erikradisch** [comment]
Zum letzten Punkt: hast Du ein element ausgewählt, das Du editieren willst?

**Comment by erikradisch** [comment]
zu der fehlenden Möglichkeit einen Iconography-Entry bei der Suche hinzuzufügen: Ich schätze, Du blockst cookies und musst sich bei jedem mal, wenn Du die Seite aufrufst neu einloggen. 
Ich habe jetzt etwas eingebaut, was die Zugangsrechte beim Aufruf prüft, jetzt sollte es auch bei Dir dort möglich sein. Natürlich nur in Kuchatest!

**Comment by erikradisch** [comment]
Iconographysuche sollte jetzt wieder zu öffnen sein

**Comment by erikradisch** [comment]
kannst Du das mal überpüfen?

**Comment by OKienzler** [comment]
Kucha-Test, über iconography search geht es wieder:
![grafik](https://user-images.githubusercontent.com/47562310/97702281-06c36600-1aaf-11eb-99f3-1881ea5ac588.png)

**Comment by OKienzler** [comment]
Kucha-Test, über eine Painted Representation (Kachel) geht es nicht, ist nicht auswählbar:
![grafik](https://user-images.githubusercontent.com/47562310/97702430-412d0300-1aaf-11eb-81e7-cebd8add8940.png)

**Comment by erikradisch** [comment]
mir scheint, Du hast immer noch nichts ausgewählt, wohhin Du den Eintrag anlegen willst, bzw. welchen Du verändern möchtest. (Siehe Bild)
![grafik](https://user-images.githubusercontent.com/34335811/97703571-1e9be980-1ab1-11eb-9176-67540dd81e16.png)

Außerdem wird dein neuer Eintrag im Baum nur sichtbar, wenn Du alle Einträge einblenden lässt, ansonsten sind es ja nur die bereits gewählten wo eben dieser noch nicht mit dabei ist.

**Comment by OKienzler** [comment]
Richtig, ich habe es nicht ausgewählt, weil ich dazu zuerst man den gesamten Baum sehen muss, und da scheitert es schon. Es ist dann notwendig, wenn ein Element hinzugefügt werden muss, der aber noch nicht vorhanden ist und die Kategogie ist nicht sichtbar.

**Comment by erikradisch** [comment]
Und den gesamten Baum einzublenden geht bei Dir nicht? (Symbol ganz rechts)

**Comment by OKienzler** [comment]
doch, aber es wird nur das eingeblendet was schon als element zuvor hinzugefügt wurde, aber nicht der gesamte Baum

![grafik](https://user-images.githubusercontent.com/47562310/97704773-4be99700-1ab3-11eb-8bf7-31f14a54ba15.png)

**Comment by OKienzler** [comment]
Es geht zum Beispiel nicht wenn ich ein neues animal hinzufügen möchte

**Comment by OKienzler** [comment]
neues "animal" würde ich nur über die Search funktion hinzufügen können, aber nicht in der kachel wie du es letzen Mittwoch hinzugefügt hast

**Comment by erikradisch** [comment]
ganz rechts, nicht ganz links
![grafik](https://user-images.githubusercontent.com/34335811/97705048-b26eb500-1ab3-11eb-9daa-c9a55e97c253.png)

**Comment by OKienzler** [comment]
Achso, ganz links habe ich noch gar nicht beachtet

**Comment by OKienzler** [comment]
so geht es natürlich, ich dachte 2. Symbol von rechts muss den Baum öffnen
