### ISSUE TITLE
Iconography Suche in Kucha-Test ist fehlerhaft

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#291]
Iconography Suche in Kucha-Test ist fehlerhaft
![grafik](https://user-images.githubusercontent.com/47562310/97679605-c2779c00-1a95-11eb-8000-e16b1ba33c96.png)

Die Suche wird gestartet es kommt aber kein Ergebnis und die Lupe bleibt rot
![grafik](https://user-images.githubusercontent.com/47562310/97679788-0074c000-1a96-11eb-9d43-b1b0fe5f9d0d.png)

**Comment by OKienzler** [comment]
Auch nach dem Verlassen des paited representation Bereich und erneutem Auswählen ist die Lupe weiterhin in Suchmodus, so dass keine anderen Funktionen möglich sind

**Comment by erikradisch** [comment]
sollte wieder gehen, schua mal bitte nach

**Comment by OKienzler** [comment]
geht wieder, Dankeschön
