### ISSUE TITLE
Iconography-Zuweisung löschen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#292]
in dieser Kachel habe ich "die Dame"  versehentlich nicht im Masterbild annnotiert und als wind göttin bezeichnet. Zusätzlich habe ich absichtlich um zu testen eine falsche Zuweisung gemach "Activities":
- die Annotation wird nicht angezeigt
- rauslöschen aus dem Baum (über den linken Symbol) nicht möglich

![grafik](https://user-images.githubusercontent.com/47562310/97891954-b73f9d00-1d2f-11eb-9d0f-9e6510cb5adf.png)

**Comment by erikradisch** [comment]
Das Problem war, dass das Speichern nicht mehr richtig funktionierte. JEtzt sollte es wieder gehen.

**Comment by erikradisch** [comment]
Das geht jetzt auch wieder, oder?

**Comment by OKienzler** [comment]
es geht jetzt, Dankeschön
