### ISSUE TITLE
Annotation ist nicht gespeichert

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#293]
Die Annotation ist wurde nicht gespeichert, ob obwohl ich beim Schließen "yes" aufwählte:

![grafik](https://user-images.githubusercontent.com/47562310/97893610-caec0300-1d31-11eb-9105-681a06e32482.png)

**Comment by OKienzler** [comment]
und dieses mal im Masterbild alles durchgeführt hatte

**Comment by OKienzler** [comment]
noch ein Beispiel, dass die Annotation nicht angezeigt wird.

![grafik](https://user-images.githubusercontent.com/47562310/97899696-eb1fc000-1d39-11eb-985b-da118137550f.png)

**Comment by OKienzler** [comment]
"Alt + Klick" zum Beenden funktioniert

**Comment by erikradisch** [comment]
ja, sollte jetzt wieder gehen

**Comment by OKienzler** [comment]
ja, funktionier wieder

----- Ursprüngliche Mail -----
Von: "erikradisch" <notifications@github.com>
An: "saw-leipzig/kucha" <kucha@noreply.github.com>
CC: "OKienzler" <kienzler@saw-leipzig.de>, "Author" <author@noreply.github.com>
Gesendet: Montag, 2. November 2020 23:39:14
Betreff: Re: [saw-leipzig/kucha] Annotation ist nicht gespeichert (#293)





ja, sollte jetzt wieder gehen
