### ISSUE TITLE
image upload fehlerhaft

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#294]
Das Bild wird bereits beim Hochladen nicht angezeigt:
Bilddatei ist in Ordnung
zwei zuvor hochgeladenen Bilder werden angezeigt
s.u.
![grafik](https://user-images.githubusercontent.com/47562310/98367664-50bfc500-2036-11eb-97bd-2bae405b0ec5.png)

**Comment by erikradisch** [comment]
Ich denke mal, dass ist gerade genau das selbe Problem, was wir auch mit einigen anderen JPGs haben. Sobald Uwe wieder im Haus ist, kann ich das angehen. Das ist aber leider am 11. der Fall.

**Comment by OKienzler** [comment]
Dankeschön, das Bild wird jetzt angezeigt
