### ISSUE TITLE
Iconographie Suche in der Kachel der P&R fehlerhaft

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#295]
Iconographie Suche in der Kachel der P&R fehlerhaft, es werden nur die Begriffe gefunden die der Iconography zugeordnet sind, obwohl der ganze Baum offen ist:

![grafik](https://user-images.githubusercontent.com/47562310/99949234-f97e5c00-2d7a-11eb-8266-feed17822506.png)

**Comment by erikradisch** [comment]
In Kuchatest bitte überprüfen, es sollte wieder gehen

**Comment by OKienzler** [comment]
ja, es funktioniert wieder, Dankschön
