### ISSUE TITLE
Annotationen sind nicht mehr sichtbar

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#296]
Habe die Painted Representation in der Kucha-Arbeitsversion Montag am 30.11. angelegt und annotiert. Die Annatationen sind verschwunden und es wird auch nicht angezeigt wer wann was gemacht hatte. Es geht um Kiz 34.
![grafik](https://user-images.githubusercontent.com/47562310/101164993-2d3c6a00-3636-11eb-8611-abafe6cc7f15.png)

heute habe ich weitere Painted Representation in der Kucha-Arbeitsversion angelegt und annotiert, hier ist alles sichtbar:
![grafik](https://user-images.githubusercontent.com/47562310/101165208-886e5c80-3636-11eb-8a65-2066e1955c75.png)

**Comment by erikradisch** [comment]
hmm. Seltsam. Im Log sehe ich die Einträge auch. Kein Fehler, dass die gelöscht wurden. Das ist, glaube ich, eine gute Gelegenheit, das neueste Update heute abend einzuspielen.

Soll ich die Annotationen wieder herrstellen?

**Comment by OKienzler** [comment]
Alles wieder da, Dankeshön
