### ISSUE TITLE
Bibliographie-Suche in manchen Fällen problematisch

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#297]
Suche nach dem Autor "Samosyuk" oder "Samosiuk" funktioniert nicht, obwohl der Autor in der Bibliographie gelistet ist (Samosiuk [Samosyuk]). 
Suche funktioniert nur mit "Samo*"

Könnte das Problem in dem Alias-Namen stecken? Andere Namen, die keine alternative Schreibung haben, lassen sich ohne Sternchen problemlos suchen.

**Comment by erikradisch** [comment]
Das Problem hoer könnte sein, dass die alternative Schreibung von Samosiuk nicht im Alias ist, sondern in eckigen Klammern dahinter steht.
Hast du mal einen anderen russischen Namen?

**Comment by konczaknagel** [comment]
Du hast wohl recht. Wenn man "Oldenburg" eingibt funktioniert die Suche einwandfrei.
Hast Du eine Lösung für das Weglassen der eckigen Klammern?

**Comment by erikradisch** [comment]
Die sauberste und beste Lösung wäre die Angelsachsen endlich zu einer einheitlichen Transliteration zu bewegen. Das könnte aber schwierig werden. ;-)
Spaß beiseite.
Entweder, wir fügen es mit in den Alias ein oder machen ein neues Feld: alternative spelling.
Variante 1 wäre wohl das einfachste, aber ich bin mir gerade nicht sicher, ob wir den Alias nicht auch mit bei der Bibliographie auswerfen, dann würde dort das natürlich wiederum stören. Letztlich bleibt dann nur noch das neue Feld....
Was meinst Du?

**Comment by konczaknagel** [comment]
Wenn ein neues Feld (alternative spelling) machbar wäre, wäre ich sehr dafür. Bei Alias haben wir bisher entweder die  Originalschreibung oder wenn vorhanden ein Pseudonym eingegeben.
Danke schön!

**Comment by erikradisch** [comment]
Wir bräuchtne das ja nur für die Suche. In der bibliography bräuchte man ja sowas nicht, gel?

**Comment by konczaknagel** [comment]
Ja richtig.

**Comment by erikradisch** [comment]
Bitte mal in Kistest austewten.

**Comment by konczaknagel** [comment]
Das Speichern des Autornamen ist in Kucha-Text nicht möglich.
![grafik](https://user-images.githubusercontent.com/45167567/102227109-78356780-3ee9-11eb-8352-4fea71a5c7ad.png)

**Comment by erikradisch** [comment]
Probier noch mal.

**Comment by konczaknagel** [comment]
Neuen Eintrag anlegen und dann nach Namen suchen funktioniert. Der gefundene Datensatz lässt sich aber nicht für eine weitere Bearbeitung öffnen.

**Comment by erikradisch** [comment]
kannst du mir mal ein Beispiel geben?

**Comment by konczaknagel** [comment]
Hab es gerade noch einmal ausprobiert. Jetzt geht es.
