### ISSUE TITLE
Bibliography: Icon oder Marker anlegen für die Sichtbarkeit eines bereits hoch geladenen pdf (Artikel oder Annotationen)

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#298]

**Comment by erikradisch** [comment]
bitte mal in Kuchatest überprüfen

**Comment by konczaknagel** [comment]
Das ist so schon sehr schön, nur dass nicht klar ist, ob es sich bei der pdf um einen Artikel oder eine Annotation oder beides handelt. Mir war es auch nicht möglich, die pdf anzeigen zu lassen. In meiner Literatur-Datenbank (jabref) funktioniert es mit einem Klick auf das Icon. Wäre das hier auch möglich?

**Comment by erikradisch** [comment]
ich denke schon. Im gespräch ging es nur um die Annotation. Deswegen habe ich das andere Feld bisher ignoriert. :-)
Es gibt allerdings ein Problem. Wir haben dann 2 pdfs und nur ein Symbol. entweder, es ist dann nicht klar, ob eine Annotation oder der Artikel hochgeladen wurde, oder wir müssen uns was in der Darstellung überlegen. Hast Du da ne Idee?

**Comment by konczaknagel** [comment]
Wäre es denn technisch möglich, dass wir selbst entworfene Zeichen für die pdfs verwenden? Dann könnten wir unsere Designerin fragen, ob sie uns etwas schönes entwirft, womit wir Artikel von Annotation unterscheiden können.

**Comment by erikradisch** [comment]
klar ginge das. Wollen wir das am Montag nochmal besprechen oder schreibst Du sie direkt an? Einzig wäre darauf zu achten, dass die Symbole schön klein sind. Aber solche hat sie ja auch schon gemacht. Ich mach das dann mal fertig und füge als platzhalter erstmal gleiche Symbole ein.

**Comment by erikradisch** [comment]
Das ist ja auch erledigt, oder?

**Comment by konczaknagel** [comment]
Haben wir denn jetzt zwei unteschiedliche pdf-Icons? Also eines für die annotierte Zusammenfassung und eines für den Artikel selbst?

**Comment by konczaknagel** [comment]
Danke schön! Dann ist das auch erledigt.
