### ISSUE TITLE
Painted Representation 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#299]
Eine offene Painted Representation-Kachel schließt sich mitten im Prozess ohne Vorwarnung. Hinzugefügte und noch nicht gespeichte Einträge gehen dabei verlohren. Eine Regel, wann zu solchen Abbrüchen kommt, konnte ich nicht feststellen, es scheint willkürlich zu sein und passiert einige male, ca. 5-7 mal je 0,5 Stunde.

**Comment by erikradisch** [comment]
welche Einträge hattest Du denn da gerade hinzugefügt?

**Comment by OKienzler** [comment]
Das waren mit entry no.:
1000
1001
1002
1003

wenn mir wieder so was auffällt, werde ich Dir dann gleich schreiben

**Comment by OKienzler** [comment]
Painted Representation Entry 869 hat sich um 13:09 von alleine geschlossen

**Comment by erikradisch** [comment]
hast Du den Browser noch auf?

**Comment by erikradisch** [comment]
mach mal bitte die Konsole auf (Rechtcklick und dann Inspect) und dort auf den Console-Reiter gehen. Kannst Du davon mal einen Screenshot machen?

**Comment by OKienzler** [comment]
![Uploading grafik.png…]()

**Comment by OKienzler** [comment]
jetzt ist es bei PR 938 passiert

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/110628824-c7ff9400-81a3-11eb-8b3c-0986d9147cc5.png)

**Comment by erikradisch** [comment]
könntest Du das mal größer machen?

**Comment by OKienzler** [comment]
Wenn Du auf das Bild in Github draufklickst wird es größer

**Comment by erikradisch** [comment]
der Fehler ist nicht komplett in der Graphik enthalten. Du musst das Fenster Größer ziehen, dann passt er komplett rein.

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/110630686-faaa8c00-81a5-11eb-90fd-c6261300b383.png)

**Comment by erikradisch** [comment]
Hmm schiwerig. Ich tippe auf einen Übertragungsfehler. Passiert das beim Beenden einer Annotation?
Hast Du eine stabile Verbindung?

**Comment by OKienzler** [comment]
Ja, ich habe eine stabile Verbindung, es ist auch mal im Büro und mal im Homeoffice passiert. Und es passiert unabhängig von einer Annotation. Manchmal direkt nach dem Öffnen oder während ich eine Annotation suche.

**Comment by erikradisch** [comment]
Poste mal bitte weiter diese Fehler, damit ich eine Vorstellung bekomme, ob es immer dieser JSON-Parse ist.

**Comment by OKienzler** [comment]
Bei PR 896 bei Entfernung einer Zuweisung in einer Annotation
![grafik](https://user-images.githubusercontent.com/47562310/110633378-fb90ed00-81a8-11eb-9c74-77fd6711bc97.png)

**Comment by erikradisch** [comment]
hier gab es ja noch nicht einmal eine Fehlermeldung. Kannst du mal auf Chrome wechseln?

**Comment by OKienzler** [comment]
Nee, bin bei Firefox. Soll ich mal das nächste mal über Chrome probieren?

**Comment by erikradisch** [comment]
genau. Der Fehler ist extrem unspezifisch. Wenn wir Glück haben, geht es in Chrome stabiler. Ruf mich mal, wenn Du im Büro bist, letztlich muss ich am Besten mal in die Browser-Console direkt schauen, aber ich glaube auch das bringt nicht viel.

**Comment by OKienzler** [comment]
das Problem kam nicht mehr auf
