### ISSUE TITLE
Bibliography Wishlist

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#3]
- [x]  Die Vorschau zeigt „Title“ und „Year“ nur dann an, wenn diese im obersten Feld „English“ eingetragen wurden, nicht aber sobald „Original“ ausgefüllt wurde. Ich finde diese Trennung von „English“ und „Original“ irreführend und falsch. Bsp.: Albert Grünwedels „Alt-Buddhistische Kultstätten“ von 1912. Hier kann der Titel nur in „Original“, nicht in „English“ angelegt werden.
- [x]  Die eingetragenen Angaben zu „Journal Name“ und „Issue“ erscheinen nicht in der Vorschau. Stattdessen wird der „Publisher“ verlangt, den ich in diesem Fall eher unwichtig finde.
- [x]  den Verlag an einen Ort zu binden, ist unpraktisch, da Verlage etwas sehr fragiles sind, sie fusionieren und trennen sich wieder, sie eröffnen Dependancen und schließen diese wieder; je nachdem ändern sich die Orte…
- [x]  Ich möchte überprüfen, wie ein angelegter Titel vollständig ausgegeben wird, z.B. für eine Publikationsliste. Das heißt: Originalschrift, Transkription und Übersetzung sowie alle anderen Angaben sollen zu sehen sein. - Wie kann ich das veranlassen?

**Comment by alingnau** [comment]
like solved, check again

**Comment by konczaknagel** [comment]
Ich habe noch zwei neue Wünsche:
1. bei Editor-Type bitte "edd." statt "eds." als Beispiel einfügen
2. in die Bibliographie-Suche bei "publisher" noch "address" mit einfügen (der Ort wird sowieso mit durchsucht, da wir Verlag und Ort zusammen in eine Spalte schreiben, dann kann auch angezeigt werden, dass danach gesucht werden kann)

**Comment by alingnau** [comment]
erledigt in der nächsten Version
