### ISSUE TITLE
Ornamentik Editor (Fehler)

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#301]
- [x] ich kann nicht mehr eine neue Karteikarte für ein neuen Motiv kreieren (wenn ich auf den Knopf "add new" klicke, es passiert einfach gar nichts).
- [x] manche Ornamentik Karteikarten zeigen eine unvollständige Liste der Höhle ("Ornamentation detected in Caves"), auch wenn den entsprechenden Motiv schon annotiert wurde (z.B. Triangles.1 und Crosses.1 in Höhle 171 oder alle Motive aus Höhle 167, sowie der Motiv Festoon.2a hat eine leere Liste der Höhle, wogegen der schon ziemlich oft annotiert wurde).
- [x] während der Bearbeitung der Karteikarten kann es passieren, dass das Bild von eine Karteikarte ständig geöffnet bleibt und das Fenster der generelle Überblick der Ornamentik überlappt (Beispiel im Anhang): 
![2021 02 12](https://user-images.githubusercontent.com/45200800/107787847-f084a180-6d4f-11eb-99bb-9a985897c019.jpg)

**Comment by erikradisch** [comment]
Überprüf mal Kuchatest, sollte wieder alles gehen.

**Comment by LucaDeF** [comment]
Es sieht für Punkt 1 und 3 gut aus!! Nun ich kann Punkt 2 in Kuchatest nicht überprufen, da es in Kuchatest nur wenigen Annotationen gemacht worden sind.
