### ISSUE TITLE
Bild-Annotation: Auswahl-Baum wird manchmal nicht vollständig angezeigt

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#304]
Manchmal ist es nicht möglich, einen Begriff, den man einer Annotation zuordnen möchte, auszuwählen, weil man innerhalb des Auswahl-Baumes nicht nach unten gelangt, wie z.B. hier:
![grafik](https://user-images.githubusercontent.com/45167567/112128621-e6fc1e00-8bc6-11eb-9efb-01ac0376123d.png)

Erst nach Verkleinern des Bildes wird der Baum angezeigt und es ist möglich zu dem gewünschten Begriff zu gelangen:
![grafik](https://user-images.githubusercontent.com/45167567/112128828-1743bc80-8bc7-11eb-94b4-4ffe1bef998d.png)

**Comment by erikradisch** [comment]
die sollten jetzt in Kucha-Test ein wenig höher kommen. Schau mal bitte.

**Comment by konczaknagel** [comment]
Im Kucha-Test ist es jetzt etwas höher. Aber nach dem Speichern kam diese Nachricht:
![grafik](https://user-images.githubusercontent.com/45167567/112432739-96f59680-8d41-11eb-8d8b-b060d8f76724.png)

Ich weiß nicht, was "retray" ist.

**Comment by konczaknagel** [comment]
Nach "Yes" klicken und ca. 1 Minute später kommt die Nachricht wieder:
![grafik](https://user-images.githubusercontent.com/45167567/112432967-e76cf400-8d41-11eb-9c50-2a74f8f75f1b.png)

**Comment by erikradisch** [comment]
Probiers nochmal

**Comment by konczaknagel** [comment]
Speichern war jetzt problemlos. Jedoch nach Schließen und Öffnen des bearbeiteten Eintrages werden die Bilder nicht mehr angezeigt:
![grafik](https://user-images.githubusercontent.com/45167567/113287193-83bc6b00-92ed-11eb-9f6d-c0c2128662d6.png)

**Comment by erikradisch** [comment]
sollte jetzt in Kuchatest gehen. Bitte überprüfen.

**Comment by konczaknagel** [comment]
Scheint zu funktionieren. Danke!
