### ISSUE TITLE
entry 157 in "Painted Representations" lässt sich nicht öffnen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#305]

**Comment by erikradisch** [comment]
Das liegt daran, dass folgender Bibliographie-Eintrag gelöscht wurde, der aber noch mit der PR verbunden war:
The Kizil Grottoes in Xinjiang Uyghur Autonomous Region of China

Ich hab den jetzt mal gelöscht. Zukünftig werden dann solche einträge ignoriert.
