### ISSUE TITLE
Annotated Bibliography: Filter für Autor / Editor in Eingabemaske funktioniert nicht mehr

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#306]

**Comment by erikradisch** [comment]
Also, wenn ich dort "zin" eingebe, finde ich dort Werke von Monika. Wo siehst Du denn den Fehler?

**Comment by konczaknagel** [comment]
So sieht es bei mir aus, wenn ich "Zin" eingebe:
![grafik](https://user-images.githubusercontent.com/45167567/113482499-4992cb00-949f-11eb-8dc1-ef5c8e3b8a2c.png)

**Comment by erikradisch** [comment]
jetzt geht es wieder. Schau mal in Kuchatest

**Comment by konczaknagel** [comment]
Danke schön! In Kuchatest funktioniert's.
