### ISSUE TITLE
Image suche fehlerhaft

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#307]
Nur diese Suche *_ZXBY_V_* funktioniert nicht, ansonsten funktioniert es:
![grafik](https://user-images.githubusercontent.com/47562310/114365263-99961f80-9b7a-11eb-9842-4365ee7dc88a.png)

**Comment by OKienzler** [comment]
bzw. wenn ich so *_ZXBY* suche, dann kann ich nur 300 von 1619 sehen

![grafik](https://user-images.githubusercontent.com/47562310/114365581-e4b03280-9b7a-11eb-938f-31423a521a47.png)

**Comment by erikradisch** [comment]
Da der Server auch abgestürzt war, denke ich, dass Du nur den Cantaloupe durch neue Bildabfragen überfordert hast und dann der Server eine Zeitlang überfordert war. Habe den Cantaloupe neu gestartet und schon 500 Bilder anzeigen lassen. Ich empfehle Warten, wenn die Bilder ein wenig länger dauern. Wenn Du direkt noch einmal 100 Bilder lädtst, befor die anderen Bilder geladen sind, kann es passieren, dass der Cantaloupe überfordert ist.

**Comment by erikradisch** [comment]
geht es bei Dir jetzt auch?
