### ISSUE TITLE
Annotated Bibliography: Möglichkeit für die Eingabe von "et al." für Autoren und Editoren schaffen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#308]

**Comment by erikradisch** [comment]
kannst Du es mal in Kuchatest ausprobieren?

**Comment by konczaknagel** [comment]
Der Eintrag wird nach dem Speichern korrekt angezeigt. Ist aber dann über die Suche nicht zu finden, außer über die Jahreszahlen-Suche. Die andere Suche scheint sich aufzuhängen.

**Comment by erikradisch** [comment]
hast Du mal ein Beispiel? Bei mir ging es, aber ich habe in meiner lokalen Datenbank auch einfach nur das Häckchen in einem bestehenden Titel gesetzt.

**Comment by konczaknagel** [comment]
Danke! Es funktioniert jetzt.
