### ISSUE TITLE
Painted Representation: Löschen einer (doppelten) Painted Representation nicht möglich

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#309]
Habe versucht, entry 12 zu löschen (mehrfach) weil diese Painted Representation noch einmal angelegt wurde (entry 1005) war jedoch erfolglos.

**Comment by erikradisch** [comment]
der ist doch gelöscht?

**Comment by konczaknagel** [comment]
Bei mir ist er noch vorhanden:
![grafik](https://user-images.githubusercontent.com/45167567/115871869-65a3df80-a441-11eb-9cdf-bcea3bdd3392.png)

**Comment by erikradisch** [comment]
Ach? wir reden über die Testversion?

**Comment by erikradisch** [comment]
da ging er jetzt aber auch ohne Probleme zu löschen.

**Comment by konczaknagel** [comment]
Mein Fehler. Der Eintrag ist gelöscht.
