### ISSUE TITLE
Text Felder in "Ideal Typical Pictures"

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#310]
Mit dem Mouse kann man nur den Feld auswählen aber nicht damit interagieren (z.B es ist nicht möglich den Text mit dem Mouse zu markieren sowie es ist nicht Möglich den gewünschte Punkt des Texts zu klicken).

**Comment by erikradisch** [comment]
welches Feld denn?

**Comment by LucaDeF** [comment]
Alle Textfelder: "Ornament Code"; "Type Description" und "General Remarks"

**Comment by erikradisch** [comment]
sehr seltsam. Bei mir geht alles. Nur steht der Coursor immer am anfang des Textfeldes.

**Comment by LucaDeF** [comment]
Ja das schon. Man kann aber mit dem Mouse den Feld auswählen, dann kriegt man den Cursor am Anfang des Feldes und kann den Cursor nur mit der Tastatur bewegen. D.h. kann man nicht mit dem Mouse ein Wort oder ein bestimmtes Punkt wählen. Z.B. kann man nicht den Text kopieren oder ein bestimmtes Wort anklicken. 
Ich kann eigentlich damit arbeiten, aber ich habe gesehen dass es in anderen "Abteilung" ganz normal funktioniert. Außerdem werden andere Leute bestimmt Bald auch damit arbeiten wollen.

**Comment by erikradisch** [comment]
Mit Strg (Ctrl) + a schon.

**Comment by LucaDeF** [comment]
Das funktioniert aber nur für den ganzen Text oder?
Jedenfalls ist es für mich kein großes Problem. Wichtig ist, dass Du es weißt.

**Comment by erikradisch** [comment]
Das geht über shift und die pfeiltasten. Ich schließe das mal, OK? Ich habe es mir mal angeschaut und auf die Schnelle keinen Unterschied festgestellt. Ich würde es aber auch nicht als großes Problem einstufen.
