### ISSUE TITLE
Image-Pool: Bilder hochladen nicht möglich

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#311]
Es kommt die Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/45167567/114563137-6e412c80-9c6f-11eb-9922-94b6efa865ed.png)

**Comment by erikradisch** [comment]
ging das nach einem zweiten mal? Wie heißt das Bild?

**Comment by konczaknagel** [comment]
War jetzt drei Mal in der Datenbank. :-)
