### ISSUE TITLE
Typical Image-Editor

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#312]
Typical Image-Editor: Annotation hat funktioniert, beim Schließen mit "Shift + Enter" kommt kein Fenster mit der Abfrage bezüglich des Speichert, Kachel wurde einfach nur geschlossen und die Annotation gespeichert.

Das Fenster mit der Abfrage kommt, wenn man die Kachel über "X" schließt

Allgemein, ohne dass man sich in einem beschreibbarem Feld befindet kann man nicht mit "Shift + Enter" rausgehen.

**Comment by erikradisch** [comment]
ich habe jetzt eine Warnung eingebuat. Warum es nicht außerhalb der Felder geht, erschließt sich mir nicht. Ich fürchte, dass liegt an dem zugrundeliegenden schlechten Code von Nina. Ich behalte es mal im Hinterkopf, eventuell fällt mir mal was auf, aber das Ussue würde ich schließen, da es ja grundsätzlich geht.
