### ISSUE TITLE
Fehlermeldung beim Speichern in der Arbeitsversion

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#313]
Kucha-Arbeitsversion: Eine Fehlermeldung ist beim Speichern aufgetreten und kommt immer wieder obwohl man "ja" ausgewählt hat. Sie kommt auch wenn die Kachel geschlossen ist (Bils 2)
Bild 1
![grafik](https://user-images.githubusercontent.com/47562310/115865342-77cd5000-a438-11eb-9d74-c4d2345c17d4.png)

Bild 2
![grafik](https://user-images.githubusercontent.com/47562310/115865506-b4994700-a438-11eb-9cf6-cda6acc373bf.png)

**Comment by erikradisch** [comment]
Danke für den Hinweis, ist behoben.
