### ISSUE TITLE
Seitenzahlen in der Bibliography einer Painted Representation ändern 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#314]
Wie kann man Seitenzahlen nachträglich in der Bibliography einer Painted Representation ändern? Ich glaube früher war es möglich und jetzt geht es nicht mehr

![grafik](https://user-images.githubusercontent.com/47562310/122044464-d54ca000-cddc-11eb-8966-43ccf9ca5f16.png)

**Comment by erikradisch** [comment]
Geht das nicht, indem man einfach mal den Hacken wegmacht und gleich wieder setzt?

**Comment by OKienzler** [comment]
doch, aber dann verschwindet alles und man muss alles wieder neu eintragen. Es wäre gut wenn man das Eingetragene ergänzen kann und nicht alles wieder neu schreiben. Früher konnte man den Eintrag anklicken und sehen & verändern was drin steht

**Comment by OKienzler** [comment]
Super!!! Lieben Dank funktioniert sehr gut
