### ISSUE TITLE
Ideal Typical Pictures Fehler

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#315]
- [x] Es ist nicht möglich eine neue Karteikarte in "Ideal Typical Pictures" zu erschaffen. Wenn man auf den Knopf + druckt, passiert es einfach nichts. 
- [x] Es ist nicht möglich die Eingabe in der Baumstruktur zu ändern. 
- [x] Es ist nicht möglich mit dem Mouse mit den Textfelder zu interagieren (bestimmten Wörter auswählen; ein Teil des Texts markieren usw.).
- [x] Einigen annotierten Ornamenten zeigen die Liste der Höhle in dem Feld "Ornamentation detected in caves" leer. 
- [x] Ornamenten mit vielen Annotationen zeigen nicht alle Höhle in dem Feld "Ornamentation detected in caves" (z.B. Festoon.D, ID 88).

**Comment by erikradisch** [comment]
Kannst Du in kuchatest.saw-leipzig noch einmal überprüfen, ob das Setzen der Baumstruktur jetzt wieder geht? Ich habe das ein wenig umorganisiert.

**Comment by LucaDeF** [comment]
Soviel ich sehen kann, scheint es zu funktionieren!!!

**Comment by erikradisch** [comment]
den letzten Punkt habe ich jetzt auch gelöst. Kannst es in der Testversion überprüfen.

**Comment by LucaDeF** [comment]
Bei mir funktioniert noch nicht. Ich kann immer noch nicht mit dem mouse ein Text markieren usw.
Ich habe es versucht, auch nachdem ich den Cache geleert habe.

**Comment by erikradisch** [comment]
in Kuchatest?

**Comment by LucaDeF** [comment]
Ja, genau!

**Comment by erikradisch** [comment]
geht es bei Dir auch in Chrome, in Firefox jedoch nicht?

**Comment by LucaDeF** [comment]
Bei Firefox funktioniert immer noch nicht. Ich habe aber gerade Chrome kontrolliert und da scheint es zu funktionieren!!
