### ISSUE TITLE
Bildannotation wird bei mehreren Polygonen nicht gespeichert

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#316]
Folgende Fehlermeldung erscheint:
![grafik](https://user-images.githubusercontent.com/45167567/123900827-165ebb80-d96a-11eb-8e71-b198d29fac7b.png)

**Comment by erikradisch** [comment]
Das ist die Fehlermeldung, die kommt, wenn Du einige Punkte so dicht gesetzt hast, dass linien als identisch gelten. In diesen Fällen musst Du das Polygon überprüfen und schauen, ob Du den fehler siehst.

Am 30. Juni 2021 06:12:18 MESZ schrieb konczaknagel ***@***.***>:
>Folgende Fehlermeldung erscheint:
>![grafik](https://user-images.githubusercontent.com/45167567/123900827-165ebb80-d96a-11eb-8e71-b198d29fac7b.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/saw-leipzig/kucha/issues/316

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by konczaknagel** [comment]
In Ordnung. Danke!
