### ISSUE TITLE
Ideal Typical Picture

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#318]
Es scheint immer noch das alte aus ID 181 gelöschte Bild mit dem Eintrag im Buam verküpft zu sein. 

![grafik](https://user-images.githubusercontent.com/47562310/125070450-415ab500-e0b8-11eb-9d48-f8dc935dde83.png)

**Comment by erikradisch** [comment]
jetzt aber!

**Comment by OKienzler** [comment]
Ich sehe immer noch das alte und die neue Annotation (auf dem neuen Bild s.o. rechtes Bild) ist jetzt auch weg
![grafik](https://user-images.githubusercontent.com/47562310/125074631-d3b18780-e0bd-11eb-9a1b-b53369172204.png)

**Comment by erikradisch** [comment]
Es ging doch nur im die annotation, oder? Das Bild kannst du selbst rauslöschen.

**Comment by OKienzler** [comment]
Es gibt 2 Bilder

ID 26808 mit Annotation - habe ich gelöscht, aber die Annotation bestand noch, deshalb bat ich Dich dieses Bild bzw. Annotation auf dem Bild zu löschen

danach habe ichdas Bild mit ID 27510 hochgeladen und annotiert. Es war jetzt dann alles ok, nur angezeigt im Baum wurde immer noch das alte Bild mit ID 26808

jetzt ist in ITP ID 181 das richtige Bild ID 27510 aber die Annotation (also neue) ist nicht mehr sichtbar

**Comment by erikradisch** [comment]
Achsoooo. Da hatte ich Dich falsch verstanden. Du musst das neue Bild noch zum MasterImage deklarieren, dann verschwindet auch das alte.

**Comment by erikradisch** [comment]
Annotation ist wieder hergestellt

**Comment by OKienzler** [comment]
Dankeschön, jetzt passt alles :)
