### ISSUE TITLE
check in all modules which fields are not open accessible 

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#32]

**Comment by konczaknagel** [comment]
diesen Punkt muss ich im Projekt besprechen

**Comment by alingnau** [comment]
Ich habe es jetzt erst einmal so gelöst, dass Caves, Painted Representations und Images komplett nicht angezeigt werden. Dabei gelten die Beschränkungen private nur für FULL member und Admin, copyright für associated, full und Admin und public für alle.
