### ISSUE TITLE
ITP markieren und suchen im Baum

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#321]
- wäre es möglich eine Suchfunktion in Baum-Bereich einzufügen?
- Markieren / Einfügen / kopieren in den freien Textbereichen geht leider noch nicht
![grafik](https://user-images.githubusercontent.com/47562310/125079958-81c03000-e0c4-11eb-8ec9-46098a851ba4.png)

**Comment by erikradisch** [comment]
ist in der Testversion jetzt beides realisiert. Bitte überprüfen

**Comment by OKienzler** [comment]
Suchfunktion funktioniert sehr gut, Dankeschön

**Comment by OKienzler** [comment]
Markieren / kopieren / mit der Maus in den Text klicken - in dem freien Textbereichen geht leider noch nicht

**Comment by erikradisch** [comment]
Probier das Mal bitte mit Chrome aus.

Am 19. Juli 2021 15:57:49 MESZ schrieb OKienzler ***@***.***>:
>Markieren / kopieren / mit der Maus in den Text klicken - in dem freien
>Textbereichen geht leider noch nicht
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/saw-leipzig/kucha/issues/321#issuecomment-882569990

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by OKienzler** [comment]
Mit Chrome funktioniert alles sehr gut, 
nur nicht mit firefox

**Comment by erikradisch** [comment]
ich fürchte, damit müssen wir jetzt leben. Das Framework wird ja nicht mehr weiterentwickelt...
