### ISSUE TITLE
Paited Representation Annotation speichern nicht möglich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#322]
Heute zum zweiten mal passiert und in der Vergangenheit auch schon - Speichern der Annotation ist nicht möglich s. Mail (konnte screen nicht hierher kopieren) ID 162 um 1m 13.07.2021 um 18:27 (falls die Uhrzeit zum Nachschauen hilft :)

Die Annotationen gingen verloren und man musste von vorne beginnen (schmerzhaft)

**Comment by erikradisch** [comment]
Die Annotation war nicht mehr da und abklickbar? In solchen Fällen soll man ja die Annotation nach problematischen Stellen absuchen.

**Comment by OKienzler** [comment]
Vielen Dank für die Rückmeldung, werde in der Zukunft überprüfen, wenn so eine Meldung kommt.
