### ISSUE TITLE
Einträge in der Ornamentik Baumstruktur eliminieren

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#323]
Es gibt vier Einträge der Baumstruktur unter Decorations & Ornaments/Phytomorphic Motifs/Running Scroll die jetzt als "delete" bezeichnet sind und die zu eliminieren sind. Ich habe schon kontrolliert und jetzt existiert keine Annotation die mit diesen Einträge gespeichert ist.

**Comment by erikradisch** [comment]
Ist erledigt, oder?

**Comment by LucaDeF** [comment]
Ja!!
