### ISSUE TITLE
Annotation ITP ID 181

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#325]
nachdem Beenden und Speichern einer Annotation, wurde die Annotation nachträglich korrigiert. Nachträgliches und Urspungliches überlappt sich, wenn ich es richtig sehe:

![grafik](https://user-images.githubusercontent.com/47562310/127618028-3f05a9cc-acff-4399-b146-836bc0ef8cd9.png)

**Comment by erikradisch** [comment]
das hatten wir ja geklärt.
