### ISSUE TITLE
ITP ID 181 Annotation wird nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#326]
die eben gemachte neue Annotation ist nicht sichtbar, obwohl andere Elemente sichtbar sind (Bild 1)
wenn Annotationen "sichtbar machen" eingeschaltet ist, dann wird auch die neue Annotation sichtbar und auswählbar (Bild 2)

Bild 1
![grafik](https://user-images.githubusercontent.com/47562310/127897974-a9e5fcf6-8419-44e4-95a5-4dcf84937e8d.png)

Bild 2
![grafik](https://user-images.githubusercontent.com/47562310/127898493-6d8cadb0-2c73-4ffc-8288-8fb66f57db88.png)

**Comment by erikradisch** [comment]
ist behoben. Schaus Dir mal in Kuchatest an.

**Comment by OKienzler** [comment]
Dankeschön, jetzt sieht man alles
