### ISSUE TITLE
Auswahlmöglichkeit aus Baumstruktur löschen

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#327]
Auswahlmöglichkeit aus Baumstruktur löschen:

Decoration&Ornaments/Geometric Motifs/Oval and Pearl/delete

Ich habe schon kontrolliert dass keine existierende Annotation mit dieser Auswahlmöglichkeit gespeichert wurde.

**Comment by erikradisch** [comment]
erledigt
