### ISSUE TITLE
Fehlermeldung bei ID-Suche in Painted Representation einfügen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#329]
Bitte in Painted Representations bei "Image Filter": ID eine Fehlermeldung ausgeben, falls hier aus Versehen nach anderem gesucht wird, wie Kurztitel, wie : no such ID

Vielen Dank!

**Comment by erikradisch** [comment]
Ist erledigt. In Kuchatest bitte mal überprüfen. Wenn Du direkt enter drückst funktioniert es am besten, wenn Du eine Eingabe machst und direkt die suchlupe drückst, wird jetzt der Eintrag gelöscht, leider aber eine Suche initiiert. Eine Fehlermeldung kommt aber auch.

**Comment by konczaknagel** [comment]
Dumme Frage: Liegt Kuchatest jetzt woanders? Unter meinem alten Link https://kuchatest.saw-leipzig.de/kis/ wird nur sehr wenig angezeigt:
![grafik](https://user-images.githubusercontent.com/45167567/131632059-7e5f34e1-70e5-43f5-8223-973dbca4771a.png)

**Comment by erikradisch** [comment]
danke für den Hinweis, da Kuchatest jetzt eine andere URL hat, muss ich diese jedes mal im System ändern, wenn ich eine Version für kuchatest fertig mache. Beim letzten mal ging es mir durch die Lappen. jetzt sieht es wieder gut aus.

**Comment by erikradisch** [comment]
ist das eledigt?

**Comment by konczaknagel** [comment]
Ist erledigt. Danke!
