### ISSUE TITLE
ITP: Speichern von Sätzen nicht möglich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#330]
Im "ideal typical picture" speichern mehrere Sätze nicht möglich. Wenn man nur ein Wort eingibt, wird es jedoch gespeichert:

![grafik](https://user-images.githubusercontent.com/47562310/131126966-781ab77a-4cdc-4b8f-a684-f80c10b209a8.png)

**Comment by erikradisch** [comment]
sollte jetzt gehen.

**Comment by OKienzler** [comment]
Ja, Dankeschön, hat gespeichert
