### ISSUE TITLE
Speichern in PR nicht möglich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#331]
Speichern in PR, Inscription nicht möglich (Fang hat mir davon berichtet)

![grafik](https://user-images.githubusercontent.com/47562310/131356227-9412cf63-f6f9-4a86-a225-371c2cfc2262.png)

**Comment by erikradisch** [comment]
bei mir geht's. Selbst nach neu laden steht ein Test-Wort in dem Inscription-Memo... Was genau sollte denn reingeschrieben werden?

**Comment by erikradisch** [comment]
Aaahh. Es war zu lang. Fehler behoben. Ich schreibe Fang gleich mal.

**Comment by OKienzler** [comment]
﻿Dankeschön und sorry, man sollte alle Mails lesen bevor man antwortet :)

Von meinem iPhone gesendet



Von meinem iPhone gesendet
