### ISSUE TITLE
PR doppelter Eintrag

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#336]
Nach dem Anlegen einer Kachel ID 1687, ist ihr Duplikat ID 1688 automatisch erschienen, das ist heute zum zweiten Mal passiert. Beim ersten mal waren es ID 1678 und 1679 die gleich waren, woraufhin ich 1679 neu zugeordnet habe, aber die Erstellzeit müsste absolutt identisch sein.

![grafik](https://user-images.githubusercontent.com/47562310/141519857-380cfeda-c40d-4d5c-befb-e5f3401fe130.png)

**Comment by OKienzler** [comment]
wieder ein Duplikat ID 1779 und 1780:
![grafik](https://user-images.githubusercontent.com/47562310/154694175-6ae1874f-d5c1-4fd0-bf0d-c006d79b1725.png)

**Comment by erikradisch** [comment]
Das tritt jetzt nocht mehr auf, oder?

**Comment by OKienzler** [comment]
ist nicht mehr aufgetreten
