### ISSUE TITLE
Speichern der Position in PR nicht möglich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#340]
![grafik](https://user-images.githubusercontent.com/47562310/148544852-797e713e-076f-4d41-a1db-0ddd92f98215.png)

**Comment by erikradisch** [comment]
im Bild hast Du das Häckchen bei er Wall nicht gesetzt. Dann geht es auch nicht, die Position zu setzen. Ist das eventuell das Problem?

**Comment by OKienzler** [comment]
Dankeschön, das war offensichtlich das problem, in anderen Fällen hat es ja geklappt (da habe ich wahrscheinlich ohne nachzudenken ein Häkchen automatisch gesetzt :)
