### ISSUE TITLE
PR Bilder aus image pool werden nicht geladen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#341]
PR Bilder aus image pool werden nicht geladen bzw. oft ist es extrem langsam
![grafik](https://user-images.githubusercontent.com/47562310/148818723-476f58dd-6df4-49e7-a233-5af17ecb2321.png)

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/148818997-0cab3a4c-b61c-4880-a971-97e71694efb1.png)

**Comment by erikradisch** [comment]
das geht wieder, oder?

**Comment by OKienzler** [comment]
im Moment geht es wieder ganz gut
