### ISSUE TITLE
Painted Representation/Basics/Located in Cave: Auswahlmöglichkeit "unknown" hinzufügen

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#343]
unter der Liste der Höhle eine Auswahlmöglichkeit "unknown" hinzufügen

**Comment by erikradisch** [comment]
Ging es da nicht darum, unknown im Frontend erscheinen zu lassen, wenn kein Cave zugewiesen wurde?

**Comment by erikradisch** [comment]
So! hat lang genug gedauert. Du solltest es jetzt eigentlich einstellen können und es sollte nach einem Neustart auch schön angezeigt werden. Hast Du eventuell eine veröffentlichte Painted Representation, wo Du das einstellen willst? Wenn ja, tu das doch bitte gleich mal. Ich muss nämlich die Darstellung für das Frontend entsprechend anpassen und bräuchte dafür dringend einen Testfall.

**Comment by LucaDeF** [comment]
Lieber Erik,

ich habe den veröffentlichen Painted Representation mit ID 1580 mit
"unknown" cave gesetzt. Bitte sag mal wenn Du fertig bist, weil ich muss
sie unbedingt zurück zum cave 167 setzen!!!

viele Grüße,
Luca

Il giorno mer 17 ago 2022 alle ore 17:30 Luca De Fabritiis <
***@***.***> ha scritto:

**Comment by erikradisch** [comment]
So! Fertig! Schau's Dir mal an. Wenn es OK is, kannst Du es zurücksetzen und diesen Issue schließen.

**Comment by LucaDeF** [comment]
Lieber Erik,

Ich kontrolliere sobald meinen Rechner zurück in der Modernität kehrt und
ich wieder ein schnelle Internet Verbindung bekomme (heute kriege ich nicht
mal die Seite geladen)!!

Luca




Il Gio 18 Ago 2022, 15:21 erikradisch ***@***.***> ha scritto:

**Comment by LucaDeF** [comment]
Gut, mir scheint alles in Ordnung zu sein!!
