### ISSUE TITLE
Painted Representation - Bäumchen beim Annotieren "zuklappen" 

### ISSUE THREAD

**Issue by DomKlimaszewski** [saw-leipzig/kucha#344]

**Comment by erikradisch** [comment]
schau mal rein. sollte jetzt funktionieren

**Comment by DomKlimaszewski** [comment]
Man kann es zuklappen, aber dann nicht wieder aufklappen. Oben rechts erscheint "blubb" im schwarzen Fenster

**Comment by DomKlimaszewski** [comment]
aaahaaa! okay, das kann man manuel dann machen. Ist gut. Supi, danke dir :)
