### ISSUE TITLE
Painted Representation: Infos der Bildern fehlt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#346]
Painted Representation: Infos der Bildern fehlt und man kann die Bilder nicht markiteren um die z.B. auf "Favorit" zu ändern:

![grafik](https://user-images.githubusercontent.com/47562310/160091710-21095fd7-054e-48ac-903d-e64770182402.png)

**Comment by erikradisch** [comment]
fixed

**Comment by OKienzler** [comment]
Dankeschön
