### ISSUE TITLE
Ideal Typical Picture: die Zuordnung aus dem Bäumchen verloren gegangen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#347]
![grafik](https://user-images.githubusercontent.com/47562310/160092493-39514a75-70d8-4c30-ab54-1cce284953c3.png)

**Comment by OKienzler** [comment]
Es lässt sich keine neue Zuordnung auswählen:
![grafik](https://user-images.githubusercontent.com/47562310/160093282-6e0322af-495a-4390-bd21-ae170d4f7a2d.png)

**Comment by erikradisch** [comment]
Naja, lies doch mal die Fehlermeldung. Die sagt Dir, dass dieses Element bereits zugewiesen wurde und bietet Dir an, das entsprechende Ideal Tpyische Element zu öffnen. Stimmtst Du dem Zu, wir das Element mit der nächst höheren ID geöffnet. Da muss also was beim Speichern schief gegangen sein.

**Comment by OKienzler** [comment]
Genau das habe ich auch gemacht (gelesen und zugestimmt!)

**Comment by OKienzler** [comment]
Warum da wieder zwei gleichzeitig angelegt wurden ist wieder die Frage, die wir im Auge behalten sollen

**Comment by erikradisch** [comment]
Dann öffnet sich ein anderes Element mit der nächst höheren ID. 

Am 25. März 2022 11:25:45 MEZ schrieb OKienzler ***@***.***>:
>Genau das habe ich auch gemacht (gelesen und zugestimmt!) 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/saw-leipzig/kucha/issues/347#issuecomment-1078878493
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
