### ISSUE TITLE
ITP: doppelter Eintrag

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#349]
ITP ID 249 und 250 wurden gleichzeitig angelegt, beim schließen über X (nicht mit der Tastenkombination):
![grafik](https://user-images.githubusercontent.com/47562310/161591747-602a1c35-553b-4c3d-a465-aa989fb426c4.png)

**Comment by OKienzler** [comment]
![grafik](https://user-images.githubusercontent.com/47562310/179520363-128776c0-2785-4d25-b5ef-4a163b7830fe.png)

Es ist wieder passiert, werde aber gleich TP ID 258 löschen

**Comment by erikradisch** [comment]
Ich habe jetzt eine Sicherung eingebaut, die eigentlich eine doppelte Speicherung ausschließen sollte. Wir behalten es im Auge.

**Comment by erikradisch** [comment]
hat sich das jetzt geklärt?

**Comment by OKienzler** [comment]
wieder dopperlter Eintrag, gerade eben frisch angelegt ITP 285 und 286 (dieses lösche ich gleich, weil ich weiterarbeiten muss):
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/2f7bf3dc-46d8-4f05-8f87-a0630798c008)

**Comment by erikradisch** [comment]
Wahrscheinlich steht das damit nicht in zusammenhang aber es gab eine Fehlermeldung, dass ein Bibliographischer Eintrag zulang war. Ich habe die Länge mal hochgestellt und manuell eingefügt. schau mal, ob das passt.
Hast Du abgepeichert und bist dann rausgegangen, indem Du das X gedrückt und den Dialog mit Enter beendet hast?
