### ISSUE TITLE
Türdurchgänge

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#35]
* [x]  reveal (left/right) 
* [ ]  oberer Teil in verschieden Varianten einteilen (analog zu Deckentypen)

**Comment by konczaknagel** [comment]
Verschiedene reveal-Typen mit in die Liste (wall selector) aufnehmen:
- antechamber entry reveal left
- antechamber entry reveal right
- antechamber entry reveal top
- main chamber entry reveal left
- main chamber entry reveal right
- main chamber entry reveal top
- rear area left corridor entry reveal left
- rear area left corridor entry reveal right
- rear area left corridor entry reveal top
- rear area left entry reveal left
- rear area left entry reveal right
- rear area left entry reveal top
- rear area right corridor entry reveal left
- rear area right corridor entry reveal right
- rear area right corridor entry reveal top
- rear area right entry reveal left
- rear area right entry reveal right
- rear area right entry reveal top

**Comment by konczaknagel** [comment]
Bitte aus der Liste löschen:
- rear area left wall
- rear area right wall

**Comment by alingnau** [comment]
wirksam mit dem nächsten update
