### ISSUE TITLE
Image Pool: image wird nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#353]
image ID 10152 wird nicht angezeigt:

![grafik](https://user-images.githubusercontent.com/47562310/170724541-561e2629-d0e3-4460-af05-cb3051cad096.png)

**Comment by erikradisch** [comment]
Das hat sich mit dem Workaround geklärt, oder?

**Comment by OKienzler** [comment]
DAs scheint nicht mehr vorzukommen
