### ISSUE TITLE
Upload neuer Bilder in image pool ist nicht möglich

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#354]
Upload neuer Bilder in image pool ist nicht möglich:

![grafik](https://user-images.githubusercontent.com/47562310/170978309-ebcf50f9-1a25-497c-98a4-63b633d8688f.png)

**Comment by erikradisch** [comment]
sollte wieder gehen!

**Comment by OKienzler** [comment]
Es geht wieder, vielen Dank!
