### ISSUE TITLE
Painted Representation: Angaben in der Bibliographie werden nicht gespeichert

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#355]
ist schon einige Male vorgekommen. Jetzt aktuell bei neuerstellten Kachel ID 1871:
![grafik](https://user-images.githubusercontent.com/47562310/171867172-44b1ced4-7d45-4251-83f9-30a65ad11c63.png)

**Comment by OKienzler** [comment]
manchmal kommt so eine Meldung:
![grafik](https://user-images.githubusercontent.com/47562310/171903435-07469940-1b7e-4bd3-98e1-6fae827d3701.png)

**Comment by OKienzler** [comment]
Die Bibligraphie-angaben lassen sich weiterhin nicht speichern. Siehe neuerstellte PR 1876, es waren folgegende Angaben:
pp. 53–55
pp. 114-117, 149-150

**Comment by OKienzler** [comment]
Die Bibligraphie-angaben lassen sich weiterhin nicht speichern siehe PR 1877 und 1878
![grafik](https://user-images.githubusercontent.com/47562310/173022092-1ccda3ff-f720-4915-8bba-a3ceea9290b8.png)

**Comment by erikradisch** [comment]
bei welchen Bibliography-Einträgen sollten die Seitenzahlen denn rein? Damit ich es mal versuchen kann, zu reproduzieren.

**Comment by OKienzler** [comment]
PR 1879, eben erstellt und zuerst ohne Bilder und Bibliographie gespeichert, danach erneut geöffnet und mit Bib + Bildern bestückt. Die Angaben wurden auf diese Weise übernommen und gespeichert.

**Comment by OKienzler** [comment]
in 1877:
Kezi’er shiku neirong zonglu 2000, pp. 92–95
Zin 2020, pp. 114-117, 168-171

**Comment by erikradisch** [comment]
Die erste bibliographische Anmerkung ging ohne Probleme zu speichern. Bei der zweiten bin ich unsicher, welche gemeint ist? Monika hat 2020 mehrere Titel

**Comment by OKienzler** [comment]
Zin 2020 Parinirvana - speichern nachträglich hat bei mir jetzt auch funktioniert, aber es funktioniert nicht immer, ich versuche jetzt wie auf dem Wege: und zuerst ohne Bilder und Bibliographie speichern, danach erneut öffnen und mit Bib + Bildern bestückten. So hat es gerade einmal funktioniert

**Comment by OKienzler** [comment]
Die Bib Angaben aus 1879 sind wieder verschwunden, vorausschauend habe ich mir diese vorsichtshalber schon "rausgeschrieben" es waren diese:
Kizil Grottoes 1983–1985/1989–1997, vol. 2, pl. 104
According to Chongfeng Li (2012, p. 61) stūpas with relics inside
Kezi’er shiku neirong zonglu 2000, pp. 136–137
Zin 2020, pp. 114-117, 177-178

**Comment by OKienzler** [comment]
PR 1881 eben erstellt die Bib-Angabe pp. 114-117, 197-198 (Zin 2020, parinirvana) wurde nicht gespeichert

**Comment by erikradisch** [comment]
1881 zu setzen ging bei mir ohne die geringsten probleme... Es ist doch auch bei Dir im System?

**Comment by erikradisch** [comment]
Ich habe mal ein paar logs zur Überprüfung eingebaut. Sag bescheid, wenn es wieder passiert.

**Comment by erikradisch** [comment]
funktioniert das jetzt?

**Comment by OKienzler** [comment]
das geht jetzt, Dankeschön.

**Comment by erikradisch** [comment]
Ja, gerne. Wenn wir den Fehler reproduzieren könnten, wäre das eine große Hilfe.
