### ISSUE TITLE
Painted Representation: Fehlermeldung beim Speichern

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#357]
diese Fehlermeldung kommt zur Zeit oft (nicht immer) beim Speichern einer Änderung. Nach dem Klicken auf "yes", verschwindet die Fehlermeldung kurz und erscheind dann wieder, und so wiederholt es sich bis man die Seite erneuert. Die Änderung ist aber tatsächlich gespeichert worden:
![grafik](https://user-images.githubusercontent.com/47562310/172327926-e05bb605-ab9d-4b04-80a2-10bdcf88b984.png)

**Comment by erikradisch** [comment]
Dumme Frage: Kann es sein, dass Du die PRs veröffentlichen wolltest? Also auf public gesetzt hattest? Der Fehler scheint nämlich damit zusammenzuhängen, dass versucht wird, eine Version im Frontend upzudaten, was aber in einen Fehler läuft, da es noch keine Version gibt. 
Da diese PRs alle bei mir privat angezeigt werden, gehe ich davon aus, dass Du sie erstmals veröffentlichen wolltest? Das würde den Fehler erklären.

**Comment by OKienzler** [comment]
die Fehlermeldung kam auch bei bereits veröffentlichten PR, z.B. PR 225, war auch schon lange angelegt worden und auch ein anderes mal auf "public" gesetzt worden, zwar erst kürzlich, aber nicht am Dienstag (07.06.) als die Fehlermeldung wieder kam.

**Comment by erikradisch** [comment]
kommt das noch? Das sollte sich eigentlich jetzt erledigt haben.

**Comment by OKienzler** [comment]
Die Meldung kommt nicht mehr, Dankeschön.
