### ISSUE TITLE
Painted Representation: unter ID 27 wird angezeigt, dass es Bildannotationen gibt, das Bild mit den Annotationen wird aber nicht angezeigt

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#358]

**Comment by erikradisch** [comment]
Weil jemand das Bild gelöscht hat, ohne vorher zu prüfen, ob darauf Annotationen existieren. Hmm. Da sollten wir vielleicht doch mal eine Prüfung einbauen. Jedenfalls geht es um folgendes Bild:
Kizil008_CeilingRi_Reg07_No05_drawing_MengYu
Soll ich das wiederherstellen?

**Comment by konczaknagel** [comment]
Ja, es wäre schön, wenn Du die Zeichnung wieder herstellen könntest. Sie müsste von Monika sein (ist definitiv nicht von Meng Yu). Ich frage Monika mal.

**Comment by erikradisch** [comment]
So. erledigt. Die einzigen beide Modifikationen des Bildes stammen übrigens von dir. Im März. Hast Du es gelöscht?

**Comment by konczaknagel** [comment]
Ich hatte das Bild gelöscht, da alle Meng Yu-Zeichnungen irrtümlich hoch geladen wurden. Bei dieser Zeichnung schaue ich, ob ich von Monika eine ordentliche Zeichnung bekomme.
Letztlich wäre es aber schön, wenn die Annotationen zusammen mit den Bildern gelöscht werden und nicht weiter so tun, als seien sie da.
