### ISSUE TITLE
Painted Representation: Löschen einer PR nicht möglich

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#359]
Habe z.B. ID 1005 schon mehrmals gelöscht, aber nach erneutem Laden ist sie wieder da.

**Comment by erikradisch** [comment]
Meinst Du im Backend? also kucha.saw-leipzig.de? Dort ist er nämlich gelöscht. wo kommt er denn wieder?

**Comment by konczaknagel** [comment]
Wenn ich in der Ikonography nach "Vyaghri" suche, wird es immer noch angezeigt:
![grafik](https://user-images.githubusercontent.com/45167567/172646698-5f341533-b57a-4f30-89fb-cdadb9bd7ac4.png)

**Comment by erikradisch** [comment]
sollte jetzt ok sein

**Comment by konczaknagel** [comment]
Ist okay. Danke!
