### ISSUE TITLE
Painted Representations: "Iconography Selector" in "Iconography Search" funktioniert nicht mehr

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#360]
Bei der Auswahl von "Iconography Search" erscheint der "Iconography Selector" doch ist hier eine Auswahl nicht mehr möglich:
![grafik](https://user-images.githubusercontent.com/45167567/173177654-a35a910b-9a6b-46d9-ab2c-b225605705fe.png)

Auch nicht bei Eingabe eines Suchwortes:
![grafik](https://user-images.githubusercontent.com/45167567/173177671-041da251-e79c-47b5-828e-1ce0c9897e07.png)

**Comment by erikradisch** [comment]
Sehr seltsam. Bei mir geht es ohne Probleme:

![image](https://user-images.githubusercontent.com/34335811/173180314-51eeb0fa-cd50-453b-b30c-2e3fdd6faea9.png)

hanbe auch extra nochmal den Cache gelöscht...

**Comment by konczaknagel** [comment]
Jetzt geht es wieder.
