### ISSUE TITLE
Painted Representation - Bibliography Selector: Bitte englische Übersetzungen der Buchtitel mit anzeigen lassen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#361]
Bisher stehen nur die originalen asiatischen Titel zur Auswahl

![grafik](https://user-images.githubusercontent.com/45167567/173333471-50015071-6d17-43ae-ad8b-0116938e1820.png)

**Comment by konczaknagel** [comment]
Oh, das mit den Titeln ist jetzt wirklich sehr schön. Es scheint sich aber jetzt die Suchleiste oben etwas verschoben zu haben. Ist es möglich, das Autoren-Fenster größer zu machen?
![grafik](https://user-images.githubusercontent.com/45167567/174083241-d70f4709-7949-4c6a-8c7c-91587999a8fd.png)

**Comment by erikradisch** [comment]
so besser?

**Comment by konczaknagel** [comment]
So ist es hervorragend! Vielen Dank!
