### ISSUE TITLE
PR: Bib. das Feld für die Eingabe des Autor zu klein

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#362]
PR, Bibligraphie: das Feld für die Eingabe des Autor zu klein
![grafik](https://user-images.githubusercontent.com/47562310/174271435-05d0cd01-0009-4017-b3df-672b70ed18ba.png)

**Comment by erikradisch** [comment]
jetzt besser?

**Comment by OKienzler** [comment]
perfekt :D dankeschön
