### ISSUE TITLE
Bitte im Bibliography Selector der Painted Representations die Autorensuche auf Editorensuche ausweiten 

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#367]
Bitte das Suchfeld "Authors" im Bibliography Selector der Painted Representations so einstellen, dass auch Namen der Editoren dort gefunden werden können. Das Suchfeld könnte in "Authors/Editors" umbenannt werden.

**Comment by erikradisch** [comment]
sollte eigentlich bereits klappen. Geht das nicht?

**Comment by konczaknagel** [comment]
Nein, deshalb habe ich diesen Eintrag verfasst. :-)

**Comment by konczaknagel** [comment]
Editoren werden nicht in der Literaturanzeige aufgeführt und vielleicht deshalb nicht gefunden?
![grafik](https://github.com/saw-leipzig/kucha/assets/45167567/c6d208df-5189-4025-8538-ca196ad4a3db)

**Comment by erikradisch** [comment]
jetzt sollte es gehen. Bitte mal in Kuchatest überpürfen.

**Comment by konczaknagel** [comment]
In Kuchatest funktionierts. Danke!
