### ISSUE TITLE
Painted Represenation: Bitte beim Einfügen von Bildern das Markieren von mehreren aufeinanderfolgenden Bilder durch Markierung des ersten und letzten mittels Shift-Taste ermöglichen

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#370]

**Comment by erikradisch** [comment]
Das ganze ist wohl ein Bug. In der neuen Version von dem Framework wurde das gelöst. Das ist aber kostenpflichtig. Ich habe aber einen Workaround gefunden. Wenn ich eine Meldung anzeigen lasse, klappt es wohl. Das ist zwar ein wenig nervig, funktioniert aber. :-) Teste es doch mal bitte in kuchatest aus.

**Comment by konczaknagel** [comment]
Wenn ich das letzte Bild mittels Shift-Taste markieren möchte, springt alles wieder auf das erste Bild, welches dann auch das einzige ist, das markiert ist. Mehrere einzelne Bilder mittels Strg-Taste zu markieren funktioniert. Nur das Markieren von Bildern in Serie nicht.

**Comment by erikradisch** [comment]
Das ist leider ein Bug in dem Framework. Was ich anbieten kann: Mit der Pfeil-Taste geht es trotzdem. also erste Bild, das man braucht markieren, Shift-Taste drücken und dann mit den peieltasten so lange nach oben oder unten bis man bei dem letzten Bild angelangt ist. so kann man mehrere markieren. Habe es gerade in Kuchatest zum Ausprobieren gespielt

**Comment by konczaknagel** [comment]
Danke, das funktioniert in Kuchatest sehr gut!
