### ISSUE TITLE
Manchmal werden keine idealtypischen Bilder angezeigt

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#374]
im Beispiel von "running dog" wird kein idealtypisches Bild angezeigt, wie es früher der Fall war, sondern nur ein "x". Auch bei anderen Einträgen in der Ornamentik ist mir das schon aufgefallen:
![grafik](https://github.com/saw-leipzig/kucha/assets/45167567/d69458af-7dcf-41be-9ebd-43b374bd9ac6)

**Comment by erikradisch** [comment]
Das sollte jetzt gehen. Bitte überprüfen.
