### ISSUE TITLE
Bitte ums Löschen (Annotated Bibliografie Nr. 197)

### ISSUE THREAD

**Issue by JiHoYi** [saw-leipzig/kucha#376]
Lieber Erik,

Ich habe aus Versehen die gleiche Sache zweimal (Annotated Bibliografie Nr. 196 und 197) gespeichert. Das habe ich heute gefunden.
Könntest Du freundlich den Eintrag Nr. 197 löschen?
Ich wünsche Dir einen schönen Tag!

Liebe Grüße
Ji Ho

**Comment by erikradisch** [comment]
Liebe Ji Ho, 

das kannst Du doch selbst über das Minuszeichen, wenn Du den Eintrag öffnest.

Viele Grüße nach Korea,

Erik

**Comment by JiHoYi** [comment]
Lieber Erik,

Hallo! Tut mir leid für die Störung. Es ist inzwischen gelöscht.
Vielen herzlichen Dank für Deine Rückmeldung.
Bis Morgen!

Liebe Grüße
Ji Ho
