### ISSUE TITLE
Darstellung des Registers

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#395]
Das Register ist korrekt dargestellt, stimmt aber nicht mit dem Original überein, vielleicht besprechen wir es am Donnerstag persönlich, dann kann ich erklären was ich meine:

![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/f129272d-fc54-4b13-ab0b-6992a3bce8cb)

das ist Original - zweiter Register fängt auf den rechten Seite mit einer halben Raute an. Im gezeichneten Sketch fängt es (nicht korrekt) mit einer ganzen Raute an. Deshalb werden z.B. die Positionen: Reg. 3 Nr. 4 und Reg. 4 Nr. 5 nicht nebeneinander angezeigt. Tatsächlich ist Reg. 4 Nr. 5 direkt unter Reg. 3 Nr. 4
![Kizil080_CeilingRi_Gen_Tan1981_I_pl180 KLEIN](https://github.com/saw-leipzig/kucha/assets/47562310/e3229477-0ea6-4fb3-ac6f-7bd5be4a8075)

**Comment by erikradisch** [comment]
können wir das schließen?

**Comment by OKienzler** [comment]
Das sieht jetzt supergut aus!!! Es ist toll, Dankeschön!
