### ISSUE TITLE
Positionen Register

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#396]
Bei einer Decke mit 8 Reristern und 8 Nummern erscheint die letzte Reihe mit nur 7 Nummern:

![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/c44273f8-e6ff-4f18-8b4b-6d2d353a043f)

**Comment by erikradisch** [comment]
Die geraden Reihen haben immer eine weniger. Das hat was mit der Versetzung zu tun. Wie können wir das denn sonst lösen?

**Comment by OKienzler** [comment]
Habe allle "empty spots" gesetzt. Wollte eine Position Reg. 8, Nr. 8 setzen. Es wird in diesem Feld Reg. 8, Nr. 7 (anstatt Reg. 8 Nr. 8) angezeigt:

![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/fbf37f24-010b-48bd-9106-1d8d3b2d61f7)

**Comment by erikradisch** [comment]
jetzt geht es, oder?

**Comment by OKienzler** [comment]
Das geht jetzt perfekt! Super!
