### ISSUE TITLE
Empty Spot wird nicht gespeichert

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#397]
Trotz des Löschen des Cache "Empty Spot" wird nicht gespeichert: z.B. ID 834, gespeichert beim Schließen der Kachel

**Comment by erikradisch** [comment]
welche kachel sollte denn gesperrt werden?

**Comment by OKienzler** [comment]
ID 834

**Comment by erikradisch** [comment]
das habe ich gelesen. :-) Ich merine Register und nummer

**Comment by OKienzler** [comment]
Achso, rechts; REg 1, No 1
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/7434c02e-f428-4503-bd25-4c81aee31196)

**Comment by OKienzler** [comment]
Das Speichern hat einmal funktioniert und jetzt stockt es wieder:
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/e6c2e66e-c46c-4adc-bbe2-50c1970ca2cb)

**Comment by OKienzler** [comment]
Jetzt wurde alles gespeichert, aber alles extrem langsam, immer wieder neu laden ist erfrderlich und immer wieder kommt die Meldung "retry saving"

![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/0a6e7d1d-a821-46a5-a918-07b7630cde66)

**Comment by erikradisch** [comment]
das laden sollte jetzt viel schneller gehen. Wird ordentlich abgepseichert?

**Comment by OKienzler** [comment]
Es die ersten 20 min tadellos funktioniert und jetzt geht es wieder nicht. Z.B. in der ID 1287 habe ich bereits reg und no gesetzt und seite erneuert. Die Position wurde nicht gespeichert und jetzt auch die Höhle wird nicht geladen:
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/eb76c9a6-bd4d-4427-9950-0701358d3860)

**Comment by erikradisch** [comment]
da hattest du das Registersystem erst neu angelegt und dann auch gleich eine position gesetzt?

**Comment by OKienzler** [comment]
Nee, habe kein neues REgistersystem angelegt

**Comment by OKienzler** [comment]
Perfekt! Funktioniert alles, toll!
