### ISSUE TITLE
Ornamentik: Eingabe löschen

### ISSUE THREAD

**Issue by LucaDeF** [saw-leipzig/kucha#399]
Bitte löschen den mit 'delete' markierten Einträge in der Baumstruktur: Nrn. 2351, 2365 (Decoration&Ornaments/Geometric Motifs/delete) und 2961, 2962 (Decoration&Ornaments/Imitative Motifs/Imititations of Architectural Elements/delete).

**Comment by erikradisch** [comment]
schau mal bitte in Kucha-test. Da solltest Du jetzt selbst die Möglichkeit haben, Einträge zu löschen. Einfach auf iconographie-eintrag bearbeiten klicken. Neben dem speichern button gibt es da jetzt auch ein Minus, was den Eintrag löscht, solange er keine Kinder hat und nirgends verwendet wird.
