### ISSUE TITLE
Painted Representation - Taxomie-Baum: Einträge verschieben

### ISSUE THREAD

**Issue by konczaknagel** [saw-leipzig/kucha#400]
Wir würden gern die Einträge "bull" & "cow" als child-Elemente unter "bovine" subsumieren. Wir machen es gern selbst, wenn wir die technische Möglichkeit dazu haben.

**Comment by erikradisch** [comment]
schau Dir mal kuchatest an. Da kannst Du jetzt einfach einen eintrag zu einem neuen parent ziehen und so neu verknüpfen. Probiers mal aus. Ich bin allerdings schwer am Überlegen, ob wir den Benutzerkreis, der sowas darf nicht lieder stark einschränken. Was meinst Du?

**Comment by konczaknagel** [comment]
Das Verschieben klappt bei mir leider nicht. Muss ich irgendetwas beachten?
Bisher bin ich nur diejenige, die überhaupt Einträge im Bäumchen vornehmen darf (weiß nicht ob Monika noch Berechtigungen hat). Mir wäre es auch lieb, wenn es so bliebe. Ebenso mit dem Verschieben der Einträge.

**Comment by erikradisch** [comment]
das geht so bei Dir nicht?
[Screencast from 25.01.2024 13:27:24.webm](https://github.com/saw-leipzig/kucha/assets/34335811/d839aa47-3bc3-4392-a5c6-79e2285df304)

**Comment by konczaknagel** [comment]
Achso, doch in der Testumgebung funktioniert es. Hatte es im Backend probiert und dort geht es (noch) nicht.
