### ISSUE TITLE
Hochladen von Bildern funktioniert nicht 

### ISSUE THREAD

**Issue by DomKlimaszewski** [saw-leipzig/kucha#411]

**Comment by erikradisch** [comment]
sollte wieder gehen, oder?

**Comment by DomKlimaszewski** [comment]
ja es geht, habe es gerade ausprobiert. Danke!

 
 

Gesendet: Montag, 29. Januar 2024 um 13:46 Uhr
Von: "erikradisch" ***@***.***>
An: "saw-leipzig/kucha" ***@***.***>
Cc: "DomKlimaszewski" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [saw-leipzig/kucha] Hochladen von Bildern funktioniert nicht (Issue #411)


 

sollte wieder gehen, oder?
