### ISSUE TITLE
"Empty spot" rausnehmen 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#416]
Das Rausnehmen von "Empty spot" funktioniert zuerst mal, aber nach dem Speichern und erneutem Laden ist das zuvor gesetzte und gelöschte "empty spot" ist wieder da (Beispiel PR IT 1486): 
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/8c379d43-10ca-4d47-9b67-42a3330bc8ab)

**Comment by erikradisch** [comment]
Überprüfe das bitte noch einmal, ich denke, das lag nur an den alten Einträgen, die im System rumgeisterten.

**Comment by OKienzler** [comment]
das funktioniert immer noch nicht

**Comment by OKienzler** [comment]
habe eben versucht empty spot in PR ID 1276 (in Kucha Text) zu entfernen, es kommt diese Meldung und nach erneutem Laden der PR Änderung in der PR wurde tatsächlich nicht übernommen:
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/5af8f2dc-e693-47dd-8c3c-7e93a9cdca70)

**Comment by OKienzler** [comment]
Die Anzeige der Positionen stimmt nicht überein; hier soll von rechts gezählt werden; also reg. 5 und no. 5 
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/c1f09cb5-c9e2-4b62-92dd-84bc1306a018)

**Comment by OKienzler** [comment]
"empty spots" zu löschen bei dem neu gesetzten Positionsregister (in PR 2076) hat funktioniert; aber bei älteren (PR 1276) kommt nicht Fehlermeldung mit dem Speichern: 
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/0bb60b99-9ccd-439b-b0dc-5a77d1b516c8)

**Comment by OKienzler** [comment]
Problem immer noch aktuell (aus Versehen geschlossen :))

**Comment by OKienzler** [comment]
so wird es später nicht erscheinen, oder? Lässt sich Registersystem an die "richtige" Stelle wieder verschiben?
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/4b741c2f-e841-4833-b6ac-c1380c2c537c)

**Comment by OKienzler** [comment]
rausnehmen von empty spots funktioniert jetzt auch in den "älteren" PR.

**Comment by OKienzler** [comment]
kann hier automatisch "blanko" und nicht wallsketch erscheinen?
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/12f59441-dd42-4617-949c-2af88061ac49)

**Comment by erikradisch** [comment]
ist das in Kucha-test? Da ist das in Ordnung. Hat was mit den IDs zu tun. Im Backend kommt ja der blank standardmäßig.

**Comment by erikradisch** [comment]
nein, noch nicht. Aber das hier liegt schlicht daran, dass die sketche andere IDs haben, als im Backend. Da musst Du dir also keine Sorgen machen.

**Comment by OKienzler** [comment]
gut, dann kann ich die issue hier schlißen, Dankeschön!
