### ISSUE TITLE
Positionsraster nicht sichtbar

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#417]
Positionsraster für ceiling left ist bereits gezeichnet, wird aber hier nicht angezeigt. Vielleicht liegt es daran, dass in dieser PR keine Positionen zuvor erfasst wurden?
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/454b35ff-fff7-4f7c-9eda-46b372262b5c)

**Comment by erikradisch** [comment]
Genau! Das wird in der PR nur angezeigt, wenn die PR selbst verortet wurde.
