### ISSUE TITLE
Anzeige der Anzahl der Ergebnisse in PR 

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#421]
Hier (PR) wäre es gut die Anzahl der Ergebnisse der Suche zu sehen:

![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/6b9077a2-56b5-42da-89d8-48d69c8f2992)

**Comment by erikradisch** [comment]
ist jetzt drin. Bitte überprüfen (schon im richtigen)

**Comment by OKienzler** [comment]
ist da, super, Dankeschön!
