### ISSUE TITLE
Sketch wird nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#423]
An dieser Stelle wird unser Sketch nicht angezeigt
![grafik](https://github.com/saw-leipzig/kucha/assets/47562310/e87e3003-b740-4b71-9ba1-b8dbd4b01ce1)

**Comment by erikradisch** [comment]
sollte wieder angeeigt werden.

**Comment by OKienzler** [comment]
jap, ist wieder da, Dankeschön!
