### ISSUE TITLE
Annotation nicht gespeichert

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#424]
habe gerade eine Annotation gemacht, die wurde leider nicht gespeichert; PR ID 2198; Nummer im Bäumchen 1305

**Comment by erikradisch** [comment]
sollte wieder gehen, bitte überprüfen

**Comment by OKienzler** [comment]
diese meldung kam:
![image](https://github.com/user-attachments/assets/082898fb-8d3b-424c-a901-0f8a56109282)

**Comment by OKienzler** [comment]
Es wurde aber gespeichert, probiere gleich noch eine

**Comment by OKienzler** [comment]
DAs Annotieren ist jetyt extrem sperrlich, ich muss es Dir zeigen. Oder probiere es kurz selbst aus, dann weisst Du was ich meine, kann man nicht so gut erklären. Alleine eine Annotation zu starten ist sehr sperrlich

**Comment by erikradisch** [comment]
jetzt geht es wieder zu öffnen. Der cave ist da schon seit Oktober letzten Jahres nicht mehr drin. Insgesamt gibt es 41 davon. Die können wir morgen mal zusammen durchgehen und wieder herstellen. Was meinst Du?

**Comment by OKienzler** [comment]
﻿
Jap, das machen wir

**Comment by erikradisch** [comment]
das kann geschlossen werden, oder?

**Comment by OKienzler** [comment]
Jap, Dankeschön, habe eben noch mal ausprobiert, es funktioniert sehr gut!
