### ISSUE TITLE
Examples: Infos in welchen Höhlen es vorhanden ist, ist nicht mehr da (z.B. ID 287)

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#426]
![image](https://github.com/user-attachments/assets/9da7f512-9af2-4c36-ad3e-dd7e3baf94ac)

**Comment by erikradisch** [comment]
ist wieder da, bitte überpürfen

**Comment by OKienzler** [comment]
jap, ist jetzt da, aber was bedeuten diese Nummern?

![Uploading image.png…]()

**Comment by OKienzler** [comment]
![image](https://github.com/user-attachments/assets/6a5ff3d2-9e17-4833-b1ef-911b6164a566)

**Comment by erikradisch** [comment]
ist weg, bitte prüfen.

**Comment by OKienzler** [comment]
jetzt passt wieder alles, Dankeschön
