### ISSUE TITLE
3 Bilder in Examples angezeigt (anstatt zwei)

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#427]
3 Bilder in Examples angezeigt (anstatt zwei), vielleicht hängt es damit zusammen, dass das eine Bild aus Kiz 176 ist, sprich in der Höhle wo eine weitere Darstellung der Story ist 

![image](https://github.com/user-attachments/assets/52328dee-b548-4a65-993c-fa628c187c08)

**Comment by erikradisch** [comment]
Diese Auswahl richtet sich danach, in welcher PR die Bilder der Typicals verwendet werden, um sie dann zu verknüpfen. Die Auswahl, welche von den PRs zu nehmen sind, müsst ihr noch machen. Das kann das System nicht entscheiden. Das System macht hier jedenfalls alles richtig.

**Comment by OKienzler** [comment]
﻿
﻿
Vielleicht kannst Du es mir morgen erklären, bin im Zug gerade; es ist dann eine neue Vorgehensweise.

**Comment by OKienzler** [comment]
Ist nicht klar warum hier ein Bild aus Kiz176 (PR ID 2216) erscheint, weil die typical bilder aus anderen PRs stammen:
![image](https://github.com/user-attachments/assets/bb682161-6263-4fd6-83cc-4d46551578ca)

**Comment by erikradisch** [comment]
weil pr 2216 auch das Bild 28736 hat. Vielleicht sollte es das nicht haben?

**Comment by OKienzler** [comment]
Ja, das war das Problem, ich habe es jetzt geändert und es passt, Dankeschön!
