### ISSUE TITLE
Ikonografieauswahl wird nicht angezeigt

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#429]
![image](https://github.com/user-attachments/assets/cba8ac3b-2b91-42a7-877c-599ec3ddea8f)

**Comment by erikradisch** [comment]
Reden wir über unterschiedliche Dinge, bei mir ging es. siehe Video:
[Screencast from 2024-08-01 20-24-44.webm](https://github.com/user-attachments/assets/78e55a02-87e9-459f-a520-692b9f2b1a3a)

**Comment by OKienzler** [comment]
Wenn eine PR aufmache und auf dieses Symbol (Nr. 3) klicke, geht das ganze Baum auf; klicke ich noch mal drauf geht es zu und ab diesem Punkt stockts es. Keinen von den Buttos, also 1, 2 und 3 reagieren. Was ich anschauen wollte war ein aufgeklapptes Baum mit ausgewählter Ikonographie; es gibt jetzt keine Möglichkeit es zu sehen:
![image](https://github.com/user-attachments/assets/645b2ea2-1646-4ebc-a320-39a882689f66)

**Comment by erikradisch** [comment]
schau mal in kuchatest, ob es jetzt wieder geht.

**Comment by OKienzler** [comment]
in der Testversion geht die Suche nicht, z.B. habe ich nach Preta gesucht: 
![image](https://github.com/user-attachments/assets/8163dfba-f1f8-48eb-aac6-7340b52b1fb3)

**Comment by OKienzler** [comment]
Der Baum geht hier mit diesem Button auf und zu, und der anderer button geht auch; also funktioniert es mit der Anzeige des Baums, Dankeschön:
![image](https://github.com/user-attachments/assets/10f7d215-94fb-4603-95c4-fee4ae92d866)

**Comment by OKienzler** [comment]
Nur die Suche nach preta, geht hier nicht:
![image](https://github.com/user-attachments/assets/3b068ca6-3a2f-447e-acc7-b66df6140cac)

**Comment by erikradisch** [comment]
sollte wieder gehen. bitte in Kuchatest überprüfen.

**Comment by OKienzler** [comment]
Dankeschön, das geht jetzt alles!

ich sehe jetzt dieses anstatt vom Bild und Annotation, könntest Du es bitte prüfen: 
![image](https://github.com/user-attachments/assets/3baeb8ef-3f62-48dd-b874-10169f964250)

**Comment by OKienzler** [comment]
ID 152 in PR in der Testversion

**Comment by erikradisch** [comment]
das habe ich da mal hochgeladen. :-) Das war ein Test. Kannst Du gerne wieder durch das Original ersetzen.

**Comment by OKienzler** [comment]
ok, dann passt es, Dankeschön!

**Comment by OKienzler** [comment]
Leider ist wieder das gleiche Problem da:
Wenn eine PR aufmache und auf dieses Symbol (Nr. 3) klicke, geht das ganze Baum auf; klicke ich noch mal drauf geht es zu und ab diesem Punkt stockts es. Keinen von den Buttos, also 1, 2 und 3 reagieren. Was ich anschauen wollte war ein aufgeklapptes Baum mit ausgewählter Ikonographie; es gibt jetzt keine Möglichkeit es zu sehen:

https://private-user-images.githubusercontent.com/47562310/354514811-645b2ea2-1646-4ebc-a320-39a882689f66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTcxODEsIm5iZiI6MTcyOTE1Njg4MSwicGF0aCI6Ii80NzU2MjMxMC8zNTQ1MTQ4MTEtNjQ1YjJlYTItMTY0Ni00ZWJjLWEzMjAtMzlhODgyNjg5ZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5MjEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZmFhMWVlNDc1YTliZDM2MmM5OWVhMGRlNmIyMzUwYzI1NzU3MjMwMWVhOWI1OGZkOGU2N2Y5YzRkZTZhZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4_gGEWtooE-bttpZ2odmf7TyId-WLh6LYE0zSDNhzOM

**Comment by erikradisch** [comment]
Ich sehe leider das Bild nicht, da ging wohl was schief. Jedenfalls habe ich es versucht, mit dem auf und zuklappen. Bei mir ging es. Kannst Du es nochmal probieren? Eventuell hat sich das ja durch die neue Version erledigt.
