### ISSUE TITLE
gespeicherte Änderungen werden nicht übernommen

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#430]
gespeicherte Änderungen in PR werden erst nach dem Löschen des cach sichtbar, z.B. PR 2586, von "privat" auf "public" gesetzt und gespeichert. Änderung war nicht sichtbar bis ich cach gelöscht habe.

**Comment by erikradisch** [comment]
probier mal aus. geht es jetzt wieder?

**Comment by OKienzler** [comment]
das geht jetzt wieder, Dankeschön!
