### ISSUE TITLE
Iconography element kann nicht ausgewählt werden

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#431]
Iconography element kann nicht ausgewählt werden, z.B. ich möchte Siva anklicken, aber das Setzen des Häkchen funktioniert nicht:

![grafik](https://github.com/user-attachments/assets/a3007af7-4557-4306-9ae2-098d2bc2c600)

**Comment by erikradisch** [comment]
probier mal, sollte jetzt wieder gehen. Ich musste allerdings den Cache löschen.

**Comment by OKienzler** [comment]
Dankeschön, es geht wieder.
