### ISSUE TITLE
Einer fertigen Annotation kann im "Iconography Selector" keine Benennung hinzugefügt werden. Oft werden nur "Pictorial Elements" oder "Iconography" angezeigt. Nach dem Speichervorgang erscheint die Information "droping unselected" und die Annoation wird nicht gespeichert.

### ISSUE THREAD

**Issue by DomKlimaszewski** [saw-leipzig/kucha#433]

**Comment by erikradisch** [comment]
probier mal, ob das speichern jetzt wieder in Kuchatest geht?

**Comment by DomKlimaszewski** [comment]
Der Speichervorgang funktioniert in kuchatest.

Das "x" zum Entfernen eines Punktes bei einer Annotation funktioniert auch. Nur wenn ich die Annotation bearbeitet habe und dann auf "ok" drücke verschwindet die Annotation. Sie ist nach dem Neuladen aber wieder da.

 

Gesendet: Donnerstag, 24. Oktober 2024 um 13:57 Uhr
Von: "erikradisch" ***@***.***>
An: "saw-leipzig/kucha" ***@***.***>
Cc: "DomKlimaszewski" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [saw-leipzig/kucha] Einer fertigen Annotation kann im "Iconography Selector" keine Benennung hinzugefügt werden. Oft werden nur "Pictorial Elements" oder "Iconography" angezeigt. Nach dem Speichervorgang erscheint die Information "droping unselected" und die Annoation wird nicht gespeichert. (Issue #433)


 

probier mal, ob das speichern jetzt wieder in Kuchatest geht?

**Comment by erikradisch** [comment]
das habe ich behoben.
Ich würde dann die neue version gleich mal ausspielen. dann kannst Du gleich annotieren.
