### ISSUE TITLE
Registersystem in Backend

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#435]
kann das Registersystem in Backend schon wieder benutzt werden? wenn ja, stimmt da was nicht, ich wollte mal SWRi in Kiz 63 aufräumen, geht aber nicht. Könntest Du Dir bitte die PR IDs 2556, ID 2631 und ID 2631 anschauen und am besten alle löschen (ich konnte die nicht löschen) und ich lege es dann neu an.

**Comment by erikradisch** [comment]
ich habe mal rein geschaut. Meinst Du nur die Verbindungen? Die habe ich gelöscht. Seltsam war eine Verbindung zu einer Depiction 0. Das behalte ich mal im Auge.
Oder woll ich auch die Registersysteme löschen?

**Comment by OKienzler** [comment]
ja, es war doppelt, jetzt konnte ich es löschen. Es hat sich zuerst mal erledigt.
