### ISSUE TITLE
Register editor

### ISSUE THREAD

**Issue by OKienzler** [saw-leipzig/kucha#437]
Register für die linke Wand ist schon seit ein paar Wochen in PR 2625 drin; wenn ich eine neue PR für Kzg 13 für die rechte Wand anlege, sehe ich die linke Wand nicht; auch nicht nach dem Speichern der neuen Kachel.
PR 2625 (lange angelegt)
![grafik](https://github.com/user-attachments/assets/e4b281b8-055b-4d70-b503-dd4d1c465502)
PR 2629 (heute angelegt)
![grafik](https://github.com/user-attachments/assets/c6ee40d6-a0f4-4a38-bf7b-e938c542e125)

**Comment by erikradisch** [comment]
Lieber Luca,

linke und rechte Wand sollten doch zwei unterschiedliche Register bekommen, oder?
Ich würde sie auch nicht automatisch anlegen lassen, weil die ja durchaus unterschiedlich sien können.
Wie ich sehe, hat Du ja auch nun schon für 2649 ein neues Registersystem an der rechten Wand erzeugt, oder?

**Comment by OKienzler** [comment]
Ja, genau rechts und links sind zwei unterschiedliche Register. Genau, die können auch untererschiedlich sein, also automatisches Anlegen soll nicht sein. 
Ja, ich habe für 2649 ein neues Registersystem für die rechte Wand angelegt. Früher war es so dass ich als "Info" beiden Wände immer gesehen habe, die rechte und linke - wird es jetzt anders sein?

**Comment by erikradisch** [comment]
Ich glaube, das hattest Du verwechselt. Rechts und Links waren da an ein und der selben Wand gemeint. aber das habe ich jetzt glaube ich rausgenommen. Jetzt kann man die Register ja direkt am Canvas so ausrichten, dass es passt, sollte man mehrere Register an einer Wand oder Decke haben.

**Comment by OKienzler** [comment]
Achso, das macht Sinn, ich hoffe dass wir nicht an einander vorbeireden :) wir können es uns noch mal zusammen anschauen wenn wir beide wieder im Büro sind
