### ISSUE TITLE
Type Forward, z.B. für Höhlenauswahl

### ISSUE THREAD

**Issue by alingnau** [saw-leipzig/kucha#83]

**Comment by konczaknagel** [comment]
- für Höhlenauswahl
- für Bibliography Selector in Painted Representations

**Comment by alingnau** [comment]
BibliographySelector hat aktuell umfangreiche Suchfunktionen. Neue Version wird verbesserte Suche unterstützen.
Forward Typing für Höhen in Depiction implementiert
